/*
OpenApp API

Testing StatusAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/tomers/openapp-sdk/go"
	"testing"
)

func Test_openapi_StatusAPIService(t *testing.T) {

	apiKey := "http://127.0.0.1:1/api/v1_openapp_testsecret"
	apiClient, err := openapiclient.NewAPIClient(apiKey)
	require.NoError(t, err)
	t.Cleanup(func() { _ = apiClient.Close() })

	t.Run("Test StatusAPIService GetBackendStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.StatusAPI.GetBackendStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
