/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseAgentResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseAgentResponseItemsInner{}

// PaginatedResponseAgentResponseItemsInner struct for PaginatedResponseAgentResponseItemsInner
type PaginatedResponseAgentResponseItemsInner struct {
	AllowedEntityIds []string       `json:"allowed_entity_ids,omitempty"`
	AllowedPortalIds []string       `json:"allowed_portal_ids,omitempty"`
	AllowedToolNames []string       `json:"allowed_tool_names,omitempty"`
	ConfirmationMode string         `json:"confirmation_mode"`
	CreatedAt        NullableString `json:"created_at,omitempty"`
	ExpiresAt        NullableString `json:"expires_at,omitempty"`
	Id               string         `json:"id"`
	LastUsedAt       NullableString `json:"last_used_at,omitempty"`
	Name             string         `json:"name"`
	OrgId            string         `json:"org_id"`
	OwnerUserId      string         `json:"owner_user_id"`
	Purpose          NullableString `json:"purpose,omitempty"`
	RevokedAt        NullableString `json:"revoked_at,omitempty"`
	UpdatedAt        NullableString `json:"updated_at,omitempty"`
}

type _PaginatedResponseAgentResponseItemsInner PaginatedResponseAgentResponseItemsInner

// NewPaginatedResponseAgentResponseItemsInner instantiates a new PaginatedResponseAgentResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseAgentResponseItemsInner(confirmationMode string, id string, name string, orgId string, ownerUserId string) *PaginatedResponseAgentResponseItemsInner {
	this := PaginatedResponseAgentResponseItemsInner{}
	this.ConfirmationMode = confirmationMode
	this.Id = id
	this.Name = name
	this.OrgId = orgId
	this.OwnerUserId = ownerUserId
	return &this
}

// NewPaginatedResponseAgentResponseItemsInnerWithDefaults instantiates a new PaginatedResponseAgentResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseAgentResponseItemsInnerWithDefaults() *PaginatedResponseAgentResponseItemsInner {
	this := PaginatedResponseAgentResponseItemsInner{}
	return &this
}

// GetAllowedEntityIds returns the AllowedEntityIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetAllowedEntityIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedEntityIds
}

// GetAllowedEntityIdsOk returns a tuple with the AllowedEntityIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetAllowedEntityIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedEntityIds) {
		return nil, false
	}
	return o.AllowedEntityIds, true
}

// HasAllowedEntityIds returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasAllowedEntityIds() bool {
	if o != nil && !IsNil(o.AllowedEntityIds) {
		return true
	}

	return false
}

// SetAllowedEntityIds gets a reference to the given []string and assigns it to the AllowedEntityIds field.
func (o *PaginatedResponseAgentResponseItemsInner) SetAllowedEntityIds(v []string) {
	o.AllowedEntityIds = v
}

// GetAllowedPortalIds returns the AllowedPortalIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetAllowedPortalIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedPortalIds
}

// GetAllowedPortalIdsOk returns a tuple with the AllowedPortalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetAllowedPortalIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedPortalIds) {
		return nil, false
	}
	return o.AllowedPortalIds, true
}

// HasAllowedPortalIds returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasAllowedPortalIds() bool {
	if o != nil && !IsNil(o.AllowedPortalIds) {
		return true
	}

	return false
}

// SetAllowedPortalIds gets a reference to the given []string and assigns it to the AllowedPortalIds field.
func (o *PaginatedResponseAgentResponseItemsInner) SetAllowedPortalIds(v []string) {
	o.AllowedPortalIds = v
}

// GetAllowedToolNames returns the AllowedToolNames field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetAllowedToolNames() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedToolNames
}

// GetAllowedToolNamesOk returns a tuple with the AllowedToolNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetAllowedToolNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedToolNames) {
		return nil, false
	}
	return o.AllowedToolNames, true
}

// HasAllowedToolNames returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasAllowedToolNames() bool {
	if o != nil && !IsNil(o.AllowedToolNames) {
		return true
	}

	return false
}

// SetAllowedToolNames gets a reference to the given []string and assigns it to the AllowedToolNames field.
func (o *PaginatedResponseAgentResponseItemsInner) SetAllowedToolNames(v []string) {
	o.AllowedToolNames = v
}

// GetConfirmationMode returns the ConfirmationMode field value
func (o *PaginatedResponseAgentResponseItemsInner) GetConfirmationMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfirmationMode
}

// GetConfirmationModeOk returns a tuple with the ConfirmationMode field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAgentResponseItemsInner) GetConfirmationModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfirmationMode, true
}

// SetConfirmationMode sets field value
func (o *PaginatedResponseAgentResponseItemsInner) SetConfirmationMode(v string) {
	o.ConfirmationMode = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *PaginatedResponseAgentResponseItemsInner) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableString and assigns it to the ExpiresAt field.
func (o *PaginatedResponseAgentResponseItemsInner) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetId returns the Id field value
func (o *PaginatedResponseAgentResponseItemsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAgentResponseItemsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaginatedResponseAgentResponseItemsInner) SetId(v string) {
	o.Id = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetLastUsedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasLastUsedAt() bool {
	if o != nil && o.LastUsedAt.IsSet() {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given NullableString and assigns it to the LastUsedAt field.
func (o *PaginatedResponseAgentResponseItemsInner) SetLastUsedAt(v string) {
	o.LastUsedAt.Set(&v)
}

// SetLastUsedAtNil sets the value for LastUsedAt to be an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) SetLastUsedAtNil() {
	o.LastUsedAt.Set(nil)
}

// UnsetLastUsedAt ensures that no value is present for LastUsedAt, not even an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) UnsetLastUsedAt() {
	o.LastUsedAt.Unset()
}

// GetName returns the Name field value
func (o *PaginatedResponseAgentResponseItemsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAgentResponseItemsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PaginatedResponseAgentResponseItemsInner) SetName(v string) {
	o.Name = v
}

// GetOrgId returns the OrgId field value
func (o *PaginatedResponseAgentResponseItemsInner) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAgentResponseItemsInner) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *PaginatedResponseAgentResponseItemsInner) SetOrgId(v string) {
	o.OrgId = v
}

// GetOwnerUserId returns the OwnerUserId field value
func (o *PaginatedResponseAgentResponseItemsInner) GetOwnerUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAgentResponseItemsInner) GetOwnerUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerUserId, true
}

// SetOwnerUserId sets field value
func (o *PaginatedResponseAgentResponseItemsInner) SetOwnerUserId(v string) {
	o.OwnerUserId = v
}

// GetPurpose returns the Purpose field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetPurpose() string {
	if o == nil || IsNil(o.Purpose.Get()) {
		var ret string
		return ret
	}
	return *o.Purpose.Get()
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purpose.Get(), o.Purpose.IsSet()
}

// HasPurpose returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasPurpose() bool {
	if o != nil && o.Purpose.IsSet() {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given NullableString and assigns it to the Purpose field.
func (o *PaginatedResponseAgentResponseItemsInner) SetPurpose(v string) {
	o.Purpose.Set(&v)
}

// SetPurposeNil sets the value for Purpose to be an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) SetPurposeNil() {
	o.Purpose.Set(nil)
}

// UnsetPurpose ensures that no value is present for Purpose, not even an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) UnsetPurpose() {
	o.Purpose.Unset()
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt.Get()) {
		var ret string
		return ret
	}
	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetRevokedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasRevokedAt() bool {
	if o != nil && o.RevokedAt.IsSet() {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given NullableString and assigns it to the RevokedAt field.
func (o *PaginatedResponseAgentResponseItemsInner) SetRevokedAt(v string) {
	o.RevokedAt.Set(&v)
}

// SetRevokedAtNil sets the value for RevokedAt to be an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) SetRevokedAtNil() {
	o.RevokedAt.Set(nil)
}

// UnsetRevokedAt ensures that no value is present for RevokedAt, not even an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) UnsetRevokedAt() {
	o.RevokedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAgentResponseItemsInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAgentResponseItemsInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAgentResponseItemsInner) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableString and assigns it to the UpdatedAt field.
func (o *PaginatedResponseAgentResponseItemsInner) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *PaginatedResponseAgentResponseItemsInner) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o PaginatedResponseAgentResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedEntityIds != nil {
		toSerialize["allowed_entity_ids"] = o.AllowedEntityIds
	}
	if o.AllowedPortalIds != nil {
		toSerialize["allowed_portal_ids"] = o.AllowedPortalIds
	}
	if o.AllowedToolNames != nil {
		toSerialize["allowed_tool_names"] = o.AllowedToolNames
	}
	toSerialize["confirmation_mode"] = o.ConfirmationMode
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	toSerialize["id"] = o.Id
	if o.LastUsedAt.IsSet() {
		toSerialize["last_used_at"] = o.LastUsedAt.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["org_id"] = o.OrgId
	toSerialize["owner_user_id"] = o.OwnerUserId
	if o.Purpose.IsSet() {
		toSerialize["purpose"] = o.Purpose.Get()
	}
	if o.RevokedAt.IsSet() {
		toSerialize["revoked_at"] = o.RevokedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

func (o *PaginatedResponseAgentResponseItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"confirmation_mode",
		"id",
		"name",
		"org_id",
		"owner_user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseAgentResponseItemsInner := _PaginatedResponseAgentResponseItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedResponseAgentResponseItemsInner)

	if err != nil {
		return err
	}

	*o = PaginatedResponseAgentResponseItemsInner(varPaginatedResponseAgentResponseItemsInner)

	return err
}

type NullablePaginatedResponseAgentResponseItemsInner struct {
	value *PaginatedResponseAgentResponseItemsInner
	isSet bool
}

func (v NullablePaginatedResponseAgentResponseItemsInner) Get() *PaginatedResponseAgentResponseItemsInner {
	return v.value
}

func (v *NullablePaginatedResponseAgentResponseItemsInner) Set(val *PaginatedResponseAgentResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseAgentResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseAgentResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseAgentResponseItemsInner(val *PaginatedResponseAgentResponseItemsInner) *NullablePaginatedResponseAgentResponseItemsInner {
	return &NullablePaginatedResponseAgentResponseItemsInner{value: val, isSet: true}
}

func (v NullablePaginatedResponseAgentResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseAgentResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
