/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkillResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillResponse{}

// SkillResponse struct for SkillResponse
type SkillResponse struct {
	AgentId           string      `json:"agent_id"`
	Enabled           bool        `json:"enabled"`
	Id                string      `json:"id"`
	Name              string      `json:"name"`
	OrgId             string      `json:"org_id"`
	Steps             []SkillStep `json:"steps"`
	TriggerEventTypes []string    `json:"trigger_event_types"`
	Version           int32       `json:"version"`
}

type _SkillResponse SkillResponse

// NewSkillResponse instantiates a new SkillResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillResponse(agentId string, enabled bool, id string, name string, orgId string, steps []SkillStep, triggerEventTypes []string, version int32) *SkillResponse {
	this := SkillResponse{}
	this.AgentId = agentId
	this.Enabled = enabled
	this.Id = id
	this.Name = name
	this.OrgId = orgId
	this.Steps = steps
	this.TriggerEventTypes = triggerEventTypes
	this.Version = version
	return &this
}

// NewSkillResponseWithDefaults instantiates a new SkillResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillResponseWithDefaults() *SkillResponse {
	this := SkillResponse{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *SkillResponse) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *SkillResponse) SetAgentId(v string) {
	o.AgentId = v
}

// GetEnabled returns the Enabled field value
func (o *SkillResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SkillResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetId returns the Id field value
func (o *SkillResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SkillResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SkillResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SkillResponse) SetName(v string) {
	o.Name = v
}

// GetOrgId returns the OrgId field value
func (o *SkillResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *SkillResponse) SetOrgId(v string) {
	o.OrgId = v
}

// GetSteps returns the Steps field value
func (o *SkillResponse) GetSteps() []SkillStep {
	if o == nil {
		var ret []SkillStep
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetStepsOk() ([]SkillStep, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *SkillResponse) SetSteps(v []SkillStep) {
	o.Steps = v
}

// GetTriggerEventTypes returns the TriggerEventTypes field value
func (o *SkillResponse) GetTriggerEventTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TriggerEventTypes
}

// GetTriggerEventTypesOk returns a tuple with the TriggerEventTypes field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetTriggerEventTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TriggerEventTypes, true
}

// SetTriggerEventTypes sets field value
func (o *SkillResponse) SetTriggerEventTypes(v []string) {
	o.TriggerEventTypes = v
}

// GetVersion returns the Version field value
func (o *SkillResponse) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SkillResponse) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SkillResponse) SetVersion(v int32) {
	o.Version = v
}

func (o SkillResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	toSerialize["enabled"] = o.Enabled
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["org_id"] = o.OrgId
	toSerialize["steps"] = o.Steps
	toSerialize["trigger_event_types"] = o.TriggerEventTypes
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *SkillResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_id",
		"enabled",
		"id",
		"name",
		"org_id",
		"steps",
		"trigger_event_types",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkillResponse := _SkillResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkillResponse)

	if err != nil {
		return err
	}

	*o = SkillResponse(varSkillResponse)

	return err
}

type NullableSkillResponse struct {
	value *SkillResponse
	isSet bool
}

func (v NullableSkillResponse) Get() *SkillResponse {
	return v.value
}

func (v *NullableSkillResponse) Set(val *SkillResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillResponse(val *SkillResponse) *NullableSkillResponse {
	return &NullableSkillResponse{value: val, isSet: true}
}

func (v NullableSkillResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
