/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AcceptEulaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcceptEulaRequest{}

// AcceptEulaRequest Request to accept EULA and provision user
type AcceptEulaRequest struct {
	Accepted bool `json:"accepted"`
}

type _AcceptEulaRequest AcceptEulaRequest

// NewAcceptEulaRequest instantiates a new AcceptEulaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptEulaRequest(accepted bool) *AcceptEulaRequest {
	this := AcceptEulaRequest{}
	this.Accepted = accepted
	return &this
}

// NewAcceptEulaRequestWithDefaults instantiates a new AcceptEulaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptEulaRequestWithDefaults() *AcceptEulaRequest {
	this := AcceptEulaRequest{}
	return &this
}

// GetAccepted returns the Accepted field value
func (o *AcceptEulaRequest) GetAccepted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value
// and a boolean to check if the value has been set.
func (o *AcceptEulaRequest) GetAcceptedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accepted, true
}

// SetAccepted sets field value
func (o *AcceptEulaRequest) SetAccepted(v bool) {
	o.Accepted = v
}

func (o AcceptEulaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accepted"] = o.Accepted
	return toSerialize, nil
}

func (o *AcceptEulaRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accepted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAcceptEulaRequest := _AcceptEulaRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAcceptEulaRequest)

	if err != nil {
		return err
	}

	*o = AcceptEulaRequest(varAcceptEulaRequest)

	return err
}

type NullableAcceptEulaRequest struct {
	value *AcceptEulaRequest
	isSet bool
}

func (v NullableAcceptEulaRequest) Get() *AcceptEulaRequest {
	return v.value
}

func (v *NullableAcceptEulaRequest) Set(val *AcceptEulaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptEulaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptEulaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptEulaRequest(val *AcceptEulaRequest) *NullableAcceptEulaRequest {
	return &NullableAcceptEulaRequest{value: val, isSet: true}
}

func (v NullableAcceptEulaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptEulaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
