/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StoreProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreProduct{}

// StoreProduct Org-scoped catalog product. Soft-deleted products are retained (`purge_at`) so historical statements and audit stay readable.
type StoreProduct struct {
	CreatedAt         NullableString  `json:"created_at,omitempty"`
	DeletedAt         NullableString  `json:"deleted_at,omitempty"`
	ExternalUrl       NullableString  `json:"external_url,omitempty"`
	Id                NullableString  `json:"id"`
	ImageMediaAssetId NullableString  `json:"image_media_asset_id,omitempty"`
	Name              LocalizedString `json:"name"`
	OrgId             NullableString  `json:"org_id"`
	PurgeAt           NullableString  `json:"purge_at,omitempty"`
	UpdatedAt         NullableString  `json:"updated_at,omitempty"`
}

type _StoreProduct StoreProduct

// NewStoreProduct instantiates a new StoreProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreProduct(id NullableString, name LocalizedString, orgId NullableString) *StoreProduct {
	this := StoreProduct{}
	this.Id = id
	this.Name = name
	this.OrgId = orgId
	return &this
}

// NewStoreProductWithDefaults instantiates a new StoreProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreProductWithDefaults() *StoreProduct {
	this := StoreProduct{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreProduct) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *StoreProduct) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *StoreProduct) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *StoreProduct) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *StoreProduct) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreProduct) GetDeletedAt() string {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *StoreProduct) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableString and assigns it to the DeletedAt field.
func (o *StoreProduct) SetDeletedAt(v string) {
	o.DeletedAt.Set(&v)
}

// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *StoreProduct) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *StoreProduct) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetExternalUrl returns the ExternalUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreProduct) GetExternalUrl() string {
	if o == nil || IsNil(o.ExternalUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalUrl.Get()
}

// GetExternalUrlOk returns a tuple with the ExternalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetExternalUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalUrl.Get(), o.ExternalUrl.IsSet()
}

// HasExternalUrl returns a boolean if a field has been set.
func (o *StoreProduct) HasExternalUrl() bool {
	if o != nil && o.ExternalUrl.IsSet() {
		return true
	}

	return false
}

// SetExternalUrl gets a reference to the given NullableString and assigns it to the ExternalUrl field.
func (o *StoreProduct) SetExternalUrl(v string) {
	o.ExternalUrl.Set(&v)
}

// SetExternalUrlNil sets the value for ExternalUrl to be an explicit nil
func (o *StoreProduct) SetExternalUrlNil() {
	o.ExternalUrl.Set(nil)
}

// UnsetExternalUrl ensures that no value is present for ExternalUrl, not even an explicit nil
func (o *StoreProduct) UnsetExternalUrl() {
	o.ExternalUrl.Unset()
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StoreProduct) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *StoreProduct) SetId(v string) {
	o.Id.Set(&v)
}

// GetImageMediaAssetId returns the ImageMediaAssetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreProduct) GetImageMediaAssetId() string {
	if o == nil || IsNil(o.ImageMediaAssetId.Get()) {
		var ret string
		return ret
	}
	return *o.ImageMediaAssetId.Get()
}

// GetImageMediaAssetIdOk returns a tuple with the ImageMediaAssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetImageMediaAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageMediaAssetId.Get(), o.ImageMediaAssetId.IsSet()
}

// HasImageMediaAssetId returns a boolean if a field has been set.
func (o *StoreProduct) HasImageMediaAssetId() bool {
	if o != nil && o.ImageMediaAssetId.IsSet() {
		return true
	}

	return false
}

// SetImageMediaAssetId gets a reference to the given NullableString and assigns it to the ImageMediaAssetId field.
func (o *StoreProduct) SetImageMediaAssetId(v string) {
	o.ImageMediaAssetId.Set(&v)
}

// SetImageMediaAssetIdNil sets the value for ImageMediaAssetId to be an explicit nil
func (o *StoreProduct) SetImageMediaAssetIdNil() {
	o.ImageMediaAssetId.Set(nil)
}

// UnsetImageMediaAssetId ensures that no value is present for ImageMediaAssetId, not even an explicit nil
func (o *StoreProduct) UnsetImageMediaAssetId() {
	o.ImageMediaAssetId.Unset()
}

// GetName returns the Name field value
func (o *StoreProduct) GetName() LocalizedString {
	if o == nil {
		var ret LocalizedString
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StoreProduct) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StoreProduct) SetName(v LocalizedString) {
	o.Name = v
}

// GetOrgId returns the OrgId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StoreProduct) GetOrgId() string {
	if o == nil || o.OrgId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// SetOrgId sets field value
func (o *StoreProduct) SetOrgId(v string) {
	o.OrgId.Set(&v)
}

// GetPurgeAt returns the PurgeAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreProduct) GetPurgeAt() string {
	if o == nil || IsNil(o.PurgeAt.Get()) {
		var ret string
		return ret
	}
	return *o.PurgeAt.Get()
}

// GetPurgeAtOk returns a tuple with the PurgeAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetPurgeAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurgeAt.Get(), o.PurgeAt.IsSet()
}

// HasPurgeAt returns a boolean if a field has been set.
func (o *StoreProduct) HasPurgeAt() bool {
	if o != nil && o.PurgeAt.IsSet() {
		return true
	}

	return false
}

// SetPurgeAt gets a reference to the given NullableString and assigns it to the PurgeAt field.
func (o *StoreProduct) SetPurgeAt(v string) {
	o.PurgeAt.Set(&v)
}

// SetPurgeAtNil sets the value for PurgeAt to be an explicit nil
func (o *StoreProduct) SetPurgeAtNil() {
	o.PurgeAt.Set(nil)
}

// UnsetPurgeAt ensures that no value is present for PurgeAt, not even an explicit nil
func (o *StoreProduct) UnsetPurgeAt() {
	o.PurgeAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreProduct) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreProduct) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *StoreProduct) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableString and assigns it to the UpdatedAt field.
func (o *StoreProduct) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *StoreProduct) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *StoreProduct) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o StoreProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	if o.ExternalUrl.IsSet() {
		toSerialize["external_url"] = o.ExternalUrl.Get()
	}
	toSerialize["id"] = o.Id.Get()
	if o.ImageMediaAssetId.IsSet() {
		toSerialize["image_media_asset_id"] = o.ImageMediaAssetId.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["org_id"] = o.OrgId.Get()
	if o.PurgeAt.IsSet() {
		toSerialize["purge_at"] = o.PurgeAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

func (o *StoreProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"org_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreProduct := _StoreProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreProduct)

	if err != nil {
		return err
	}

	*o = StoreProduct(varStoreProduct)

	return err
}

type NullableStoreProduct struct {
	value *StoreProduct
	isSet bool
}

func (v NullableStoreProduct) Get() *StoreProduct {
	return v.value
}

func (v *NullableStoreProduct) Set(val *StoreProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreProduct(val *StoreProduct) *NullableStoreProduct {
	return &NullableStoreProduct{value: val, isSet: true}
}

func (v NullableStoreProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
