/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateSkillRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSkillRequest{}

// CreateSkillRequest struct for CreateSkillRequest
type CreateSkillRequest struct {
	AgentId           string       `json:"agent_id"`
	Enabled           NullableBool `json:"enabled,omitempty"`
	Name              string       `json:"name"`
	Steps             []SkillStep  `json:"steps"`
	TriggerEventTypes []string     `json:"trigger_event_types"`
}

type _CreateSkillRequest CreateSkillRequest

// NewCreateSkillRequest instantiates a new CreateSkillRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSkillRequest(agentId string, name string, steps []SkillStep, triggerEventTypes []string) *CreateSkillRequest {
	this := CreateSkillRequest{}
	this.AgentId = agentId
	this.Name = name
	this.Steps = steps
	this.TriggerEventTypes = triggerEventTypes
	return &this
}

// NewCreateSkillRequestWithDefaults instantiates a new CreateSkillRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSkillRequestWithDefaults() *CreateSkillRequest {
	this := CreateSkillRequest{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *CreateSkillRequest) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *CreateSkillRequest) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *CreateSkillRequest) SetAgentId(v string) {
	o.AgentId = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateSkillRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Enabled.Get()
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateSkillRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled.Get(), o.Enabled.IsSet()
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateSkillRequest) HasEnabled() bool {
	if o != nil && o.Enabled.IsSet() {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given NullableBool and assigns it to the Enabled field.
func (o *CreateSkillRequest) SetEnabled(v bool) {
	o.Enabled.Set(&v)
}

// SetEnabledNil sets the value for Enabled to be an explicit nil
func (o *CreateSkillRequest) SetEnabledNil() {
	o.Enabled.Set(nil)
}

// UnsetEnabled ensures that no value is present for Enabled, not even an explicit nil
func (o *CreateSkillRequest) UnsetEnabled() {
	o.Enabled.Unset()
}

// GetName returns the Name field value
func (o *CreateSkillRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSkillRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSkillRequest) SetName(v string) {
	o.Name = v
}

// GetSteps returns the Steps field value
func (o *CreateSkillRequest) GetSteps() []SkillStep {
	if o == nil {
		var ret []SkillStep
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *CreateSkillRequest) GetStepsOk() ([]SkillStep, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *CreateSkillRequest) SetSteps(v []SkillStep) {
	o.Steps = v
}

// GetTriggerEventTypes returns the TriggerEventTypes field value
func (o *CreateSkillRequest) GetTriggerEventTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TriggerEventTypes
}

// GetTriggerEventTypesOk returns a tuple with the TriggerEventTypes field value
// and a boolean to check if the value has been set.
func (o *CreateSkillRequest) GetTriggerEventTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TriggerEventTypes, true
}

// SetTriggerEventTypes sets field value
func (o *CreateSkillRequest) SetTriggerEventTypes(v []string) {
	o.TriggerEventTypes = v
}

func (o CreateSkillRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	if o.Enabled.IsSet() {
		toSerialize["enabled"] = o.Enabled.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["steps"] = o.Steps
	toSerialize["trigger_event_types"] = o.TriggerEventTypes
	return toSerialize, nil
}

func (o *CreateSkillRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_id",
		"name",
		"steps",
		"trigger_event_types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSkillRequest := _CreateSkillRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSkillRequest)

	if err != nil {
		return err
	}

	*o = CreateSkillRequest(varCreateSkillRequest)

	return err
}

type NullableCreateSkillRequest struct {
	value *CreateSkillRequest
	isSet bool
}

func (v NullableCreateSkillRequest) Get() *CreateSkillRequest {
	return v.value
}

func (v *NullableCreateSkillRequest) Set(val *CreateSkillRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSkillRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSkillRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSkillRequest(val *CreateSkillRequest) *NullableCreateSkillRequest {
	return &NullableCreateSkillRequest{value: val, isSet: true}
}

func (v NullableCreateSkillRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSkillRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
