/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StoreMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreMember{}

// StoreMember Store membership. `Pending` awaits admin approval; `Removed` keeps the row (history) but blocks purchasing.
type StoreMember struct {
	// Account purchases are charged to. `None` falls back to the member's personal account.
	BillingAccountId NullableString    `json:"billing_account_id,omitempty"`
	CreatedAt        NullableString    `json:"created_at,omitempty"`
	Id               NullableString    `json:"id"`
	RemovedAt        NullableString    `json:"removed_at,omitempty"`
	Role             StoreMemberRole   `json:"role"`
	Status           StoreMemberStatus `json:"status"`
	StoreId          NullableString    `json:"store_id"`
	UpdatedAt        NullableString    `json:"updated_at,omitempty"`
	UserId           NullableString    `json:"user_id"`
}

type _StoreMember StoreMember

// NewStoreMember instantiates a new StoreMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreMember(id NullableString, role StoreMemberRole, status StoreMemberStatus, storeId NullableString, userId NullableString) *StoreMember {
	this := StoreMember{}
	this.Id = id
	this.Role = role
	this.Status = status
	this.StoreId = storeId
	this.UserId = userId
	return &this
}

// NewStoreMemberWithDefaults instantiates a new StoreMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreMemberWithDefaults() *StoreMember {
	this := StoreMember{}
	return &this
}

// GetBillingAccountId returns the BillingAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreMember) GetBillingAccountId() string {
	if o == nil || IsNil(o.BillingAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.BillingAccountId.Get()
}

// GetBillingAccountIdOk returns a tuple with the BillingAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetBillingAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillingAccountId.Get(), o.BillingAccountId.IsSet()
}

// HasBillingAccountId returns a boolean if a field has been set.
func (o *StoreMember) HasBillingAccountId() bool {
	if o != nil && o.BillingAccountId.IsSet() {
		return true
	}

	return false
}

// SetBillingAccountId gets a reference to the given NullableString and assigns it to the BillingAccountId field.
func (o *StoreMember) SetBillingAccountId(v string) {
	o.BillingAccountId.Set(&v)
}

// SetBillingAccountIdNil sets the value for BillingAccountId to be an explicit nil
func (o *StoreMember) SetBillingAccountIdNil() {
	o.BillingAccountId.Set(nil)
}

// UnsetBillingAccountId ensures that no value is present for BillingAccountId, not even an explicit nil
func (o *StoreMember) UnsetBillingAccountId() {
	o.BillingAccountId.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreMember) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *StoreMember) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *StoreMember) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *StoreMember) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *StoreMember) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StoreMember) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *StoreMember) SetId(v string) {
	o.Id.Set(&v)
}

// GetRemovedAt returns the RemovedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreMember) GetRemovedAt() string {
	if o == nil || IsNil(o.RemovedAt.Get()) {
		var ret string
		return ret
	}
	return *o.RemovedAt.Get()
}

// GetRemovedAtOk returns a tuple with the RemovedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetRemovedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemovedAt.Get(), o.RemovedAt.IsSet()
}

// HasRemovedAt returns a boolean if a field has been set.
func (o *StoreMember) HasRemovedAt() bool {
	if o != nil && o.RemovedAt.IsSet() {
		return true
	}

	return false
}

// SetRemovedAt gets a reference to the given NullableString and assigns it to the RemovedAt field.
func (o *StoreMember) SetRemovedAt(v string) {
	o.RemovedAt.Set(&v)
}

// SetRemovedAtNil sets the value for RemovedAt to be an explicit nil
func (o *StoreMember) SetRemovedAtNil() {
	o.RemovedAt.Set(nil)
}

// UnsetRemovedAt ensures that no value is present for RemovedAt, not even an explicit nil
func (o *StoreMember) UnsetRemovedAt() {
	o.RemovedAt.Unset()
}

// GetRole returns the Role field value
func (o *StoreMember) GetRole() StoreMemberRole {
	if o == nil {
		var ret StoreMemberRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *StoreMember) GetRoleOk() (*StoreMemberRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *StoreMember) SetRole(v StoreMemberRole) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *StoreMember) GetStatus() StoreMemberStatus {
	if o == nil {
		var ret StoreMemberStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StoreMember) GetStatusOk() (*StoreMemberStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StoreMember) SetStatus(v StoreMemberStatus) {
	o.Status = v
}

// GetStoreId returns the StoreId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StoreMember) GetStoreId() string {
	if o == nil || o.StoreId.Get() == nil {
		var ret string
		return ret
	}

	return *o.StoreId.Get()
}

// GetStoreIdOk returns a tuple with the StoreId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetStoreIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StoreId.Get(), o.StoreId.IsSet()
}

// SetStoreId sets field value
func (o *StoreMember) SetStoreId(v string) {
	o.StoreId.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoreMember) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *StoreMember) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableString and assigns it to the UpdatedAt field.
func (o *StoreMember) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *StoreMember) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *StoreMember) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetUserId returns the UserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StoreMember) GetUserId() string {
	if o == nil || o.UserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreMember) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// SetUserId sets field value
func (o *StoreMember) SetUserId(v string) {
	o.UserId.Set(&v)
}

func (o StoreMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BillingAccountId.IsSet() {
		toSerialize["billing_account_id"] = o.BillingAccountId.Get()
	}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	toSerialize["id"] = o.Id.Get()
	if o.RemovedAt.IsSet() {
		toSerialize["removed_at"] = o.RemovedAt.Get()
	}
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	toSerialize["store_id"] = o.StoreId.Get()
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	toSerialize["user_id"] = o.UserId.Get()
	return toSerialize, nil
}

func (o *StoreMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"role",
		"status",
		"store_id",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreMember := _StoreMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreMember)

	if err != nil {
		return err
	}

	*o = StoreMember(varStoreMember)

	return err
}

type NullableStoreMember struct {
	value *StoreMember
	isSet bool
}

func (v NullableStoreMember) Get() *StoreMember {
	return v.value
}

func (v *NullableStoreMember) Set(val *StoreMember) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreMember) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreMember(val *StoreMember) *NullableStoreMember {
	return &NullableStoreMember{value: val, isSet: true}
}

func (v NullableStoreMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
