/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProhibitMasterDoorInvitesPolicyConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProhibitMasterDoorInvitesPolicyConfig{}

// ProhibitMasterDoorInvitesPolicyConfig Typed `config` shape for `prohibit_master_door_invites`.
type ProhibitMasterDoorInvitesPolicyConfig struct {
	AppliesTo     []PolicyPrincipalKind                                 `json:"applies_to,omitempty"`
	MasterDoorIds []string                                              `json:"master_door_ids"`
	Output        NullableInvitationAllowedEntryKindsPolicyConfigOutput `json:"output,omitempty"`
}

type _ProhibitMasterDoorInvitesPolicyConfig ProhibitMasterDoorInvitesPolicyConfig

// NewProhibitMasterDoorInvitesPolicyConfig instantiates a new ProhibitMasterDoorInvitesPolicyConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProhibitMasterDoorInvitesPolicyConfig(masterDoorIds []string) *ProhibitMasterDoorInvitesPolicyConfig {
	this := ProhibitMasterDoorInvitesPolicyConfig{}
	this.MasterDoorIds = masterDoorIds
	return &this
}

// NewProhibitMasterDoorInvitesPolicyConfigWithDefaults instantiates a new ProhibitMasterDoorInvitesPolicyConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProhibitMasterDoorInvitesPolicyConfigWithDefaults() *ProhibitMasterDoorInvitesPolicyConfig {
	this := ProhibitMasterDoorInvitesPolicyConfig{}
	return &this
}

// GetAppliesTo returns the AppliesTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProhibitMasterDoorInvitesPolicyConfig) GetAppliesTo() []PolicyPrincipalKind {
	if o == nil {
		var ret []PolicyPrincipalKind
		return ret
	}
	return o.AppliesTo
}

// GetAppliesToOk returns a tuple with the AppliesTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProhibitMasterDoorInvitesPolicyConfig) GetAppliesToOk() ([]PolicyPrincipalKind, bool) {
	if o == nil || IsNil(o.AppliesTo) {
		return nil, false
	}
	return o.AppliesTo, true
}

// HasAppliesTo returns a boolean if a field has been set.
func (o *ProhibitMasterDoorInvitesPolicyConfig) HasAppliesTo() bool {
	if o != nil && !IsNil(o.AppliesTo) {
		return true
	}

	return false
}

// SetAppliesTo gets a reference to the given []PolicyPrincipalKind and assigns it to the AppliesTo field.
func (o *ProhibitMasterDoorInvitesPolicyConfig) SetAppliesTo(v []PolicyPrincipalKind) {
	o.AppliesTo = v
}

// GetMasterDoorIds returns the MasterDoorIds field value
func (o *ProhibitMasterDoorInvitesPolicyConfig) GetMasterDoorIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MasterDoorIds
}

// GetMasterDoorIdsOk returns a tuple with the MasterDoorIds field value
// and a boolean to check if the value has been set.
func (o *ProhibitMasterDoorInvitesPolicyConfig) GetMasterDoorIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MasterDoorIds, true
}

// SetMasterDoorIds sets field value
func (o *ProhibitMasterDoorInvitesPolicyConfig) SetMasterDoorIds(v []string) {
	o.MasterDoorIds = v
}

// GetOutput returns the Output field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProhibitMasterDoorInvitesPolicyConfig) GetOutput() InvitationAllowedEntryKindsPolicyConfigOutput {
	if o == nil || IsNil(o.Output.Get()) {
		var ret InvitationAllowedEntryKindsPolicyConfigOutput
		return ret
	}
	return *o.Output.Get()
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProhibitMasterDoorInvitesPolicyConfig) GetOutputOk() (*InvitationAllowedEntryKindsPolicyConfigOutput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Output.Get(), o.Output.IsSet()
}

// HasOutput returns a boolean if a field has been set.
func (o *ProhibitMasterDoorInvitesPolicyConfig) HasOutput() bool {
	if o != nil && o.Output.IsSet() {
		return true
	}

	return false
}

// SetOutput gets a reference to the given NullableInvitationAllowedEntryKindsPolicyConfigOutput and assigns it to the Output field.
func (o *ProhibitMasterDoorInvitesPolicyConfig) SetOutput(v InvitationAllowedEntryKindsPolicyConfigOutput) {
	o.Output.Set(&v)
}

// SetOutputNil sets the value for Output to be an explicit nil
func (o *ProhibitMasterDoorInvitesPolicyConfig) SetOutputNil() {
	o.Output.Set(nil)
}

// UnsetOutput ensures that no value is present for Output, not even an explicit nil
func (o *ProhibitMasterDoorInvitesPolicyConfig) UnsetOutput() {
	o.Output.Unset()
}

func (o ProhibitMasterDoorInvitesPolicyConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AppliesTo != nil {
		toSerialize["applies_to"] = o.AppliesTo
	}
	toSerialize["master_door_ids"] = o.MasterDoorIds
	if o.Output.IsSet() {
		toSerialize["output"] = o.Output.Get()
	}
	return toSerialize, nil
}

func (o *ProhibitMasterDoorInvitesPolicyConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"master_door_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProhibitMasterDoorInvitesPolicyConfig := _ProhibitMasterDoorInvitesPolicyConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProhibitMasterDoorInvitesPolicyConfig)

	if err != nil {
		return err
	}

	*o = ProhibitMasterDoorInvitesPolicyConfig(varProhibitMasterDoorInvitesPolicyConfig)

	return err
}

type NullableProhibitMasterDoorInvitesPolicyConfig struct {
	value *ProhibitMasterDoorInvitesPolicyConfig
	isSet bool
}

func (v NullableProhibitMasterDoorInvitesPolicyConfig) Get() *ProhibitMasterDoorInvitesPolicyConfig {
	return v.value
}

func (v *NullableProhibitMasterDoorInvitesPolicyConfig) Set(val *ProhibitMasterDoorInvitesPolicyConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableProhibitMasterDoorInvitesPolicyConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableProhibitMasterDoorInvitesPolicyConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProhibitMasterDoorInvitesPolicyConfig(val *ProhibitMasterDoorInvitesPolicyConfig) *NullableProhibitMasterDoorInvitesPolicyConfig {
	return &NullableProhibitMasterDoorInvitesPolicyConfig{value: val, isSet: true}
}

func (v NullableProhibitMasterDoorInvitesPolicyConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProhibitMasterDoorInvitesPolicyConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
