/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseAccessPortalListItemItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseAccessPortalListItemItemsInner{}

// PaginatedResponseAccessPortalListItemItemsInner struct for PaginatedResponseAccessPortalListItemItemsInner
type PaginatedResponseAccessPortalListItemItemsInner struct {
	CreatedAt NullableString `json:"created_at,omitempty"`
	// When set, the portal is soft-deleted (kept for restore).
	DeletedAt NullableString `json:"deleted_at,omitempty"`
	// Door device id (virtual_access_portal in this integration). Canonical portal link key.
	DeviceId NullableString `json:"device_id,omitempty"`
	// Directory device id (virtual_access_directory in this integration).
	DirectoryId NullableString  `json:"directory_id,omitempty"`
	Id          string          `json:"id"`
	Name        LocalizedString `json:"name"`
	PublicId    string          `json:"public_id"`
	UpdatedAt   NullableString  `json:"updated_at,omitempty"`
}

type _PaginatedResponseAccessPortalListItemItemsInner PaginatedResponseAccessPortalListItemItemsInner

// NewPaginatedResponseAccessPortalListItemItemsInner instantiates a new PaginatedResponseAccessPortalListItemItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseAccessPortalListItemItemsInner(id string, name LocalizedString, publicId string) *PaginatedResponseAccessPortalListItemItemsInner {
	this := PaginatedResponseAccessPortalListItemItemsInner{}
	this.Id = id
	this.Name = name
	this.PublicId = publicId
	return &this
}

// NewPaginatedResponseAccessPortalListItemItemsInnerWithDefaults instantiates a new PaginatedResponseAccessPortalListItemItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseAccessPortalListItemItemsInnerWithDefaults() *PaginatedResponseAccessPortalListItemItemsInner {
	this := PaginatedResponseAccessPortalListItemItemsInner{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetDeletedAt() string {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetDeletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableString and assigns it to the DeletedAt field.
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetDeletedAt(v string) {
	o.DeletedAt.Set(&v)
}

// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceId.Get()
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceId.Get(), o.DeviceId.IsSet()
}

// HasDeviceId returns a boolean if a field has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) HasDeviceId() bool {
	if o != nil && o.DeviceId.IsSet() {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given NullableString and assigns it to the DeviceId field.
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetDeviceId(v string) {
	o.DeviceId.Set(&v)
}

// SetDeviceIdNil sets the value for DeviceId to be an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetDeviceIdNil() {
	o.DeviceId.Set(nil)
}

// UnsetDeviceId ensures that no value is present for DeviceId, not even an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) UnsetDeviceId() {
	o.DeviceId.Unset()
}

// GetDirectoryId returns the DirectoryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetDirectoryId() string {
	if o == nil || IsNil(o.DirectoryId.Get()) {
		var ret string
		return ret
	}
	return *o.DirectoryId.Get()
}

// GetDirectoryIdOk returns a tuple with the DirectoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetDirectoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DirectoryId.Get(), o.DirectoryId.IsSet()
}

// HasDirectoryId returns a boolean if a field has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) HasDirectoryId() bool {
	if o != nil && o.DirectoryId.IsSet() {
		return true
	}

	return false
}

// SetDirectoryId gets a reference to the given NullableString and assigns it to the DirectoryId field.
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetDirectoryId(v string) {
	o.DirectoryId.Set(&v)
}

// SetDirectoryIdNil sets the value for DirectoryId to be an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetDirectoryIdNil() {
	o.DirectoryId.Set(nil)
}

// UnsetDirectoryId ensures that no value is present for DirectoryId, not even an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) UnsetDirectoryId() {
	o.DirectoryId.Unset()
}

// GetId returns the Id field value
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetName() LocalizedString {
	if o == nil {
		var ret LocalizedString
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetName(v LocalizedString) {
	o.Name = v
}

// GetPublicId returns the PublicId field value
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetPublicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetPublicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicId, true
}

// SetPublicId sets field value
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetPublicId(v string) {
	o.PublicId = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseAccessPortalListItemItemsInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PaginatedResponseAccessPortalListItemItemsInner) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableString and assigns it to the UpdatedAt field.
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *PaginatedResponseAccessPortalListItemItemsInner) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o PaginatedResponseAccessPortalListItemItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	if o.DeviceId.IsSet() {
		toSerialize["device_id"] = o.DeviceId.Get()
	}
	if o.DirectoryId.IsSet() {
		toSerialize["directory_id"] = o.DirectoryId.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["public_id"] = o.PublicId
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

func (o *PaginatedResponseAccessPortalListItemItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"public_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseAccessPortalListItemItemsInner := _PaginatedResponseAccessPortalListItemItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedResponseAccessPortalListItemItemsInner)

	if err != nil {
		return err
	}

	*o = PaginatedResponseAccessPortalListItemItemsInner(varPaginatedResponseAccessPortalListItemItemsInner)

	return err
}

type NullablePaginatedResponseAccessPortalListItemItemsInner struct {
	value *PaginatedResponseAccessPortalListItemItemsInner
	isSet bool
}

func (v NullablePaginatedResponseAccessPortalListItemItemsInner) Get() *PaginatedResponseAccessPortalListItemItemsInner {
	return v.value
}

func (v *NullablePaginatedResponseAccessPortalListItemItemsInner) Set(val *PaginatedResponseAccessPortalListItemItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseAccessPortalListItemItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseAccessPortalListItemItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseAccessPortalListItemItemsInner(val *PaginatedResponseAccessPortalListItemItemsInner) *NullablePaginatedResponseAccessPortalListItemItemsInner {
	return &NullablePaginatedResponseAccessPortalListItemItemsInner{value: val, isSet: true}
}

func (v NullablePaginatedResponseAccessPortalListItemItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseAccessPortalListItemItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
