/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateAgentCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentCredentialRequest{}

// CreateAgentCredentialRequest struct for CreateAgentCredentialRequest
type CreateAgentCredentialRequest struct {
	ExpiresAt NullableString `json:"expires_at,omitempty"`
	ExpiresIn NullableString `json:"expires_in,omitempty"`
	Name      NullableString `json:"name,omitempty"`
}

// NewCreateAgentCredentialRequest instantiates a new CreateAgentCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentCredentialRequest() *CreateAgentCredentialRequest {
	this := CreateAgentCredentialRequest{}
	return &this
}

// NewCreateAgentCredentialRequestWithDefaults instantiates a new CreateAgentCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentCredentialRequestWithDefaults() *CreateAgentCredentialRequest {
	this := CreateAgentCredentialRequest{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentCredentialRequest) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentCredentialRequest) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CreateAgentCredentialRequest) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableString and assigns it to the ExpiresAt field.
func (o *CreateAgentCredentialRequest) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *CreateAgentCredentialRequest) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *CreateAgentCredentialRequest) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentCredentialRequest) GetExpiresIn() string {
	if o == nil || IsNil(o.ExpiresIn.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresIn.Get()
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentCredentialRequest) GetExpiresInOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresIn.Get(), o.ExpiresIn.IsSet()
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *CreateAgentCredentialRequest) HasExpiresIn() bool {
	if o != nil && o.ExpiresIn.IsSet() {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given NullableString and assigns it to the ExpiresIn field.
func (o *CreateAgentCredentialRequest) SetExpiresIn(v string) {
	o.ExpiresIn.Set(&v)
}

// SetExpiresInNil sets the value for ExpiresIn to be an explicit nil
func (o *CreateAgentCredentialRequest) SetExpiresInNil() {
	o.ExpiresIn.Set(nil)
}

// UnsetExpiresIn ensures that no value is present for ExpiresIn, not even an explicit nil
func (o *CreateAgentCredentialRequest) UnsetExpiresIn() {
	o.ExpiresIn.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentCredentialRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CreateAgentCredentialRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CreateAgentCredentialRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *CreateAgentCredentialRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CreateAgentCredentialRequest) UnsetName() {
	o.Name.Unset()
}

func (o CreateAgentCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if o.ExpiresIn.IsSet() {
		toSerialize["expires_in"] = o.ExpiresIn.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableCreateAgentCredentialRequest struct {
	value *CreateAgentCredentialRequest
	isSet bool
}

func (v NullableCreateAgentCredentialRequest) Get() *CreateAgentCredentialRequest {
	return v.value
}

func (v *NullableCreateAgentCredentialRequest) Set(val *CreateAgentCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentCredentialRequest(val *CreateAgentCredentialRequest) *NullableCreateAgentCredentialRequest {
	return &NullableCreateAgentCredentialRequest{value: val, isSet: true}
}

func (v NullableCreateAgentCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
