/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StartPhoneVerificationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartPhoneVerificationRequest{}

// StartPhoneVerificationRequest struct for StartPhoneVerificationRequest
type StartPhoneVerificationRequest struct {
	// Phone number in E.164 (`+[country][digits]`).
	Phone string `json:"phone"`
}

type _StartPhoneVerificationRequest StartPhoneVerificationRequest

// NewStartPhoneVerificationRequest instantiates a new StartPhoneVerificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartPhoneVerificationRequest(phone string) *StartPhoneVerificationRequest {
	this := StartPhoneVerificationRequest{}
	this.Phone = phone
	return &this
}

// NewStartPhoneVerificationRequestWithDefaults instantiates a new StartPhoneVerificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartPhoneVerificationRequestWithDefaults() *StartPhoneVerificationRequest {
	this := StartPhoneVerificationRequest{}
	return &this
}

// GetPhone returns the Phone field value
func (o *StartPhoneVerificationRequest) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *StartPhoneVerificationRequest) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *StartPhoneVerificationRequest) SetPhone(v string) {
	o.Phone = v
}

func (o StartPhoneVerificationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *StartPhoneVerificationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStartPhoneVerificationRequest := _StartPhoneVerificationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStartPhoneVerificationRequest)

	if err != nil {
		return err
	}

	*o = StartPhoneVerificationRequest(varStartPhoneVerificationRequest)

	return err
}

type NullableStartPhoneVerificationRequest struct {
	value *StartPhoneVerificationRequest
	isSet bool
}

func (v NullableStartPhoneVerificationRequest) Get() *StartPhoneVerificationRequest {
	return v.value
}

func (v *NullableStartPhoneVerificationRequest) Set(val *StartPhoneVerificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartPhoneVerificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartPhoneVerificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartPhoneVerificationRequest(val *StartPhoneVerificationRequest) *NullableStartPhoneVerificationRequest {
	return &NullableStartPhoneVerificationRequest{value: val, isSet: true}
}

func (v NullableStartPhoneVerificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartPhoneVerificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
