/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaginationQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationQuery{}

// PaginationQuery Pagination query parameters. Flatten into list-endpoint query structs. When not provided, defaults to first page (limit from config, offset=0).
type PaginationQuery struct {
	// Number of items per page. Default from config, max 200.
	Limit *int32 `json:"limit,omitempty"`
	// Number of items to skip. Default 0.
	Offset *int32 `json:"offset,omitempty"`
}

// NewPaginationQuery instantiates a new PaginationQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationQuery() *PaginationQuery {
	this := PaginationQuery{}
	return &this
}

// NewPaginationQueryWithDefaults instantiates a new PaginationQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationQueryWithDefaults() *PaginationQuery {
	this := PaginationQuery{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PaginationQuery) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationQuery) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PaginationQuery) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PaginationQuery) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *PaginationQuery) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationQuery) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *PaginationQuery) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *PaginationQuery) SetOffset(v int32) {
	o.Offset = &v
}

func (o PaginationQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullablePaginationQuery struct {
	value *PaginationQuery
	isSet bool
}

func (v NullablePaginationQuery) Get() *PaginationQuery {
	return v.value
}

func (v *NullablePaginationQuery) Set(val *PaginationQuery) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationQuery) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationQuery(val *PaginationQuery) *NullablePaginationQuery {
	return &NullablePaginationQuery{value: val, isSet: true}
}

func (v NullablePaginationQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
