/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MeApartmentAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeApartmentAsset{}

// MeApartmentAsset struct for MeApartmentAsset
type MeApartmentAsset struct {
	ApartmentLabel  interface{}   `json:"apartment_label,omitempty"`
	ApartmentNumber NullableInt64 `json:"apartment_number,omitempty"`
	BuildingName    interface{}   `json:"building_name,omitempty"`
	// True when this user would be a callee for intercom calls (policy + role + receives_calls).
	CallEligible bool        `json:"call_eligible"`
	DisplayName  interface{} `json:"display_name,omitempty"`
	// True when calls are silenced for this apartment (global DND or per-apartment DND).
	DndEnabled    NullableBool  `json:"dnd_enabled,omitempty"`
	EntityId      string        `json:"entity_id"`
	Floor         interface{}   `json:"floor,omitempty"`
	FloorNumber   NullableInt64 `json:"floor_number,omitempty"`
	IntegrationId string        `json:"integration_id"`
	OrgId         string        `json:"org_id"`
	ReceivesCalls bool          `json:"receives_calls"`
	Role          string        `json:"role"`
}

type _MeApartmentAsset MeApartmentAsset

// NewMeApartmentAsset instantiates a new MeApartmentAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeApartmentAsset(callEligible bool, entityId string, integrationId string, orgId string, receivesCalls bool, role string) *MeApartmentAsset {
	this := MeApartmentAsset{}
	this.CallEligible = callEligible
	this.EntityId = entityId
	this.IntegrationId = integrationId
	this.OrgId = orgId
	this.ReceivesCalls = receivesCalls
	this.Role = role
	return &this
}

// NewMeApartmentAssetWithDefaults instantiates a new MeApartmentAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeApartmentAssetWithDefaults() *MeApartmentAsset {
	this := MeApartmentAsset{}
	return &this
}

// GetApartmentLabel returns the ApartmentLabel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetApartmentLabel() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ApartmentLabel
}

// GetApartmentLabelOk returns a tuple with the ApartmentLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetApartmentLabelOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ApartmentLabel) {
		return nil, false
	}
	return &o.ApartmentLabel, true
}

// HasApartmentLabel returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasApartmentLabel() bool {
	if o != nil && !IsNil(o.ApartmentLabel) {
		return true
	}

	return false
}

// SetApartmentLabel gets a reference to the given interface{} and assigns it to the ApartmentLabel field.
func (o *MeApartmentAsset) SetApartmentLabel(v interface{}) {
	o.ApartmentLabel = v
}

// GetApartmentNumber returns the ApartmentNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetApartmentNumber() int64 {
	if o == nil || IsNil(o.ApartmentNumber.Get()) {
		var ret int64
		return ret
	}
	return *o.ApartmentNumber.Get()
}

// GetApartmentNumberOk returns a tuple with the ApartmentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetApartmentNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApartmentNumber.Get(), o.ApartmentNumber.IsSet()
}

// HasApartmentNumber returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasApartmentNumber() bool {
	if o != nil && o.ApartmentNumber.IsSet() {
		return true
	}

	return false
}

// SetApartmentNumber gets a reference to the given NullableInt64 and assigns it to the ApartmentNumber field.
func (o *MeApartmentAsset) SetApartmentNumber(v int64) {
	o.ApartmentNumber.Set(&v)
}

// SetApartmentNumberNil sets the value for ApartmentNumber to be an explicit nil
func (o *MeApartmentAsset) SetApartmentNumberNil() {
	o.ApartmentNumber.Set(nil)
}

// UnsetApartmentNumber ensures that no value is present for ApartmentNumber, not even an explicit nil
func (o *MeApartmentAsset) UnsetApartmentNumber() {
	o.ApartmentNumber.Unset()
}

// GetBuildingName returns the BuildingName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetBuildingName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.BuildingName
}

// GetBuildingNameOk returns a tuple with the BuildingName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetBuildingNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.BuildingName) {
		return nil, false
	}
	return &o.BuildingName, true
}

// HasBuildingName returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasBuildingName() bool {
	if o != nil && !IsNil(o.BuildingName) {
		return true
	}

	return false
}

// SetBuildingName gets a reference to the given interface{} and assigns it to the BuildingName field.
func (o *MeApartmentAsset) SetBuildingName(v interface{}) {
	o.BuildingName = v
}

// GetCallEligible returns the CallEligible field value
func (o *MeApartmentAsset) GetCallEligible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CallEligible
}

// GetCallEligibleOk returns a tuple with the CallEligible field value
// and a boolean to check if the value has been set.
func (o *MeApartmentAsset) GetCallEligibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallEligible, true
}

// SetCallEligible sets field value
func (o *MeApartmentAsset) SetCallEligible(v bool) {
	o.CallEligible = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetDisplayName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetDisplayNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return &o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given interface{} and assigns it to the DisplayName field.
func (o *MeApartmentAsset) SetDisplayName(v interface{}) {
	o.DisplayName = v
}

// GetDndEnabled returns the DndEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetDndEnabled() bool {
	if o == nil || IsNil(o.DndEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.DndEnabled.Get()
}

// GetDndEnabledOk returns a tuple with the DndEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetDndEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DndEnabled.Get(), o.DndEnabled.IsSet()
}

// HasDndEnabled returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasDndEnabled() bool {
	if o != nil && o.DndEnabled.IsSet() {
		return true
	}

	return false
}

// SetDndEnabled gets a reference to the given NullableBool and assigns it to the DndEnabled field.
func (o *MeApartmentAsset) SetDndEnabled(v bool) {
	o.DndEnabled.Set(&v)
}

// SetDndEnabledNil sets the value for DndEnabled to be an explicit nil
func (o *MeApartmentAsset) SetDndEnabledNil() {
	o.DndEnabled.Set(nil)
}

// UnsetDndEnabled ensures that no value is present for DndEnabled, not even an explicit nil
func (o *MeApartmentAsset) UnsetDndEnabled() {
	o.DndEnabled.Unset()
}

// GetEntityId returns the EntityId field value
func (o *MeApartmentAsset) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *MeApartmentAsset) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *MeApartmentAsset) SetEntityId(v string) {
	o.EntityId = v
}

// GetFloor returns the Floor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetFloor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Floor
}

// GetFloorOk returns a tuple with the Floor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetFloorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Floor) {
		return nil, false
	}
	return &o.Floor, true
}

// HasFloor returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasFloor() bool {
	if o != nil && !IsNil(o.Floor) {
		return true
	}

	return false
}

// SetFloor gets a reference to the given interface{} and assigns it to the Floor field.
func (o *MeApartmentAsset) SetFloor(v interface{}) {
	o.Floor = v
}

// GetFloorNumber returns the FloorNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeApartmentAsset) GetFloorNumber() int64 {
	if o == nil || IsNil(o.FloorNumber.Get()) {
		var ret int64
		return ret
	}
	return *o.FloorNumber.Get()
}

// GetFloorNumberOk returns a tuple with the FloorNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeApartmentAsset) GetFloorNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FloorNumber.Get(), o.FloorNumber.IsSet()
}

// HasFloorNumber returns a boolean if a field has been set.
func (o *MeApartmentAsset) HasFloorNumber() bool {
	if o != nil && o.FloorNumber.IsSet() {
		return true
	}

	return false
}

// SetFloorNumber gets a reference to the given NullableInt64 and assigns it to the FloorNumber field.
func (o *MeApartmentAsset) SetFloorNumber(v int64) {
	o.FloorNumber.Set(&v)
}

// SetFloorNumberNil sets the value for FloorNumber to be an explicit nil
func (o *MeApartmentAsset) SetFloorNumberNil() {
	o.FloorNumber.Set(nil)
}

// UnsetFloorNumber ensures that no value is present for FloorNumber, not even an explicit nil
func (o *MeApartmentAsset) UnsetFloorNumber() {
	o.FloorNumber.Unset()
}

// GetIntegrationId returns the IntegrationId field value
func (o *MeApartmentAsset) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *MeApartmentAsset) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *MeApartmentAsset) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetOrgId returns the OrgId field value
func (o *MeApartmentAsset) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *MeApartmentAsset) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *MeApartmentAsset) SetOrgId(v string) {
	o.OrgId = v
}

// GetReceivesCalls returns the ReceivesCalls field value
func (o *MeApartmentAsset) GetReceivesCalls() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReceivesCalls
}

// GetReceivesCallsOk returns a tuple with the ReceivesCalls field value
// and a boolean to check if the value has been set.
func (o *MeApartmentAsset) GetReceivesCallsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivesCalls, true
}

// SetReceivesCalls sets field value
func (o *MeApartmentAsset) SetReceivesCalls(v bool) {
	o.ReceivesCalls = v
}

// GetRole returns the Role field value
func (o *MeApartmentAsset) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MeApartmentAsset) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MeApartmentAsset) SetRole(v string) {
	o.Role = v
}

func (o MeApartmentAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApartmentLabel != nil {
		toSerialize["apartment_label"] = o.ApartmentLabel
	}
	if o.ApartmentNumber.IsSet() {
		toSerialize["apartment_number"] = o.ApartmentNumber.Get()
	}
	if o.BuildingName != nil {
		toSerialize["building_name"] = o.BuildingName
	}
	toSerialize["call_eligible"] = o.CallEligible
	if o.DisplayName != nil {
		toSerialize["display_name"] = o.DisplayName
	}
	if o.DndEnabled.IsSet() {
		toSerialize["dnd_enabled"] = o.DndEnabled.Get()
	}
	toSerialize["entity_id"] = o.EntityId
	if o.Floor != nil {
		toSerialize["floor"] = o.Floor
	}
	if o.FloorNumber.IsSet() {
		toSerialize["floor_number"] = o.FloorNumber.Get()
	}
	toSerialize["integration_id"] = o.IntegrationId
	toSerialize["org_id"] = o.OrgId
	toSerialize["receives_calls"] = o.ReceivesCalls
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *MeApartmentAsset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"call_eligible",
		"entity_id",
		"integration_id",
		"org_id",
		"receives_calls",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeApartmentAsset := _MeApartmentAsset{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeApartmentAsset)

	if err != nil {
		return err
	}

	*o = MeApartmentAsset(varMeApartmentAsset)

	return err
}

type NullableMeApartmentAsset struct {
	value *MeApartmentAsset
	isSet bool
}

func (v NullableMeApartmentAsset) Get() *MeApartmentAsset {
	return v.value
}

func (v *NullableMeApartmentAsset) Set(val *MeApartmentAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableMeApartmentAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableMeApartmentAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeApartmentAsset(val *MeApartmentAsset) *NullableMeApartmentAsset {
	return &NullableMeApartmentAsset{value: val, isSet: true}
}

func (v NullableMeApartmentAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeApartmentAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
