/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SiteAccessDeviceRole Which door-side list put a device in a section.
type SiteAccessDeviceRole string

// List of SiteAccessDeviceRole
const (
	SITEACCESSDEVICEROLE_OPENER SiteAccessDeviceRole = "opener"
	SITEACCESSDEVICEROLE_LIGHT  SiteAccessDeviceRole = "light"
	SITEACCESSDEVICEROLE_CAMERA SiteAccessDeviceRole = "camera"
)

// All allowed values of SiteAccessDeviceRole enum
var AllowedSiteAccessDeviceRoleEnumValues = []SiteAccessDeviceRole{
	"opener",
	"light",
	"camera",
}

func (v *SiteAccessDeviceRole) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SiteAccessDeviceRole(value)
	for _, existing := range AllowedSiteAccessDeviceRoleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SiteAccessDeviceRole", value)
}

// NewSiteAccessDeviceRoleFromValue returns a pointer to a valid SiteAccessDeviceRole
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSiteAccessDeviceRoleFromValue(v string) (*SiteAccessDeviceRole, error) {
	ev := SiteAccessDeviceRole(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SiteAccessDeviceRole: valid values are %v", v, AllowedSiteAccessDeviceRoleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SiteAccessDeviceRole) IsValid() bool {
	for _, existing := range AllowedSiteAccessDeviceRoleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SiteAccessDeviceRole value
func (v SiteAccessDeviceRole) Ptr() *SiteAccessDeviceRole {
	return &v
}

type NullableSiteAccessDeviceRole struct {
	value *SiteAccessDeviceRole
	isSet bool
}

func (v NullableSiteAccessDeviceRole) Get() *SiteAccessDeviceRole {
	return v.value
}

func (v *NullableSiteAccessDeviceRole) Set(val *SiteAccessDeviceRole) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteAccessDeviceRole) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteAccessDeviceRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteAccessDeviceRole(val *SiteAccessDeviceRole) *NullableSiteAccessDeviceRole {
	return &NullableSiteAccessDeviceRole{value: val, isSet: true}
}

func (v NullableSiteAccessDeviceRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteAccessDeviceRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
