/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResponseStoreProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseStoreProduct{}

// PaginatedResponseStoreProduct Paginated response body for list endpoints.
type PaginatedResponseStoreProduct struct {
	Items []PaginatedResponseStoreProductItemsInner `json:"items"`
	Total int64                                     `json:"total"`
}

type _PaginatedResponseStoreProduct PaginatedResponseStoreProduct

// NewPaginatedResponseStoreProduct instantiates a new PaginatedResponseStoreProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseStoreProduct(items []PaginatedResponseStoreProductItemsInner, total int64) *PaginatedResponseStoreProduct {
	this := PaginatedResponseStoreProduct{}
	this.Items = items
	this.Total = total
	return &this
}

// NewPaginatedResponseStoreProductWithDefaults instantiates a new PaginatedResponseStoreProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseStoreProductWithDefaults() *PaginatedResponseStoreProduct {
	this := PaginatedResponseStoreProduct{}
	return &this
}

// GetItems returns the Items field value
func (o *PaginatedResponseStoreProduct) GetItems() []PaginatedResponseStoreProductItemsInner {
	if o == nil {
		var ret []PaginatedResponseStoreProductItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseStoreProduct) GetItemsOk() ([]PaginatedResponseStoreProductItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginatedResponseStoreProduct) SetItems(v []PaginatedResponseStoreProductItemsInner) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *PaginatedResponseStoreProduct) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseStoreProduct) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PaginatedResponseStoreProduct) SetTotal(v int64) {
	o.Total = v
}

func (o PaginatedResponseStoreProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *PaginatedResponseStoreProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseStoreProduct := _PaginatedResponseStoreProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedResponseStoreProduct)

	if err != nil {
		return err
	}

	*o = PaginatedResponseStoreProduct(varPaginatedResponseStoreProduct)

	return err
}

type NullablePaginatedResponseStoreProduct struct {
	value *PaginatedResponseStoreProduct
	isSet bool
}

func (v NullablePaginatedResponseStoreProduct) Get() *PaginatedResponseStoreProduct {
	return v.value
}

func (v *NullablePaginatedResponseStoreProduct) Set(val *PaginatedResponseStoreProduct) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseStoreProduct) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseStoreProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseStoreProduct(val *PaginatedResponseStoreProduct) *NullablePaginatedResponseStoreProduct {
	return &NullablePaginatedResponseStoreProduct{value: val, isSet: true}
}

func (v NullablePaginatedResponseStoreProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseStoreProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
