/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetDoorRestrictionsPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDoorRestrictionsPayload{}

// SetDoorRestrictionsPayload struct for SetDoorRestrictionsPayload
type SetDoorRestrictionsPayload struct {
	ApartmentEntityIds []string `json:"apartment_entity_ids"`
}

type _SetDoorRestrictionsPayload SetDoorRestrictionsPayload

// NewSetDoorRestrictionsPayload instantiates a new SetDoorRestrictionsPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDoorRestrictionsPayload(apartmentEntityIds []string) *SetDoorRestrictionsPayload {
	this := SetDoorRestrictionsPayload{}
	this.ApartmentEntityIds = apartmentEntityIds
	return &this
}

// NewSetDoorRestrictionsPayloadWithDefaults instantiates a new SetDoorRestrictionsPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDoorRestrictionsPayloadWithDefaults() *SetDoorRestrictionsPayload {
	this := SetDoorRestrictionsPayload{}
	return &this
}

// GetApartmentEntityIds returns the ApartmentEntityIds field value
func (o *SetDoorRestrictionsPayload) GetApartmentEntityIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ApartmentEntityIds
}

// GetApartmentEntityIdsOk returns a tuple with the ApartmentEntityIds field value
// and a boolean to check if the value has been set.
func (o *SetDoorRestrictionsPayload) GetApartmentEntityIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApartmentEntityIds, true
}

// SetApartmentEntityIds sets field value
func (o *SetDoorRestrictionsPayload) SetApartmentEntityIds(v []string) {
	o.ApartmentEntityIds = v
}

func (o SetDoorRestrictionsPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apartment_entity_ids"] = o.ApartmentEntityIds
	return toSerialize, nil
}

func (o *SetDoorRestrictionsPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apartment_entity_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDoorRestrictionsPayload := _SetDoorRestrictionsPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDoorRestrictionsPayload)

	if err != nil {
		return err
	}

	*o = SetDoorRestrictionsPayload(varSetDoorRestrictionsPayload)

	return err
}

type NullableSetDoorRestrictionsPayload struct {
	value *SetDoorRestrictionsPayload
	isSet bool
}

func (v NullableSetDoorRestrictionsPayload) Get() *SetDoorRestrictionsPayload {
	return v.value
}

func (v *NullableSetDoorRestrictionsPayload) Set(val *SetDoorRestrictionsPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDoorRestrictionsPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDoorRestrictionsPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDoorRestrictionsPayload(val *SetDoorRestrictionsPayload) *NullableSetDoorRestrictionsPayload {
	return &NullableSetDoorRestrictionsPayload{value: val, isSet: true}
}

func (v NullableSetDoorRestrictionsPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDoorRestrictionsPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
