/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Zone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Zone{}

// Zone A logical or physical space (recursive for hierarchy).  Example: Floor 1 > Living Room > TV Nook
type Zone struct {
	// External ID from the integration.
	ExternalId NullableString `json:"external_id,omitempty"`
	// Unique identifier (ULID).
	Id string `json:"id"`
	// Integration this zone belongs to.
	IntegrationId string            `json:"integration_id"`
	Metadata      map[string]string `json:"metadata,omitempty"`
	// Zone name.
	Name LocalizedString `json:"name"`
	// Parent zone for hierarchy.
	ParentZoneId NullableString `json:"parent_zone_id,omitempty"`
}

type _Zone Zone

// NewZone instantiates a new Zone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZone(id string, integrationId string, name LocalizedString) *Zone {
	this := Zone{}
	this.Id = id
	this.IntegrationId = integrationId
	this.Name = name
	return &this
}

// NewZoneWithDefaults instantiates a new Zone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZoneWithDefaults() *Zone {
	this := Zone{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Zone) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Zone) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *Zone) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *Zone) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *Zone) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *Zone) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetId returns the Id field value
func (o *Zone) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Zone) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Zone) SetId(v string) {
	o.Id = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *Zone) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *Zone) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *Zone) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Zone) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Zone) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Zone) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *Zone) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetName returns the Name field value
func (o *Zone) GetName() LocalizedString {
	if o == nil {
		var ret LocalizedString
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Zone) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Zone) SetName(v LocalizedString) {
	o.Name = v
}

// GetParentZoneId returns the ParentZoneId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Zone) GetParentZoneId() string {
	if o == nil || IsNil(o.ParentZoneId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentZoneId.Get()
}

// GetParentZoneIdOk returns a tuple with the ParentZoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Zone) GetParentZoneIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentZoneId.Get(), o.ParentZoneId.IsSet()
}

// HasParentZoneId returns a boolean if a field has been set.
func (o *Zone) HasParentZoneId() bool {
	if o != nil && o.ParentZoneId.IsSet() {
		return true
	}

	return false
}

// SetParentZoneId gets a reference to the given NullableString and assigns it to the ParentZoneId field.
func (o *Zone) SetParentZoneId(v string) {
	o.ParentZoneId.Set(&v)
}

// SetParentZoneIdNil sets the value for ParentZoneId to be an explicit nil
func (o *Zone) SetParentZoneIdNil() {
	o.ParentZoneId.Set(nil)
}

// UnsetParentZoneId ensures that no value is present for ParentZoneId, not even an explicit nil
func (o *Zone) UnsetParentZoneId() {
	o.ParentZoneId.Unset()
}

func (o Zone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ExternalId.IsSet() {
		toSerialize["external_id"] = o.ExternalId.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["integration_id"] = o.IntegrationId
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	if o.ParentZoneId.IsSet() {
		toSerialize["parent_zone_id"] = o.ParentZoneId.Get()
	}
	return toSerialize, nil
}

func (o *Zone) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"integration_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZone := _Zone{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZone)

	if err != nil {
		return err
	}

	*o = Zone(varZone)

	return err
}

type NullableZone struct {
	value *Zone
	isSet bool
}

func (v NullableZone) Get() *Zone {
	return v.value
}

func (v *NullableZone) Set(val *Zone) {
	v.value = val
	v.isSet = true
}

func (v NullableZone) IsSet() bool {
	return v.isSet
}

func (v *NullableZone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZone(val *Zone) *NullableZone {
	return &NullableZone{value: val, isSet: true}
}

func (v NullableZone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
