/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateIntegrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIntegrationRequest{}

// CreateIntegrationRequest struct for CreateIntegrationRequest
type CreateIntegrationRequest struct {
	Config  interface{} `json:"config,omitempty"`
	Enabled *bool       `json:"enabled,omitempty"`
	// Human-friendly name for this integration (optional; defaults server-side). Accepts string or LocalizedString map, e.g. { \"en\": \"Name\", \"he\": \"שם\" }.
	Name         NullableLocalizedString `json:"name,omitempty"`
	OrgId        string                  `json:"org_id"`
	ProviderType string                  `json:"provider_type"`
	Secrets      interface{}             `json:"secrets,omitempty"`
}

type _CreateIntegrationRequest CreateIntegrationRequest

// NewCreateIntegrationRequest instantiates a new CreateIntegrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIntegrationRequest(orgId string, providerType string) *CreateIntegrationRequest {
	this := CreateIntegrationRequest{}
	this.OrgId = orgId
	this.ProviderType = providerType
	return &this
}

// NewCreateIntegrationRequestWithDefaults instantiates a new CreateIntegrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIntegrationRequestWithDefaults() *CreateIntegrationRequest {
	this := CreateIntegrationRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateIntegrationRequest) GetConfig() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateIntegrationRequest) GetConfigOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return &o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateIntegrationRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given interface{} and assigns it to the Config field.
func (o *CreateIntegrationRequest) SetConfig(v interface{}) {
	o.Config = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateIntegrationRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIntegrationRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateIntegrationRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateIntegrationRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateIntegrationRequest) GetName() LocalizedString {
	if o == nil || IsNil(o.Name.Get()) {
		var ret LocalizedString
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateIntegrationRequest) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CreateIntegrationRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableLocalizedString and assigns it to the Name field.
func (o *CreateIntegrationRequest) SetName(v LocalizedString) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *CreateIntegrationRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CreateIntegrationRequest) UnsetName() {
	o.Name.Unset()
}

// GetOrgId returns the OrgId field value
func (o *CreateIntegrationRequest) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *CreateIntegrationRequest) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *CreateIntegrationRequest) SetOrgId(v string) {
	o.OrgId = v
}

// GetProviderType returns the ProviderType field value
func (o *CreateIntegrationRequest) GetProviderType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderType
}

// GetProviderTypeOk returns a tuple with the ProviderType field value
// and a boolean to check if the value has been set.
func (o *CreateIntegrationRequest) GetProviderTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderType, true
}

// SetProviderType sets field value
func (o *CreateIntegrationRequest) SetProviderType(v string) {
	o.ProviderType = v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateIntegrationRequest) GetSecrets() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateIntegrationRequest) GetSecretsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return &o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *CreateIntegrationRequest) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given interface{} and assigns it to the Secrets field.
func (o *CreateIntegrationRequest) SetSecrets(v interface{}) {
	o.Secrets = v
}

func (o CreateIntegrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["org_id"] = o.OrgId
	toSerialize["provider_type"] = o.ProviderType
	if o.Secrets != nil {
		toSerialize["secrets"] = o.Secrets
	}
	return toSerialize, nil
}

func (o *CreateIntegrationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_id",
		"provider_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateIntegrationRequest := _CreateIntegrationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateIntegrationRequest)

	if err != nil {
		return err
	}

	*o = CreateIntegrationRequest(varCreateIntegrationRequest)

	return err
}

type NullableCreateIntegrationRequest struct {
	value *CreateIntegrationRequest
	isSet bool
}

func (v NullableCreateIntegrationRequest) Get() *CreateIntegrationRequest {
	return v.value
}

func (v *NullableCreateIntegrationRequest) Set(val *CreateIntegrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIntegrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIntegrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIntegrationRequest(val *CreateIntegrationRequest) *NullableCreateIntegrationRequest {
	return &NullableCreateIntegrationRequest{value: val, isSet: true}
}

func (v NullableCreateIntegrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIntegrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
