/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetAccessPortalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccessPortalResponse{}

// GetAccessPortalResponse Response for get access portal by ID (includes integration_id for navigation).
type GetAccessPortalResponse struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// When set, the portal is soft-deleted (kept for restore).
	DeletedAt *string `json:"deleted_at,omitempty"`
	// Door device id (virtual_access_portal in this integration). Canonical portal link key.
	DeviceId *string `json:"device_id,omitempty"`
	// Directory device id (virtual_access_directory in this integration).
	DirectoryId   *string         `json:"directory_id,omitempty"`
	Id            string          `json:"id"`
	Name          LocalizedString `json:"name"`
	PublicId      string          `json:"public_id"`
	UpdatedAt     *string         `json:"updated_at,omitempty"`
	IntegrationId string          `json:"integration_id"`
}

type _GetAccessPortalResponse GetAccessPortalResponse

// NewGetAccessPortalResponse instantiates a new GetAccessPortalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccessPortalResponse(id string, name LocalizedString, publicId string, integrationId string) *GetAccessPortalResponse {
	this := GetAccessPortalResponse{}
	this.Id = id
	this.Name = name
	this.PublicId = publicId
	this.IntegrationId = integrationId
	return &this
}

// NewGetAccessPortalResponseWithDefaults instantiates a new GetAccessPortalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccessPortalResponseWithDefaults() *GetAccessPortalResponse {
	this := GetAccessPortalResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetAccessPortalResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetAccessPortalResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetAccessPortalResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *GetAccessPortalResponse) GetDeletedAt() string {
	if o == nil || IsNil(o.DeletedAt) {
		var ret string
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetDeletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *GetAccessPortalResponse) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given string and assigns it to the DeletedAt field.
func (o *GetAccessPortalResponse) SetDeletedAt(v string) {
	o.DeletedAt = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *GetAccessPortalResponse) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *GetAccessPortalResponse) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *GetAccessPortalResponse) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetDirectoryId returns the DirectoryId field value if set, zero value otherwise.
func (o *GetAccessPortalResponse) GetDirectoryId() string {
	if o == nil || IsNil(o.DirectoryId) {
		var ret string
		return ret
	}
	return *o.DirectoryId
}

// GetDirectoryIdOk returns a tuple with the DirectoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetDirectoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryId) {
		return nil, false
	}
	return o.DirectoryId, true
}

// HasDirectoryId returns a boolean if a field has been set.
func (o *GetAccessPortalResponse) HasDirectoryId() bool {
	if o != nil && !IsNil(o.DirectoryId) {
		return true
	}

	return false
}

// SetDirectoryId gets a reference to the given string and assigns it to the DirectoryId field.
func (o *GetAccessPortalResponse) SetDirectoryId(v string) {
	o.DirectoryId = &v
}

// GetId returns the Id field value
func (o *GetAccessPortalResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetAccessPortalResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetAccessPortalResponse) GetName() LocalizedString {
	if o == nil {
		var ret LocalizedString
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetAccessPortalResponse) SetName(v LocalizedString) {
	o.Name = v
}

// GetPublicId returns the PublicId field value
func (o *GetAccessPortalResponse) GetPublicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetPublicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicId, true
}

// SetPublicId sets field value
func (o *GetAccessPortalResponse) SetPublicId(v string) {
	o.PublicId = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetAccessPortalResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetAccessPortalResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetAccessPortalResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetIntegrationId returns the IntegrationId field value
func (o *GetAccessPortalResponse) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *GetAccessPortalResponse) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *GetAccessPortalResponse) SetIntegrationId(v string) {
	o.IntegrationId = v
}

func (o GetAccessPortalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.DeviceId) {
		toSerialize["device_id"] = o.DeviceId
	}
	if !IsNil(o.DirectoryId) {
		toSerialize["directory_id"] = o.DirectoryId
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["public_id"] = o.PublicId
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["integration_id"] = o.IntegrationId
	return toSerialize, nil
}

func (o *GetAccessPortalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"public_id",
		"integration_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAccessPortalResponse := _GetAccessPortalResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAccessPortalResponse)

	if err != nil {
		return err
	}

	*o = GetAccessPortalResponse(varGetAccessPortalResponse)

	return err
}

type NullableGetAccessPortalResponse struct {
	value *GetAccessPortalResponse
	isSet bool
}

func (v NullableGetAccessPortalResponse) Get() *GetAccessPortalResponse {
	return v.value
}

func (v *NullableGetAccessPortalResponse) Set(val *GetAccessPortalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccessPortalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccessPortalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccessPortalResponse(val *GetAccessPortalResponse) *NullableGetAccessPortalResponse {
	return &NullableGetAccessPortalResponse{value: val, isSet: true}
}

func (v NullableGetAccessPortalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccessPortalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
