/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentResponse{}

// AgentResponse struct for AgentResponse
type AgentResponse struct {
	AllowedEntityIds []string       `json:"allowed_entity_ids,omitempty"`
	AllowedPortalIds []string       `json:"allowed_portal_ids,omitempty"`
	AllowedToolNames []string       `json:"allowed_tool_names,omitempty"`
	ConfirmationMode NullableString `json:"confirmation_mode"`
	CreatedAt        NullableString `json:"created_at,omitempty"`
	ExpiresAt        NullableString `json:"expires_at,omitempty"`
	Id               NullableString `json:"id"`
	LastUsedAt       NullableString `json:"last_used_at,omitempty"`
	Name             NullableString `json:"name"`
	OrgId            NullableString `json:"org_id"`
	OwnerUserId      NullableString `json:"owner_user_id"`
	Purpose          NullableString `json:"purpose,omitempty"`
	RevokedAt        NullableString `json:"revoked_at,omitempty"`
	UpdatedAt        NullableString `json:"updated_at,omitempty"`
}

type _AgentResponse AgentResponse

// NewAgentResponse instantiates a new AgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentResponse(confirmationMode NullableString, id NullableString, name NullableString, orgId NullableString, ownerUserId NullableString) *AgentResponse {
	this := AgentResponse{}
	this.ConfirmationMode = confirmationMode
	this.Id = id
	this.Name = name
	this.OrgId = orgId
	this.OwnerUserId = ownerUserId
	return &this
}

// NewAgentResponseWithDefaults instantiates a new AgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentResponseWithDefaults() *AgentResponse {
	this := AgentResponse{}
	return &this
}

// GetAllowedEntityIds returns the AllowedEntityIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetAllowedEntityIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedEntityIds
}

// GetAllowedEntityIdsOk returns a tuple with the AllowedEntityIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetAllowedEntityIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedEntityIds) {
		return nil, false
	}
	return o.AllowedEntityIds, true
}

// HasAllowedEntityIds returns a boolean if a field has been set.
func (o *AgentResponse) HasAllowedEntityIds() bool {
	if o != nil && !IsNil(o.AllowedEntityIds) {
		return true
	}

	return false
}

// SetAllowedEntityIds gets a reference to the given []string and assigns it to the AllowedEntityIds field.
func (o *AgentResponse) SetAllowedEntityIds(v []string) {
	o.AllowedEntityIds = v
}

// GetAllowedPortalIds returns the AllowedPortalIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetAllowedPortalIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedPortalIds
}

// GetAllowedPortalIdsOk returns a tuple with the AllowedPortalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetAllowedPortalIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedPortalIds) {
		return nil, false
	}
	return o.AllowedPortalIds, true
}

// HasAllowedPortalIds returns a boolean if a field has been set.
func (o *AgentResponse) HasAllowedPortalIds() bool {
	if o != nil && !IsNil(o.AllowedPortalIds) {
		return true
	}

	return false
}

// SetAllowedPortalIds gets a reference to the given []string and assigns it to the AllowedPortalIds field.
func (o *AgentResponse) SetAllowedPortalIds(v []string) {
	o.AllowedPortalIds = v
}

// GetAllowedToolNames returns the AllowedToolNames field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetAllowedToolNames() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedToolNames
}

// GetAllowedToolNamesOk returns a tuple with the AllowedToolNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetAllowedToolNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedToolNames) {
		return nil, false
	}
	return o.AllowedToolNames, true
}

// HasAllowedToolNames returns a boolean if a field has been set.
func (o *AgentResponse) HasAllowedToolNames() bool {
	if o != nil && !IsNil(o.AllowedToolNames) {
		return true
	}

	return false
}

// SetAllowedToolNames gets a reference to the given []string and assigns it to the AllowedToolNames field.
func (o *AgentResponse) SetAllowedToolNames(v []string) {
	o.AllowedToolNames = v
}

// GetConfirmationMode returns the ConfirmationMode field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentResponse) GetConfirmationMode() string {
	if o == nil || o.ConfirmationMode.Get() == nil {
		var ret string
		return ret
	}

	return *o.ConfirmationMode.Get()
}

// GetConfirmationModeOk returns a tuple with the ConfirmationMode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetConfirmationModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfirmationMode.Get(), o.ConfirmationMode.IsSet()
}

// SetConfirmationMode sets field value
func (o *AgentResponse) SetConfirmationMode(v string) {
	o.ConfirmationMode.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *AgentResponse) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *AgentResponse) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *AgentResponse) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *AgentResponse) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableString and assigns it to the ExpiresAt field.
func (o *AgentResponse) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *AgentResponse) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *AgentResponse) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentResponse) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *AgentResponse) SetId(v string) {
	o.Id.Set(&v)
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetLastUsedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *AgentResponse) HasLastUsedAt() bool {
	if o != nil && o.LastUsedAt.IsSet() {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given NullableString and assigns it to the LastUsedAt field.
func (o *AgentResponse) SetLastUsedAt(v string) {
	o.LastUsedAt.Set(&v)
}

// SetLastUsedAtNil sets the value for LastUsedAt to be an explicit nil
func (o *AgentResponse) SetLastUsedAtNil() {
	o.LastUsedAt.Set(nil)
}

// UnsetLastUsedAt ensures that no value is present for LastUsedAt, not even an explicit nil
func (o *AgentResponse) UnsetLastUsedAt() {
	o.LastUsedAt.Unset()
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentResponse) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *AgentResponse) SetName(v string) {
	o.Name.Set(&v)
}

// GetOrgId returns the OrgId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentResponse) GetOrgId() string {
	if o == nil || o.OrgId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// SetOrgId sets field value
func (o *AgentResponse) SetOrgId(v string) {
	o.OrgId.Set(&v)
}

// GetOwnerUserId returns the OwnerUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AgentResponse) GetOwnerUserId() string {
	if o == nil || o.OwnerUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OwnerUserId.Get()
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetOwnerUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerUserId.Get(), o.OwnerUserId.IsSet()
}

// SetOwnerUserId sets field value
func (o *AgentResponse) SetOwnerUserId(v string) {
	o.OwnerUserId.Set(&v)
}

// GetPurpose returns the Purpose field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetPurpose() string {
	if o == nil || IsNil(o.Purpose.Get()) {
		var ret string
		return ret
	}
	return *o.Purpose.Get()
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purpose.Get(), o.Purpose.IsSet()
}

// HasPurpose returns a boolean if a field has been set.
func (o *AgentResponse) HasPurpose() bool {
	if o != nil && o.Purpose.IsSet() {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given NullableString and assigns it to the Purpose field.
func (o *AgentResponse) SetPurpose(v string) {
	o.Purpose.Set(&v)
}

// SetPurposeNil sets the value for Purpose to be an explicit nil
func (o *AgentResponse) SetPurposeNil() {
	o.Purpose.Set(nil)
}

// UnsetPurpose ensures that no value is present for Purpose, not even an explicit nil
func (o *AgentResponse) UnsetPurpose() {
	o.Purpose.Unset()
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt.Get()) {
		var ret string
		return ret
	}
	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetRevokedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *AgentResponse) HasRevokedAt() bool {
	if o != nil && o.RevokedAt.IsSet() {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given NullableString and assigns it to the RevokedAt field.
func (o *AgentResponse) SetRevokedAt(v string) {
	o.RevokedAt.Set(&v)
}

// SetRevokedAtNil sets the value for RevokedAt to be an explicit nil
func (o *AgentResponse) SetRevokedAtNil() {
	o.RevokedAt.Set(nil)
}

// UnsetRevokedAt ensures that no value is present for RevokedAt, not even an explicit nil
func (o *AgentResponse) UnsetRevokedAt() {
	o.RevokedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AgentResponse) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableString and assigns it to the UpdatedAt field.
func (o *AgentResponse) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *AgentResponse) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *AgentResponse) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o AgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedEntityIds != nil {
		toSerialize["allowed_entity_ids"] = o.AllowedEntityIds
	}
	if o.AllowedPortalIds != nil {
		toSerialize["allowed_portal_ids"] = o.AllowedPortalIds
	}
	if o.AllowedToolNames != nil {
		toSerialize["allowed_tool_names"] = o.AllowedToolNames
	}
	toSerialize["confirmation_mode"] = o.ConfirmationMode.Get()
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	toSerialize["id"] = o.Id.Get()
	if o.LastUsedAt.IsSet() {
		toSerialize["last_used_at"] = o.LastUsedAt.Get()
	}
	toSerialize["name"] = o.Name.Get()
	toSerialize["org_id"] = o.OrgId.Get()
	toSerialize["owner_user_id"] = o.OwnerUserId.Get()
	if o.Purpose.IsSet() {
		toSerialize["purpose"] = o.Purpose.Get()
	}
	if o.RevokedAt.IsSet() {
		toSerialize["revoked_at"] = o.RevokedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

func (o *AgentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"confirmation_mode",
		"id",
		"name",
		"org_id",
		"owner_user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentResponse := _AgentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentResponse)

	if err != nil {
		return err
	}

	*o = AgentResponse(varAgentResponse)

	return err
}

type NullableAgentResponse struct {
	value *AgentResponse
	isSet bool
}

func (v NullableAgentResponse) Get() *AgentResponse {
	return v.value
}

func (v *NullableAgentResponse) Set(val *AgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentResponse(val *AgentResponse) *NullableAgentResponse {
	return &NullableAgentResponse{value: val, isSet: true}
}

func (v NullableAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
