/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateAccessInviteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAccessInviteRequest{}

// UpdateAccessInviteRequest struct for UpdateAccessInviteRequest
type UpdateAccessInviteRequest struct {
	DisabledJustification NullableString `json:"disabled_justification,omitempty"`
	ExpiresIn             NullableString `json:"expires_in,omitempty"`
	InviteRecurrence      interface{}    `json:"invite_recurrence,omitempty"`
	InviteeMessage        interface{}    `json:"invitee_message,omitempty"`
	IsEnabled             NullableBool   `json:"is_enabled,omitempty"`
	MaxUses               NullableInt32  `json:"max_uses,omitempty"`
	Name                  NullableString `json:"name,omitempty"`
	PortalIds             []string       `json:"portal_ids,omitempty"`
	// When set, replaces all schedule entries. Required when changing times/recurrence on an invite that already has multiple schedule entries.
	Schedules []InviteScheduleEntryInput `json:"schedules,omitempty"`
	ValidFrom NullableString             `json:"valid_from,omitempty"`
	ValidTo   NullableString             `json:"valid_to,omitempty"`
}

// NewUpdateAccessInviteRequest instantiates a new UpdateAccessInviteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAccessInviteRequest() *UpdateAccessInviteRequest {
	this := UpdateAccessInviteRequest{}
	return &this
}

// NewUpdateAccessInviteRequestWithDefaults instantiates a new UpdateAccessInviteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAccessInviteRequestWithDefaults() *UpdateAccessInviteRequest {
	this := UpdateAccessInviteRequest{}
	return &this
}

// GetDisabledJustification returns the DisabledJustification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetDisabledJustification() string {
	if o == nil || IsNil(o.DisabledJustification.Get()) {
		var ret string
		return ret
	}
	return *o.DisabledJustification.Get()
}

// GetDisabledJustificationOk returns a tuple with the DisabledJustification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetDisabledJustificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisabledJustification.Get(), o.DisabledJustification.IsSet()
}

// HasDisabledJustification returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasDisabledJustification() bool {
	if o != nil && o.DisabledJustification.IsSet() {
		return true
	}

	return false
}

// SetDisabledJustification gets a reference to the given NullableString and assigns it to the DisabledJustification field.
func (o *UpdateAccessInviteRequest) SetDisabledJustification(v string) {
	o.DisabledJustification.Set(&v)
}

// SetDisabledJustificationNil sets the value for DisabledJustification to be an explicit nil
func (o *UpdateAccessInviteRequest) SetDisabledJustificationNil() {
	o.DisabledJustification.Set(nil)
}

// UnsetDisabledJustification ensures that no value is present for DisabledJustification, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetDisabledJustification() {
	o.DisabledJustification.Unset()
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetExpiresIn() string {
	if o == nil || IsNil(o.ExpiresIn.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresIn.Get()
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetExpiresInOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresIn.Get(), o.ExpiresIn.IsSet()
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasExpiresIn() bool {
	if o != nil && o.ExpiresIn.IsSet() {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given NullableString and assigns it to the ExpiresIn field.
func (o *UpdateAccessInviteRequest) SetExpiresIn(v string) {
	o.ExpiresIn.Set(&v)
}

// SetExpiresInNil sets the value for ExpiresIn to be an explicit nil
func (o *UpdateAccessInviteRequest) SetExpiresInNil() {
	o.ExpiresIn.Set(nil)
}

// UnsetExpiresIn ensures that no value is present for ExpiresIn, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetExpiresIn() {
	o.ExpiresIn.Unset()
}

// GetInviteRecurrence returns the InviteRecurrence field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetInviteRecurrence() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InviteRecurrence
}

// GetInviteRecurrenceOk returns a tuple with the InviteRecurrence field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetInviteRecurrenceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InviteRecurrence) {
		return nil, false
	}
	return &o.InviteRecurrence, true
}

// HasInviteRecurrence returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasInviteRecurrence() bool {
	if o != nil && !IsNil(o.InviteRecurrence) {
		return true
	}

	return false
}

// SetInviteRecurrence gets a reference to the given interface{} and assigns it to the InviteRecurrence field.
func (o *UpdateAccessInviteRequest) SetInviteRecurrence(v interface{}) {
	o.InviteRecurrence = v
}

// GetInviteeMessage returns the InviteeMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetInviteeMessage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InviteeMessage
}

// GetInviteeMessageOk returns a tuple with the InviteeMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetInviteeMessageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InviteeMessage) {
		return nil, false
	}
	return &o.InviteeMessage, true
}

// HasInviteeMessage returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasInviteeMessage() bool {
	if o != nil && !IsNil(o.InviteeMessage) {
		return true
	}

	return false
}

// SetInviteeMessage gets a reference to the given interface{} and assigns it to the InviteeMessage field.
func (o *UpdateAccessInviteRequest) SetInviteeMessage(v interface{}) {
	o.InviteeMessage = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.IsEnabled.Get()
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsEnabled.Get(), o.IsEnabled.IsSet()
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasIsEnabled() bool {
	if o != nil && o.IsEnabled.IsSet() {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given NullableBool and assigns it to the IsEnabled field.
func (o *UpdateAccessInviteRequest) SetIsEnabled(v bool) {
	o.IsEnabled.Set(&v)
}

// SetIsEnabledNil sets the value for IsEnabled to be an explicit nil
func (o *UpdateAccessInviteRequest) SetIsEnabledNil() {
	o.IsEnabled.Set(nil)
}

// UnsetIsEnabled ensures that no value is present for IsEnabled, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetIsEnabled() {
	o.IsEnabled.Unset()
}

// GetMaxUses returns the MaxUses field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetMaxUses() int32 {
	if o == nil || IsNil(o.MaxUses.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxUses.Get()
}

// GetMaxUsesOk returns a tuple with the MaxUses field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetMaxUsesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxUses.Get(), o.MaxUses.IsSet()
}

// HasMaxUses returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasMaxUses() bool {
	if o != nil && o.MaxUses.IsSet() {
		return true
	}

	return false
}

// SetMaxUses gets a reference to the given NullableInt32 and assigns it to the MaxUses field.
func (o *UpdateAccessInviteRequest) SetMaxUses(v int32) {
	o.MaxUses.Set(&v)
}

// SetMaxUsesNil sets the value for MaxUses to be an explicit nil
func (o *UpdateAccessInviteRequest) SetMaxUsesNil() {
	o.MaxUses.Set(nil)
}

// UnsetMaxUses ensures that no value is present for MaxUses, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetMaxUses() {
	o.MaxUses.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateAccessInviteRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateAccessInviteRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetName() {
	o.Name.Unset()
}

// GetPortalIds returns the PortalIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetPortalIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.PortalIds
}

// GetPortalIdsOk returns a tuple with the PortalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetPortalIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PortalIds) {
		return nil, false
	}
	return o.PortalIds, true
}

// HasPortalIds returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasPortalIds() bool {
	if o != nil && !IsNil(o.PortalIds) {
		return true
	}

	return false
}

// SetPortalIds gets a reference to the given []string and assigns it to the PortalIds field.
func (o *UpdateAccessInviteRequest) SetPortalIds(v []string) {
	o.PortalIds = v
}

// GetSchedules returns the Schedules field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetSchedules() []InviteScheduleEntryInput {
	if o == nil {
		var ret []InviteScheduleEntryInput
		return ret
	}
	return o.Schedules
}

// GetSchedulesOk returns a tuple with the Schedules field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetSchedulesOk() ([]InviteScheduleEntryInput, bool) {
	if o == nil || IsNil(o.Schedules) {
		return nil, false
	}
	return o.Schedules, true
}

// HasSchedules returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasSchedules() bool {
	if o != nil && !IsNil(o.Schedules) {
		return true
	}

	return false
}

// SetSchedules gets a reference to the given []InviteScheduleEntryInput and assigns it to the Schedules field.
func (o *UpdateAccessInviteRequest) SetSchedules(v []InviteScheduleEntryInput) {
	o.Schedules = v
}

// GetValidFrom returns the ValidFrom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetValidFrom() string {
	if o == nil || IsNil(o.ValidFrom.Get()) {
		var ret string
		return ret
	}
	return *o.ValidFrom.Get()
}

// GetValidFromOk returns a tuple with the ValidFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetValidFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidFrom.Get(), o.ValidFrom.IsSet()
}

// HasValidFrom returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasValidFrom() bool {
	if o != nil && o.ValidFrom.IsSet() {
		return true
	}

	return false
}

// SetValidFrom gets a reference to the given NullableString and assigns it to the ValidFrom field.
func (o *UpdateAccessInviteRequest) SetValidFrom(v string) {
	o.ValidFrom.Set(&v)
}

// SetValidFromNil sets the value for ValidFrom to be an explicit nil
func (o *UpdateAccessInviteRequest) SetValidFromNil() {
	o.ValidFrom.Set(nil)
}

// UnsetValidFrom ensures that no value is present for ValidFrom, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetValidFrom() {
	o.ValidFrom.Unset()
}

// GetValidTo returns the ValidTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessInviteRequest) GetValidTo() string {
	if o == nil || IsNil(o.ValidTo.Get()) {
		var ret string
		return ret
	}
	return *o.ValidTo.Get()
}

// GetValidToOk returns a tuple with the ValidTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessInviteRequest) GetValidToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidTo.Get(), o.ValidTo.IsSet()
}

// HasValidTo returns a boolean if a field has been set.
func (o *UpdateAccessInviteRequest) HasValidTo() bool {
	if o != nil && o.ValidTo.IsSet() {
		return true
	}

	return false
}

// SetValidTo gets a reference to the given NullableString and assigns it to the ValidTo field.
func (o *UpdateAccessInviteRequest) SetValidTo(v string) {
	o.ValidTo.Set(&v)
}

// SetValidToNil sets the value for ValidTo to be an explicit nil
func (o *UpdateAccessInviteRequest) SetValidToNil() {
	o.ValidTo.Set(nil)
}

// UnsetValidTo ensures that no value is present for ValidTo, not even an explicit nil
func (o *UpdateAccessInviteRequest) UnsetValidTo() {
	o.ValidTo.Unset()
}

func (o UpdateAccessInviteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DisabledJustification.IsSet() {
		toSerialize["disabled_justification"] = o.DisabledJustification.Get()
	}
	if o.ExpiresIn.IsSet() {
		toSerialize["expires_in"] = o.ExpiresIn.Get()
	}
	if o.InviteRecurrence != nil {
		toSerialize["invite_recurrence"] = o.InviteRecurrence
	}
	if o.InviteeMessage != nil {
		toSerialize["invitee_message"] = o.InviteeMessage
	}
	if o.IsEnabled.IsSet() {
		toSerialize["is_enabled"] = o.IsEnabled.Get()
	}
	if o.MaxUses.IsSet() {
		toSerialize["max_uses"] = o.MaxUses.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.PortalIds != nil {
		toSerialize["portal_ids"] = o.PortalIds
	}
	if o.Schedules != nil {
		toSerialize["schedules"] = o.Schedules
	}
	if o.ValidFrom.IsSet() {
		toSerialize["valid_from"] = o.ValidFrom.Get()
	}
	if o.ValidTo.IsSet() {
		toSerialize["valid_to"] = o.ValidTo.Get()
	}
	return toSerialize, nil
}

type NullableUpdateAccessInviteRequest struct {
	value *UpdateAccessInviteRequest
	isSet bool
}

func (v NullableUpdateAccessInviteRequest) Get() *UpdateAccessInviteRequest {
	return v.value
}

func (v *NullableUpdateAccessInviteRequest) Set(val *UpdateAccessInviteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAccessInviteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAccessInviteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAccessInviteRequest(val *UpdateAccessInviteRequest) *NullableUpdateAccessInviteRequest {
	return &NullableUpdateAccessInviteRequest{value: val, isSet: true}
}

func (v NullableUpdateAccessInviteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAccessInviteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
