/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListInvitationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListInvitationsResponse{}

// ListInvitationsResponse struct for ListInvitationsResponse
type ListInvitationsResponse struct {
	Invitations []UserInvitationDto `json:"invitations"`
}

type _ListInvitationsResponse ListInvitationsResponse

// NewListInvitationsResponse instantiates a new ListInvitationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInvitationsResponse(invitations []UserInvitationDto) *ListInvitationsResponse {
	this := ListInvitationsResponse{}
	this.Invitations = invitations
	return &this
}

// NewListInvitationsResponseWithDefaults instantiates a new ListInvitationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInvitationsResponseWithDefaults() *ListInvitationsResponse {
	this := ListInvitationsResponse{}
	return &this
}

// GetInvitations returns the Invitations field value
func (o *ListInvitationsResponse) GetInvitations() []UserInvitationDto {
	if o == nil {
		var ret []UserInvitationDto
		return ret
	}

	return o.Invitations
}

// GetInvitationsOk returns a tuple with the Invitations field value
// and a boolean to check if the value has been set.
func (o *ListInvitationsResponse) GetInvitationsOk() ([]UserInvitationDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Invitations, true
}

// SetInvitations sets field value
func (o *ListInvitationsResponse) SetInvitations(v []UserInvitationDto) {
	o.Invitations = v
}

func (o ListInvitationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invitations"] = o.Invitations
	return toSerialize, nil
}

func (o *ListInvitationsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invitations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListInvitationsResponse := _ListInvitationsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListInvitationsResponse)

	if err != nil {
		return err
	}

	*o = ListInvitationsResponse(varListInvitationsResponse)

	return err
}

type NullableListInvitationsResponse struct {
	value *ListInvitationsResponse
	isSet bool
}

func (v NullableListInvitationsResponse) Get() *ListInvitationsResponse {
	return v.value
}

func (v *NullableListInvitationsResponse) Set(val *ListInvitationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListInvitationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListInvitationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInvitationsResponse(val *ListInvitationsResponse) *NullableListInvitationsResponse {
	return &NullableListInvitationsResponse{value: val, isSet: true}
}

func (v NullableListInvitationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInvitationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
