/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkillStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillStep{}

// SkillStep struct for SkillStep
type SkillStep struct {
	Args interface{} `json:"args,omitempty"`
	Tool string      `json:"tool"`
}

type _SkillStep SkillStep

// NewSkillStep instantiates a new SkillStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillStep(tool string) *SkillStep {
	this := SkillStep{}
	this.Tool = tool
	return &this
}

// NewSkillStepWithDefaults instantiates a new SkillStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillStepWithDefaults() *SkillStep {
	this := SkillStep{}
	return &this
}

// GetArgs returns the Args field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillStep) GetArgs() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillStep) GetArgsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return &o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *SkillStep) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given interface{} and assigns it to the Args field.
func (o *SkillStep) SetArgs(v interface{}) {
	o.Args = v
}

// GetTool returns the Tool field value
func (o *SkillStep) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *SkillStep) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *SkillStep) SetTool(v string) {
	o.Tool = v
}

func (o SkillStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Args != nil {
		toSerialize["args"] = o.Args
	}
	toSerialize["tool"] = o.Tool
	return toSerialize, nil
}

func (o *SkillStep) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tool",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkillStep := _SkillStep{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkillStep)

	if err != nil {
		return err
	}

	*o = SkillStep(varSkillStep)

	return err
}

type NullableSkillStep struct {
	value *SkillStep
	isSet bool
}

func (v NullableSkillStep) Get() *SkillStep {
	return v.value
}

func (v *NullableSkillStep) Set(val *SkillStep) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillStep) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillStep(val *SkillStep) *NullableSkillStep {
	return &NullableSkillStep{value: val, isSet: true}
}

func (v NullableSkillStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
