/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PerceptionLprRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerceptionLprRequest{}

// PerceptionLprRequest struct for PerceptionLprRequest
type PerceptionLprRequest struct {
	EntityId string      `json:"entity_id"`
	Evidence interface{} `json:"evidence,omitempty"`
	Plate    string      `json:"plate"`
}

type _PerceptionLprRequest PerceptionLprRequest

// NewPerceptionLprRequest instantiates a new PerceptionLprRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerceptionLprRequest(entityId string, plate string) *PerceptionLprRequest {
	this := PerceptionLprRequest{}
	this.EntityId = entityId
	this.Plate = plate
	return &this
}

// NewPerceptionLprRequestWithDefaults instantiates a new PerceptionLprRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerceptionLprRequestWithDefaults() *PerceptionLprRequest {
	this := PerceptionLprRequest{}
	return &this
}

// GetEntityId returns the EntityId field value
func (o *PerceptionLprRequest) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *PerceptionLprRequest) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *PerceptionLprRequest) SetEntityId(v string) {
	o.EntityId = v
}

// GetEvidence returns the Evidence field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PerceptionLprRequest) GetEvidence() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PerceptionLprRequest) GetEvidenceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Evidence) {
		return nil, false
	}
	return &o.Evidence, true
}

// HasEvidence returns a boolean if a field has been set.
func (o *PerceptionLprRequest) HasEvidence() bool {
	if o != nil && !IsNil(o.Evidence) {
		return true
	}

	return false
}

// SetEvidence gets a reference to the given interface{} and assigns it to the Evidence field.
func (o *PerceptionLprRequest) SetEvidence(v interface{}) {
	o.Evidence = v
}

// GetPlate returns the Plate field value
func (o *PerceptionLprRequest) GetPlate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plate
}

// GetPlateOk returns a tuple with the Plate field value
// and a boolean to check if the value has been set.
func (o *PerceptionLprRequest) GetPlateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plate, true
}

// SetPlate sets field value
func (o *PerceptionLprRequest) SetPlate(v string) {
	o.Plate = v
}

func (o PerceptionLprRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entity_id"] = o.EntityId
	if o.Evidence != nil {
		toSerialize["evidence"] = o.Evidence
	}
	toSerialize["plate"] = o.Plate
	return toSerialize, nil
}

func (o *PerceptionLprRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_id",
		"plate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPerceptionLprRequest := _PerceptionLprRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPerceptionLprRequest)

	if err != nil {
		return err
	}

	*o = PerceptionLprRequest(varPerceptionLprRequest)

	return err
}

type NullablePerceptionLprRequest struct {
	value *PerceptionLprRequest
	isSet bool
}

func (v NullablePerceptionLprRequest) Get() *PerceptionLprRequest {
	return v.value
}

func (v *NullablePerceptionLprRequest) Set(val *PerceptionLprRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePerceptionLprRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePerceptionLprRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerceptionLprRequest(val *PerceptionLprRequest) *NullablePerceptionLprRequest {
	return &NullablePerceptionLprRequest{value: val, isSet: true}
}

func (v NullablePerceptionLprRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerceptionLprRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
