/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PowerFailBehavior the model 'PowerFailBehavior'
type PowerFailBehavior string

// List of PowerFailBehavior
const (
	POWERFAILBEHAVIOR_FAIL_SAFE         PowerFailBehavior = "fail_safe"
	POWERFAILBEHAVIOR_FAIL_SECURE       PowerFailBehavior = "fail_secure"
	POWERFAILBEHAVIOR_MECHANICAL_ALWAYS PowerFailBehavior = "mechanical_always"
)

// All allowed values of PowerFailBehavior enum
var AllowedPowerFailBehaviorEnumValues = []PowerFailBehavior{
	"fail_safe",
	"fail_secure",
	"mechanical_always",
}

func (v *PowerFailBehavior) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PowerFailBehavior(value)
	for _, existing := range AllowedPowerFailBehaviorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PowerFailBehavior", value)
}

// NewPowerFailBehaviorFromValue returns a pointer to a valid PowerFailBehavior
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPowerFailBehaviorFromValue(v string) (*PowerFailBehavior, error) {
	ev := PowerFailBehavior(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PowerFailBehavior: valid values are %v", v, AllowedPowerFailBehaviorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PowerFailBehavior) IsValid() bool {
	for _, existing := range AllowedPowerFailBehaviorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PowerFailBehavior value
func (v PowerFailBehavior) Ptr() *PowerFailBehavior {
	return &v
}

type NullablePowerFailBehavior struct {
	value *PowerFailBehavior
	isSet bool
}

func (v NullablePowerFailBehavior) Get() *PowerFailBehavior {
	return v.value
}

func (v *NullablePowerFailBehavior) Set(val *PowerFailBehavior) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerFailBehavior) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerFailBehavior) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerFailBehavior(val *PowerFailBehavior) *NullablePowerFailBehavior {
	return &NullablePowerFailBehavior{value: val, isSet: true}
}

func (v NullablePowerFailBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerFailBehavior) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
