/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EffectiveLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EffectiveLimit{}

// EffectiveLimit Resolved limit for `(subject, key, period)`, with provenance so the dashboard can explain to admins which line of policy is in effect.
type EffectiveLimit struct {
	// Where this value came from: an override, the org's tier, or the system default.
	Source LimitSource `json:"source"`
	// The effective cap. `None` means \"unlimited\".
	Value NullableInt64 `json:"value,omitempty"`
}

type _EffectiveLimit EffectiveLimit

// NewEffectiveLimit instantiates a new EffectiveLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEffectiveLimit(source LimitSource) *EffectiveLimit {
	this := EffectiveLimit{}
	this.Source = source
	return &this
}

// NewEffectiveLimitWithDefaults instantiates a new EffectiveLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEffectiveLimitWithDefaults() *EffectiveLimit {
	this := EffectiveLimit{}
	return &this
}

// GetSource returns the Source field value
func (o *EffectiveLimit) GetSource() LimitSource {
	if o == nil {
		var ret LimitSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *EffectiveLimit) GetSourceOk() (*LimitSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *EffectiveLimit) SetSource(v LimitSource) {
	o.Source = v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EffectiveLimit) GetValue() int64 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret int64
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EffectiveLimit) GetValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *EffectiveLimit) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableInt64 and assigns it to the Value field.
func (o *EffectiveLimit) SetValue(v int64) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *EffectiveLimit) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *EffectiveLimit) UnsetValue() {
	o.Value.Unset()
}

func (o EffectiveLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

func (o *EffectiveLimit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEffectiveLimit := _EffectiveLimit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEffectiveLimit)

	if err != nil {
		return err
	}

	*o = EffectiveLimit(varEffectiveLimit)

	return err
}

type NullableEffectiveLimit struct {
	value *EffectiveLimit
	isSet bool
}

func (v NullableEffectiveLimit) Get() *EffectiveLimit {
	return v.value
}

func (v *NullableEffectiveLimit) Set(val *EffectiveLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableEffectiveLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableEffectiveLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEffectiveLimit(val *EffectiveLimit) *NullableEffectiveLimit {
	return &NullableEffectiveLimit{value: val, isSet: true}
}

func (v NullableEffectiveLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEffectiveLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
