/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExecuteScriptingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteScriptingRequest{}

// ExecuteScriptingRequest struct for ExecuteScriptingRequest
type ExecuteScriptingRequest struct {
	Script string `json:"script"`
}

type _ExecuteScriptingRequest ExecuteScriptingRequest

// NewExecuteScriptingRequest instantiates a new ExecuteScriptingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteScriptingRequest(script string) *ExecuteScriptingRequest {
	this := ExecuteScriptingRequest{}
	this.Script = script
	return &this
}

// NewExecuteScriptingRequestWithDefaults instantiates a new ExecuteScriptingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteScriptingRequestWithDefaults() *ExecuteScriptingRequest {
	this := ExecuteScriptingRequest{}
	return &this
}

// GetScript returns the Script field value
func (o *ExecuteScriptingRequest) GetScript() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Script
}

// GetScriptOk returns a tuple with the Script field value
// and a boolean to check if the value has been set.
func (o *ExecuteScriptingRequest) GetScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Script, true
}

// SetScript sets field value
func (o *ExecuteScriptingRequest) SetScript(v string) {
	o.Script = v
}

func (o ExecuteScriptingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["script"] = o.Script
	return toSerialize, nil
}

func (o *ExecuteScriptingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"script",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteScriptingRequest := _ExecuteScriptingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecuteScriptingRequest)

	if err != nil {
		return err
	}

	*o = ExecuteScriptingRequest(varExecuteScriptingRequest)

	return err
}

type NullableExecuteScriptingRequest struct {
	value *ExecuteScriptingRequest
	isSet bool
}

func (v NullableExecuteScriptingRequest) Get() *ExecuteScriptingRequest {
	return v.value
}

func (v *NullableExecuteScriptingRequest) Set(val *ExecuteScriptingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteScriptingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteScriptingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteScriptingRequest(val *ExecuteScriptingRequest) *NullableExecuteScriptingRequest {
	return &NullableExecuteScriptingRequest{value: val, isSet: true}
}

func (v NullableExecuteScriptingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteScriptingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
