/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LanAgentMetaResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LanAgentMetaResponse{}

// LanAgentMetaResponse struct for LanAgentMetaResponse
type LanAgentMetaResponse struct {
	LanProtocolVersion       int32          `json:"lan_protocol_version"`
	LatestAgentVersion       NullableString `json:"latest_agent_version,omitempty"`
	MinSupportedAgentVersion NullableString `json:"min_supported_agent_version,omitempty"`
	TasksCatalog             interface{}    `json:"tasks_catalog"`
	UpgradeDownloadUrl       NullableString `json:"upgrade_download_url,omitempty"`
}

type _LanAgentMetaResponse LanAgentMetaResponse

// NewLanAgentMetaResponse instantiates a new LanAgentMetaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLanAgentMetaResponse(lanProtocolVersion int32, tasksCatalog interface{}) *LanAgentMetaResponse {
	this := LanAgentMetaResponse{}
	this.LanProtocolVersion = lanProtocolVersion
	this.TasksCatalog = tasksCatalog
	return &this
}

// NewLanAgentMetaResponseWithDefaults instantiates a new LanAgentMetaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLanAgentMetaResponseWithDefaults() *LanAgentMetaResponse {
	this := LanAgentMetaResponse{}
	return &this
}

// GetLanProtocolVersion returns the LanProtocolVersion field value
func (o *LanAgentMetaResponse) GetLanProtocolVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LanProtocolVersion
}

// GetLanProtocolVersionOk returns a tuple with the LanProtocolVersion field value
// and a boolean to check if the value has been set.
func (o *LanAgentMetaResponse) GetLanProtocolVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LanProtocolVersion, true
}

// SetLanProtocolVersion sets field value
func (o *LanAgentMetaResponse) SetLanProtocolVersion(v int32) {
	o.LanProtocolVersion = v
}

// GetLatestAgentVersion returns the LatestAgentVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LanAgentMetaResponse) GetLatestAgentVersion() string {
	if o == nil || IsNil(o.LatestAgentVersion.Get()) {
		var ret string
		return ret
	}
	return *o.LatestAgentVersion.Get()
}

// GetLatestAgentVersionOk returns a tuple with the LatestAgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LanAgentMetaResponse) GetLatestAgentVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatestAgentVersion.Get(), o.LatestAgentVersion.IsSet()
}

// HasLatestAgentVersion returns a boolean if a field has been set.
func (o *LanAgentMetaResponse) HasLatestAgentVersion() bool {
	if o != nil && o.LatestAgentVersion.IsSet() {
		return true
	}

	return false
}

// SetLatestAgentVersion gets a reference to the given NullableString and assigns it to the LatestAgentVersion field.
func (o *LanAgentMetaResponse) SetLatestAgentVersion(v string) {
	o.LatestAgentVersion.Set(&v)
}

// SetLatestAgentVersionNil sets the value for LatestAgentVersion to be an explicit nil
func (o *LanAgentMetaResponse) SetLatestAgentVersionNil() {
	o.LatestAgentVersion.Set(nil)
}

// UnsetLatestAgentVersion ensures that no value is present for LatestAgentVersion, not even an explicit nil
func (o *LanAgentMetaResponse) UnsetLatestAgentVersion() {
	o.LatestAgentVersion.Unset()
}

// GetMinSupportedAgentVersion returns the MinSupportedAgentVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LanAgentMetaResponse) GetMinSupportedAgentVersion() string {
	if o == nil || IsNil(o.MinSupportedAgentVersion.Get()) {
		var ret string
		return ret
	}
	return *o.MinSupportedAgentVersion.Get()
}

// GetMinSupportedAgentVersionOk returns a tuple with the MinSupportedAgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LanAgentMetaResponse) GetMinSupportedAgentVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinSupportedAgentVersion.Get(), o.MinSupportedAgentVersion.IsSet()
}

// HasMinSupportedAgentVersion returns a boolean if a field has been set.
func (o *LanAgentMetaResponse) HasMinSupportedAgentVersion() bool {
	if o != nil && o.MinSupportedAgentVersion.IsSet() {
		return true
	}

	return false
}

// SetMinSupportedAgentVersion gets a reference to the given NullableString and assigns it to the MinSupportedAgentVersion field.
func (o *LanAgentMetaResponse) SetMinSupportedAgentVersion(v string) {
	o.MinSupportedAgentVersion.Set(&v)
}

// SetMinSupportedAgentVersionNil sets the value for MinSupportedAgentVersion to be an explicit nil
func (o *LanAgentMetaResponse) SetMinSupportedAgentVersionNil() {
	o.MinSupportedAgentVersion.Set(nil)
}

// UnsetMinSupportedAgentVersion ensures that no value is present for MinSupportedAgentVersion, not even an explicit nil
func (o *LanAgentMetaResponse) UnsetMinSupportedAgentVersion() {
	o.MinSupportedAgentVersion.Unset()
}

// GetTasksCatalog returns the TasksCatalog field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *LanAgentMetaResponse) GetTasksCatalog() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.TasksCatalog
}

// GetTasksCatalogOk returns a tuple with the TasksCatalog field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LanAgentMetaResponse) GetTasksCatalogOk() (*interface{}, bool) {
	if o == nil || IsNil(o.TasksCatalog) {
		return nil, false
	}
	return &o.TasksCatalog, true
}

// SetTasksCatalog sets field value
func (o *LanAgentMetaResponse) SetTasksCatalog(v interface{}) {
	o.TasksCatalog = v
}

// GetUpgradeDownloadUrl returns the UpgradeDownloadUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LanAgentMetaResponse) GetUpgradeDownloadUrl() string {
	if o == nil || IsNil(o.UpgradeDownloadUrl.Get()) {
		var ret string
		return ret
	}
	return *o.UpgradeDownloadUrl.Get()
}

// GetUpgradeDownloadUrlOk returns a tuple with the UpgradeDownloadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LanAgentMetaResponse) GetUpgradeDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpgradeDownloadUrl.Get(), o.UpgradeDownloadUrl.IsSet()
}

// HasUpgradeDownloadUrl returns a boolean if a field has been set.
func (o *LanAgentMetaResponse) HasUpgradeDownloadUrl() bool {
	if o != nil && o.UpgradeDownloadUrl.IsSet() {
		return true
	}

	return false
}

// SetUpgradeDownloadUrl gets a reference to the given NullableString and assigns it to the UpgradeDownloadUrl field.
func (o *LanAgentMetaResponse) SetUpgradeDownloadUrl(v string) {
	o.UpgradeDownloadUrl.Set(&v)
}

// SetUpgradeDownloadUrlNil sets the value for UpgradeDownloadUrl to be an explicit nil
func (o *LanAgentMetaResponse) SetUpgradeDownloadUrlNil() {
	o.UpgradeDownloadUrl.Set(nil)
}

// UnsetUpgradeDownloadUrl ensures that no value is present for UpgradeDownloadUrl, not even an explicit nil
func (o *LanAgentMetaResponse) UnsetUpgradeDownloadUrl() {
	o.UpgradeDownloadUrl.Unset()
}

func (o LanAgentMetaResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lan_protocol_version"] = o.LanProtocolVersion
	if o.LatestAgentVersion.IsSet() {
		toSerialize["latest_agent_version"] = o.LatestAgentVersion.Get()
	}
	if o.MinSupportedAgentVersion.IsSet() {
		toSerialize["min_supported_agent_version"] = o.MinSupportedAgentVersion.Get()
	}
	if o.TasksCatalog != nil {
		toSerialize["tasks_catalog"] = o.TasksCatalog
	}
	if o.UpgradeDownloadUrl.IsSet() {
		toSerialize["upgrade_download_url"] = o.UpgradeDownloadUrl.Get()
	}
	return toSerialize, nil
}

func (o *LanAgentMetaResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lan_protocol_version",
		"tasks_catalog",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLanAgentMetaResponse := _LanAgentMetaResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLanAgentMetaResponse)

	if err != nil {
		return err
	}

	*o = LanAgentMetaResponse(varLanAgentMetaResponse)

	return err
}

type NullableLanAgentMetaResponse struct {
	value *LanAgentMetaResponse
	isSet bool
}

func (v NullableLanAgentMetaResponse) Get() *LanAgentMetaResponse {
	return v.value
}

func (v *NullableLanAgentMetaResponse) Set(val *LanAgentMetaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLanAgentMetaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLanAgentMetaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanAgentMetaResponse(val *LanAgentMetaResponse) *NullableLanAgentMetaResponse {
	return &NullableLanAgentMetaResponse{value: val, isSet: true}
}

func (v NullableLanAgentMetaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanAgentMetaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
