/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InviteLocationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteLocationInput{}

// InviteLocationInput Event-location payload for an access invite. Mirrors the shared location fields; an empty object clears the invite's location on update.
type InviteLocationInput struct {
	City             NullableLocalizedString            `json:"city,omitempty"`
	Country          NullableInviteLocationInputCountry `json:"country,omitempty"`
	FormattedAddress NullableInviteLocationInputCountry `json:"formatted_address,omitempty"`
	Kind             NullableLocationKind               `json:"kind,omitempty"`
	Lat              NullableFloat64                    `json:"lat,omitempty"`
	Lng              NullableFloat64                    `json:"lng,omitempty"`
	Notes            NullableInviteLocationInputCountry `json:"notes,omitempty"`
	PlaceId          NullableString                     `json:"place_id,omitempty"`
}

// NewInviteLocationInput instantiates a new InviteLocationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteLocationInput() *InviteLocationInput {
	this := InviteLocationInput{}
	return &this
}

// NewInviteLocationInputWithDefaults instantiates a new InviteLocationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteLocationInputWithDefaults() *InviteLocationInput {
	this := InviteLocationInput{}
	return &this
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetCity() LocalizedString {
	if o == nil || IsNil(o.City.Get()) {
		var ret LocalizedString
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetCityOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *InviteLocationInput) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableLocalizedString and assigns it to the City field.
func (o *InviteLocationInput) SetCity(v LocalizedString) {
	o.City.Set(&v)
}

// SetCityNil sets the value for City to be an explicit nil
func (o *InviteLocationInput) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *InviteLocationInput) UnsetCity() {
	o.City.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetCountry() InviteLocationInputCountry {
	if o == nil || IsNil(o.Country.Get()) {
		var ret InviteLocationInputCountry
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetCountryOk() (*InviteLocationInputCountry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *InviteLocationInput) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableInviteLocationInputCountry and assigns it to the Country field.
func (o *InviteLocationInput) SetCountry(v InviteLocationInputCountry) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *InviteLocationInput) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *InviteLocationInput) UnsetCountry() {
	o.Country.Unset()
}

// GetFormattedAddress returns the FormattedAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetFormattedAddress() InviteLocationInputCountry {
	if o == nil || IsNil(o.FormattedAddress.Get()) {
		var ret InviteLocationInputCountry
		return ret
	}
	return *o.FormattedAddress.Get()
}

// GetFormattedAddressOk returns a tuple with the FormattedAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetFormattedAddressOk() (*InviteLocationInputCountry, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormattedAddress.Get(), o.FormattedAddress.IsSet()
}

// HasFormattedAddress returns a boolean if a field has been set.
func (o *InviteLocationInput) HasFormattedAddress() bool {
	if o != nil && o.FormattedAddress.IsSet() {
		return true
	}

	return false
}

// SetFormattedAddress gets a reference to the given NullableInviteLocationInputCountry and assigns it to the FormattedAddress field.
func (o *InviteLocationInput) SetFormattedAddress(v InviteLocationInputCountry) {
	o.FormattedAddress.Set(&v)
}

// SetFormattedAddressNil sets the value for FormattedAddress to be an explicit nil
func (o *InviteLocationInput) SetFormattedAddressNil() {
	o.FormattedAddress.Set(nil)
}

// UnsetFormattedAddress ensures that no value is present for FormattedAddress, not even an explicit nil
func (o *InviteLocationInput) UnsetFormattedAddress() {
	o.FormattedAddress.Unset()
}

// GetKind returns the Kind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetKind() LocationKind {
	if o == nil || IsNil(o.Kind.Get()) {
		var ret LocationKind
		return ret
	}
	return *o.Kind.Get()
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetKindOk() (*LocationKind, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kind.Get(), o.Kind.IsSet()
}

// HasKind returns a boolean if a field has been set.
func (o *InviteLocationInput) HasKind() bool {
	if o != nil && o.Kind.IsSet() {
		return true
	}

	return false
}

// SetKind gets a reference to the given NullableLocationKind and assigns it to the Kind field.
func (o *InviteLocationInput) SetKind(v LocationKind) {
	o.Kind.Set(&v)
}

// SetKindNil sets the value for Kind to be an explicit nil
func (o *InviteLocationInput) SetKindNil() {
	o.Kind.Set(nil)
}

// UnsetKind ensures that no value is present for Kind, not even an explicit nil
func (o *InviteLocationInput) UnsetKind() {
	o.Kind.Unset()
}

// GetLat returns the Lat field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetLat() float64 {
	if o == nil || IsNil(o.Lat.Get()) {
		var ret float64
		return ret
	}
	return *o.Lat.Get()
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetLatOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lat.Get(), o.Lat.IsSet()
}

// HasLat returns a boolean if a field has been set.
func (o *InviteLocationInput) HasLat() bool {
	if o != nil && o.Lat.IsSet() {
		return true
	}

	return false
}

// SetLat gets a reference to the given NullableFloat64 and assigns it to the Lat field.
func (o *InviteLocationInput) SetLat(v float64) {
	o.Lat.Set(&v)
}

// SetLatNil sets the value for Lat to be an explicit nil
func (o *InviteLocationInput) SetLatNil() {
	o.Lat.Set(nil)
}

// UnsetLat ensures that no value is present for Lat, not even an explicit nil
func (o *InviteLocationInput) UnsetLat() {
	o.Lat.Unset()
}

// GetLng returns the Lng field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetLng() float64 {
	if o == nil || IsNil(o.Lng.Get()) {
		var ret float64
		return ret
	}
	return *o.Lng.Get()
}

// GetLngOk returns a tuple with the Lng field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetLngOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lng.Get(), o.Lng.IsSet()
}

// HasLng returns a boolean if a field has been set.
func (o *InviteLocationInput) HasLng() bool {
	if o != nil && o.Lng.IsSet() {
		return true
	}

	return false
}

// SetLng gets a reference to the given NullableFloat64 and assigns it to the Lng field.
func (o *InviteLocationInput) SetLng(v float64) {
	o.Lng.Set(&v)
}

// SetLngNil sets the value for Lng to be an explicit nil
func (o *InviteLocationInput) SetLngNil() {
	o.Lng.Set(nil)
}

// UnsetLng ensures that no value is present for Lng, not even an explicit nil
func (o *InviteLocationInput) UnsetLng() {
	o.Lng.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetNotes() InviteLocationInputCountry {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret InviteLocationInputCountry
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetNotesOk() (*InviteLocationInputCountry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *InviteLocationInput) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableInviteLocationInputCountry and assigns it to the Notes field.
func (o *InviteLocationInput) SetNotes(v InviteLocationInputCountry) {
	o.Notes.Set(&v)
}

// SetNotesNil sets the value for Notes to be an explicit nil
func (o *InviteLocationInput) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *InviteLocationInput) UnsetNotes() {
	o.Notes.Unset()
}

// GetPlaceId returns the PlaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteLocationInput) GetPlaceId() string {
	if o == nil || IsNil(o.PlaceId.Get()) {
		var ret string
		return ret
	}
	return *o.PlaceId.Get()
}

// GetPlaceIdOk returns a tuple with the PlaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteLocationInput) GetPlaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlaceId.Get(), o.PlaceId.IsSet()
}

// HasPlaceId returns a boolean if a field has been set.
func (o *InviteLocationInput) HasPlaceId() bool {
	if o != nil && o.PlaceId.IsSet() {
		return true
	}

	return false
}

// SetPlaceId gets a reference to the given NullableString and assigns it to the PlaceId field.
func (o *InviteLocationInput) SetPlaceId(v string) {
	o.PlaceId.Set(&v)
}

// SetPlaceIdNil sets the value for PlaceId to be an explicit nil
func (o *InviteLocationInput) SetPlaceIdNil() {
	o.PlaceId.Set(nil)
}

// UnsetPlaceId ensures that no value is present for PlaceId, not even an explicit nil
func (o *InviteLocationInput) UnsetPlaceId() {
	o.PlaceId.Unset()
}

func (o InviteLocationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.FormattedAddress.IsSet() {
		toSerialize["formatted_address"] = o.FormattedAddress.Get()
	}
	if o.Kind.IsSet() {
		toSerialize["kind"] = o.Kind.Get()
	}
	if o.Lat.IsSet() {
		toSerialize["lat"] = o.Lat.Get()
	}
	if o.Lng.IsSet() {
		toSerialize["lng"] = o.Lng.Get()
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	if o.PlaceId.IsSet() {
		toSerialize["place_id"] = o.PlaceId.Get()
	}
	return toSerialize, nil
}

type NullableInviteLocationInput struct {
	value *InviteLocationInput
	isSet bool
}

func (v NullableInviteLocationInput) Get() *InviteLocationInput {
	return v.value
}

func (v *NullableInviteLocationInput) Set(val *InviteLocationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteLocationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteLocationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteLocationInput(val *InviteLocationInput) *NullableInviteLocationInput {
	return &NullableInviteLocationInput{value: val, isSet: true}
}

func (v NullableInviteLocationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteLocationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
