/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PublicInviteSessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicInviteSessionResponse{}

// PublicInviteSessionResponse struct for PublicInviteSessionResponse
type PublicInviteSessionResponse struct {
	// Stable per-device guest fingerprint (ULID). Either the one supplied by the client (cookie or `X-Guest-Id`) or a freshly minted one. Echoed so native clients can persist it and send it back via `X-Guest-Id` on subsequent public-access calls. Used only for audit attribution — it confers no access.
	GuestId string `json:"guest_id"`
	// ULID of the invite (= value of the `oa_access_invite` cookie). Echoed in the body so non-browser clients can construct the cookie without relying on a platform cookie jar for `HttpOnly` `Set-Cookie` responses.
	InviteId string `json:"invite_id"`
	Ok       bool   `json:"ok"`
}

type _PublicInviteSessionResponse PublicInviteSessionResponse

// NewPublicInviteSessionResponse instantiates a new PublicInviteSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicInviteSessionResponse(guestId string, inviteId string, ok bool) *PublicInviteSessionResponse {
	this := PublicInviteSessionResponse{}
	this.GuestId = guestId
	this.InviteId = inviteId
	this.Ok = ok
	return &this
}

// NewPublicInviteSessionResponseWithDefaults instantiates a new PublicInviteSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicInviteSessionResponseWithDefaults() *PublicInviteSessionResponse {
	this := PublicInviteSessionResponse{}
	return &this
}

// GetGuestId returns the GuestId field value
func (o *PublicInviteSessionResponse) GetGuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GuestId
}

// GetGuestIdOk returns a tuple with the GuestId field value
// and a boolean to check if the value has been set.
func (o *PublicInviteSessionResponse) GetGuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GuestId, true
}

// SetGuestId sets field value
func (o *PublicInviteSessionResponse) SetGuestId(v string) {
	o.GuestId = v
}

// GetInviteId returns the InviteId field value
func (o *PublicInviteSessionResponse) GetInviteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InviteId
}

// GetInviteIdOk returns a tuple with the InviteId field value
// and a boolean to check if the value has been set.
func (o *PublicInviteSessionResponse) GetInviteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InviteId, true
}

// SetInviteId sets field value
func (o *PublicInviteSessionResponse) SetInviteId(v string) {
	o.InviteId = v
}

// GetOk returns the Ok field value
func (o *PublicInviteSessionResponse) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *PublicInviteSessionResponse) GetOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *PublicInviteSessionResponse) SetOk(v bool) {
	o.Ok = v
}

func (o PublicInviteSessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["guest_id"] = o.GuestId
	toSerialize["invite_id"] = o.InviteId
	toSerialize["ok"] = o.Ok
	return toSerialize, nil
}

func (o *PublicInviteSessionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"guest_id",
		"invite_id",
		"ok",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicInviteSessionResponse := _PublicInviteSessionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicInviteSessionResponse)

	if err != nil {
		return err
	}

	*o = PublicInviteSessionResponse(varPublicInviteSessionResponse)

	return err
}

type NullablePublicInviteSessionResponse struct {
	value *PublicInviteSessionResponse
	isSet bool
}

func (v NullablePublicInviteSessionResponse) Get() *PublicInviteSessionResponse {
	return v.value
}

func (v *NullablePublicInviteSessionResponse) Set(val *PublicInviteSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicInviteSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicInviteSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicInviteSessionResponse(val *PublicInviteSessionResponse) *NullablePublicInviteSessionResponse {
	return &NullablePublicInviteSessionResponse{value: val, isSet: true}
}

func (v NullablePublicInviteSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicInviteSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
