/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MeProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeProfileResponse{}

// MeProfileResponse struct for MeProfileResponse
type MeProfileResponse struct {
	Email          NullableString         `json:"email,omitempty"`
	EmailVerified  bool                   `json:"email_verified"`
	IdpLinks       []IdpLinkResponse      `json:"idp_links"`
	ImageSyncError NullableString         `json:"image_sync_error,omitempty"`
	ImageThumbUrl  NullableString         `json:"image_thumb_url,omitempty"`
	ImageUrl       NullableString         `json:"image_url,omitempty"`
	Locale         NullableString         `json:"locale,omitempty"`
	Name           NullableString         `json:"name,omitempty"`
	Phone          NullableString         `json:"phone,omitempty"`
	PhoneVerified  bool                   `json:"phone_verified"`
	ProfileSources ProfileSourcesResponse `json:"profile_sources"`
}

type _MeProfileResponse MeProfileResponse

// NewMeProfileResponse instantiates a new MeProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeProfileResponse(emailVerified bool, idpLinks []IdpLinkResponse, phoneVerified bool, profileSources ProfileSourcesResponse) *MeProfileResponse {
	this := MeProfileResponse{}
	this.EmailVerified = emailVerified
	this.IdpLinks = idpLinks
	this.PhoneVerified = phoneVerified
	this.ProfileSources = profileSources
	return &this
}

// NewMeProfileResponseWithDefaults instantiates a new MeProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeProfileResponseWithDefaults() *MeProfileResponse {
	this := MeProfileResponse{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *MeProfileResponse) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *MeProfileResponse) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *MeProfileResponse) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *MeProfileResponse) UnsetEmail() {
	o.Email.Unset()
}

// GetEmailVerified returns the EmailVerified field value
func (o *MeProfileResponse) GetEmailVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EmailVerified
}

// GetEmailVerifiedOk returns a tuple with the EmailVerified field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetEmailVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailVerified, true
}

// SetEmailVerified sets field value
func (o *MeProfileResponse) SetEmailVerified(v bool) {
	o.EmailVerified = v
}

// GetIdpLinks returns the IdpLinks field value
func (o *MeProfileResponse) GetIdpLinks() []IdpLinkResponse {
	if o == nil {
		var ret []IdpLinkResponse
		return ret
	}

	return o.IdpLinks
}

// GetIdpLinksOk returns a tuple with the IdpLinks field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetIdpLinksOk() ([]IdpLinkResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.IdpLinks, true
}

// SetIdpLinks sets field value
func (o *MeProfileResponse) SetIdpLinks(v []IdpLinkResponse) {
	o.IdpLinks = v
}

// GetImageSyncError returns the ImageSyncError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetImageSyncError() string {
	if o == nil || IsNil(o.ImageSyncError.Get()) {
		var ret string
		return ret
	}
	return *o.ImageSyncError.Get()
}

// GetImageSyncErrorOk returns a tuple with the ImageSyncError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetImageSyncErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageSyncError.Get(), o.ImageSyncError.IsSet()
}

// HasImageSyncError returns a boolean if a field has been set.
func (o *MeProfileResponse) HasImageSyncError() bool {
	if o != nil && o.ImageSyncError.IsSet() {
		return true
	}

	return false
}

// SetImageSyncError gets a reference to the given NullableString and assigns it to the ImageSyncError field.
func (o *MeProfileResponse) SetImageSyncError(v string) {
	o.ImageSyncError.Set(&v)
}

// SetImageSyncErrorNil sets the value for ImageSyncError to be an explicit nil
func (o *MeProfileResponse) SetImageSyncErrorNil() {
	o.ImageSyncError.Set(nil)
}

// UnsetImageSyncError ensures that no value is present for ImageSyncError, not even an explicit nil
func (o *MeProfileResponse) UnsetImageSyncError() {
	o.ImageSyncError.Unset()
}

// GetImageThumbUrl returns the ImageThumbUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetImageThumbUrl() string {
	if o == nil || IsNil(o.ImageThumbUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ImageThumbUrl.Get()
}

// GetImageThumbUrlOk returns a tuple with the ImageThumbUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetImageThumbUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageThumbUrl.Get(), o.ImageThumbUrl.IsSet()
}

// HasImageThumbUrl returns a boolean if a field has been set.
func (o *MeProfileResponse) HasImageThumbUrl() bool {
	if o != nil && o.ImageThumbUrl.IsSet() {
		return true
	}

	return false
}

// SetImageThumbUrl gets a reference to the given NullableString and assigns it to the ImageThumbUrl field.
func (o *MeProfileResponse) SetImageThumbUrl(v string) {
	o.ImageThumbUrl.Set(&v)
}

// SetImageThumbUrlNil sets the value for ImageThumbUrl to be an explicit nil
func (o *MeProfileResponse) SetImageThumbUrlNil() {
	o.ImageThumbUrl.Set(nil)
}

// UnsetImageThumbUrl ensures that no value is present for ImageThumbUrl, not even an explicit nil
func (o *MeProfileResponse) UnsetImageThumbUrl() {
	o.ImageThumbUrl.Unset()
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *MeProfileResponse) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *MeProfileResponse) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}

// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *MeProfileResponse) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *MeProfileResponse) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *MeProfileResponse) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *MeProfileResponse) SetLocale(v string) {
	o.Locale.Set(&v)
}

// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *MeProfileResponse) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *MeProfileResponse) UnsetLocale() {
	o.Locale.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *MeProfileResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *MeProfileResponse) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *MeProfileResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *MeProfileResponse) UnsetName() {
	o.Name.Unset()
}

// GetPhone returns the Phone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeProfileResponse) GetPhone() string {
	if o == nil || IsNil(o.Phone.Get()) {
		var ret string
		return ret
	}
	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeProfileResponse) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// HasPhone returns a boolean if a field has been set.
func (o *MeProfileResponse) HasPhone() bool {
	if o != nil && o.Phone.IsSet() {
		return true
	}

	return false
}

// SetPhone gets a reference to the given NullableString and assigns it to the Phone field.
func (o *MeProfileResponse) SetPhone(v string) {
	o.Phone.Set(&v)
}

// SetPhoneNil sets the value for Phone to be an explicit nil
func (o *MeProfileResponse) SetPhoneNil() {
	o.Phone.Set(nil)
}

// UnsetPhone ensures that no value is present for Phone, not even an explicit nil
func (o *MeProfileResponse) UnsetPhone() {
	o.Phone.Unset()
}

// GetPhoneVerified returns the PhoneVerified field value
func (o *MeProfileResponse) GetPhoneVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PhoneVerified
}

// GetPhoneVerifiedOk returns a tuple with the PhoneVerified field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetPhoneVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneVerified, true
}

// SetPhoneVerified sets field value
func (o *MeProfileResponse) SetPhoneVerified(v bool) {
	o.PhoneVerified = v
}

// GetProfileSources returns the ProfileSources field value
func (o *MeProfileResponse) GetProfileSources() ProfileSourcesResponse {
	if o == nil {
		var ret ProfileSourcesResponse
		return ret
	}

	return o.ProfileSources
}

// GetProfileSourcesOk returns a tuple with the ProfileSources field value
// and a boolean to check if the value has been set.
func (o *MeProfileResponse) GetProfileSourcesOk() (*ProfileSourcesResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileSources, true
}

// SetProfileSources sets field value
func (o *MeProfileResponse) SetProfileSources(v ProfileSourcesResponse) {
	o.ProfileSources = v
}

func (o MeProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	toSerialize["email_verified"] = o.EmailVerified
	toSerialize["idp_links"] = o.IdpLinks
	if o.ImageSyncError.IsSet() {
		toSerialize["image_sync_error"] = o.ImageSyncError.Get()
	}
	if o.ImageThumbUrl.IsSet() {
		toSerialize["image_thumb_url"] = o.ImageThumbUrl.Get()
	}
	if o.ImageUrl.IsSet() {
		toSerialize["image_url"] = o.ImageUrl.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Phone.IsSet() {
		toSerialize["phone"] = o.Phone.Get()
	}
	toSerialize["phone_verified"] = o.PhoneVerified
	toSerialize["profile_sources"] = o.ProfileSources
	return toSerialize, nil
}

func (o *MeProfileResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email_verified",
		"idp_links",
		"phone_verified",
		"profile_sources",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeProfileResponse := _MeProfileResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeProfileResponse)

	if err != nil {
		return err
	}

	*o = MeProfileResponse(varMeProfileResponse)

	return err
}

type NullableMeProfileResponse struct {
	value *MeProfileResponse
	isSet bool
}

func (v NullableMeProfileResponse) Get() *MeProfileResponse {
	return v.value
}

func (v *NullableMeProfileResponse) Set(val *MeProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMeProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMeProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeProfileResponse(val *MeProfileResponse) *NullableMeProfileResponse {
	return &NullableMeProfileResponse{value: val, isSet: true}
}

func (v NullableMeProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
