/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateAccessPortalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccessPortalResponse{}

// CreateAccessPortalResponse struct for CreateAccessPortalResponse
type CreateAccessPortalResponse struct {
	DeviceExternalId NullableString  `json:"device_external_id,omitempty"`
	Id               string          `json:"id"`
	Name             LocalizedString `json:"name"`
	PublicId         string          `json:"public_id"`
}

type _CreateAccessPortalResponse CreateAccessPortalResponse

// NewCreateAccessPortalResponse instantiates a new CreateAccessPortalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccessPortalResponse(id string, name LocalizedString, publicId string) *CreateAccessPortalResponse {
	this := CreateAccessPortalResponse{}
	this.Id = id
	this.Name = name
	this.PublicId = publicId
	return &this
}

// NewCreateAccessPortalResponseWithDefaults instantiates a new CreateAccessPortalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccessPortalResponseWithDefaults() *CreateAccessPortalResponse {
	this := CreateAccessPortalResponse{}
	return &this
}

// GetDeviceExternalId returns the DeviceExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAccessPortalResponse) GetDeviceExternalId() string {
	if o == nil || IsNil(o.DeviceExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceExternalId.Get()
}

// GetDeviceExternalIdOk returns a tuple with the DeviceExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccessPortalResponse) GetDeviceExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceExternalId.Get(), o.DeviceExternalId.IsSet()
}

// HasDeviceExternalId returns a boolean if a field has been set.
func (o *CreateAccessPortalResponse) HasDeviceExternalId() bool {
	if o != nil && o.DeviceExternalId.IsSet() {
		return true
	}

	return false
}

// SetDeviceExternalId gets a reference to the given NullableString and assigns it to the DeviceExternalId field.
func (o *CreateAccessPortalResponse) SetDeviceExternalId(v string) {
	o.DeviceExternalId.Set(&v)
}

// SetDeviceExternalIdNil sets the value for DeviceExternalId to be an explicit nil
func (o *CreateAccessPortalResponse) SetDeviceExternalIdNil() {
	o.DeviceExternalId.Set(nil)
}

// UnsetDeviceExternalId ensures that no value is present for DeviceExternalId, not even an explicit nil
func (o *CreateAccessPortalResponse) UnsetDeviceExternalId() {
	o.DeviceExternalId.Unset()
}

// GetId returns the Id field value
func (o *CreateAccessPortalResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateAccessPortalResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateAccessPortalResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CreateAccessPortalResponse) GetName() LocalizedString {
	if o == nil {
		var ret LocalizedString
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAccessPortalResponse) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAccessPortalResponse) SetName(v LocalizedString) {
	o.Name = v
}

// GetPublicId returns the PublicId field value
func (o *CreateAccessPortalResponse) GetPublicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value
// and a boolean to check if the value has been set.
func (o *CreateAccessPortalResponse) GetPublicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicId, true
}

// SetPublicId sets field value
func (o *CreateAccessPortalResponse) SetPublicId(v string) {
	o.PublicId = v
}

func (o CreateAccessPortalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DeviceExternalId.IsSet() {
		toSerialize["device_external_id"] = o.DeviceExternalId.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["public_id"] = o.PublicId
	return toSerialize, nil
}

func (o *CreateAccessPortalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"public_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccessPortalResponse := _CreateAccessPortalResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccessPortalResponse)

	if err != nil {
		return err
	}

	*o = CreateAccessPortalResponse(varCreateAccessPortalResponse)

	return err
}

type NullableCreateAccessPortalResponse struct {
	value *CreateAccessPortalResponse
	isSet bool
}

func (v NullableCreateAccessPortalResponse) Get() *CreateAccessPortalResponse {
	return v.value
}

func (v *NullableCreateAccessPortalResponse) Set(val *CreateAccessPortalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessPortalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessPortalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessPortalResponse(val *CreateAccessPortalResponse) *NullableCreateAccessPortalResponse {
	return &NullableCreateAccessPortalResponse{value: val, isSet: true}
}

func (v NullableCreateAccessPortalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessPortalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
