/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// InviteRecurrenceSeriesEnd - How the recurring series ends (from `invite_recurrence`), for admin/public display.
type InviteRecurrenceSeriesEnd struct {
	InviteRecurrenceSeriesEndOneOf  *InviteRecurrenceSeriesEndOneOf
	InviteRecurrenceSeriesEndOneOf1 *InviteRecurrenceSeriesEndOneOf1
	InviteRecurrenceSeriesEndOneOf2 *InviteRecurrenceSeriesEndOneOf2
}

// InviteRecurrenceSeriesEndOneOfAsInviteRecurrenceSeriesEnd is a convenience function that returns InviteRecurrenceSeriesEndOneOf wrapped in InviteRecurrenceSeriesEnd
func InviteRecurrenceSeriesEndOneOfAsInviteRecurrenceSeriesEnd(v *InviteRecurrenceSeriesEndOneOf) InviteRecurrenceSeriesEnd {
	return InviteRecurrenceSeriesEnd{
		InviteRecurrenceSeriesEndOneOf: v,
	}
}

// InviteRecurrenceSeriesEndOneOf1AsInviteRecurrenceSeriesEnd is a convenience function that returns InviteRecurrenceSeriesEndOneOf1 wrapped in InviteRecurrenceSeriesEnd
func InviteRecurrenceSeriesEndOneOf1AsInviteRecurrenceSeriesEnd(v *InviteRecurrenceSeriesEndOneOf1) InviteRecurrenceSeriesEnd {
	return InviteRecurrenceSeriesEnd{
		InviteRecurrenceSeriesEndOneOf1: v,
	}
}

// InviteRecurrenceSeriesEndOneOf2AsInviteRecurrenceSeriesEnd is a convenience function that returns InviteRecurrenceSeriesEndOneOf2 wrapped in InviteRecurrenceSeriesEnd
func InviteRecurrenceSeriesEndOneOf2AsInviteRecurrenceSeriesEnd(v *InviteRecurrenceSeriesEndOneOf2) InviteRecurrenceSeriesEnd {
	return InviteRecurrenceSeriesEnd{
		InviteRecurrenceSeriesEndOneOf2: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *InviteRecurrenceSeriesEnd) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InviteRecurrenceSeriesEndOneOf
	err = newStrictDecoder(data).Decode(&dst.InviteRecurrenceSeriesEndOneOf)
	if err == nil {
		jsonInviteRecurrenceSeriesEndOneOf, _ := json.Marshal(dst.InviteRecurrenceSeriesEndOneOf)
		if string(jsonInviteRecurrenceSeriesEndOneOf) == "{}" { // empty struct
			dst.InviteRecurrenceSeriesEndOneOf = nil
		} else {
			if err = validator.Validate(dst.InviteRecurrenceSeriesEndOneOf); err != nil {
				dst.InviteRecurrenceSeriesEndOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.InviteRecurrenceSeriesEndOneOf = nil
	}

	// try to unmarshal data into InviteRecurrenceSeriesEndOneOf1
	err = newStrictDecoder(data).Decode(&dst.InviteRecurrenceSeriesEndOneOf1)
	if err == nil {
		jsonInviteRecurrenceSeriesEndOneOf1, _ := json.Marshal(dst.InviteRecurrenceSeriesEndOneOf1)
		if string(jsonInviteRecurrenceSeriesEndOneOf1) == "{}" { // empty struct
			dst.InviteRecurrenceSeriesEndOneOf1 = nil
		} else {
			if err = validator.Validate(dst.InviteRecurrenceSeriesEndOneOf1); err != nil {
				dst.InviteRecurrenceSeriesEndOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.InviteRecurrenceSeriesEndOneOf1 = nil
	}

	// try to unmarshal data into InviteRecurrenceSeriesEndOneOf2
	err = newStrictDecoder(data).Decode(&dst.InviteRecurrenceSeriesEndOneOf2)
	if err == nil {
		jsonInviteRecurrenceSeriesEndOneOf2, _ := json.Marshal(dst.InviteRecurrenceSeriesEndOneOf2)
		if string(jsonInviteRecurrenceSeriesEndOneOf2) == "{}" { // empty struct
			dst.InviteRecurrenceSeriesEndOneOf2 = nil
		} else {
			if err = validator.Validate(dst.InviteRecurrenceSeriesEndOneOf2); err != nil {
				dst.InviteRecurrenceSeriesEndOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.InviteRecurrenceSeriesEndOneOf2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InviteRecurrenceSeriesEndOneOf = nil
		dst.InviteRecurrenceSeriesEndOneOf1 = nil
		dst.InviteRecurrenceSeriesEndOneOf2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InviteRecurrenceSeriesEnd)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(InviteRecurrenceSeriesEnd)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InviteRecurrenceSeriesEnd) MarshalJSON() ([]byte, error) {
	if src.InviteRecurrenceSeriesEndOneOf != nil {
		return json.Marshal(&src.InviteRecurrenceSeriesEndOneOf)
	}

	if src.InviteRecurrenceSeriesEndOneOf1 != nil {
		return json.Marshal(&src.InviteRecurrenceSeriesEndOneOf1)
	}

	if src.InviteRecurrenceSeriesEndOneOf2 != nil {
		return json.Marshal(&src.InviteRecurrenceSeriesEndOneOf2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InviteRecurrenceSeriesEnd) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.InviteRecurrenceSeriesEndOneOf != nil {
		return obj.InviteRecurrenceSeriesEndOneOf
	}

	if obj.InviteRecurrenceSeriesEndOneOf1 != nil {
		return obj.InviteRecurrenceSeriesEndOneOf1
	}

	if obj.InviteRecurrenceSeriesEndOneOf2 != nil {
		return obj.InviteRecurrenceSeriesEndOneOf2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj InviteRecurrenceSeriesEnd) GetActualInstanceValue() interface{} {
	if obj.InviteRecurrenceSeriesEndOneOf != nil {
		return *obj.InviteRecurrenceSeriesEndOneOf
	}

	if obj.InviteRecurrenceSeriesEndOneOf1 != nil {
		return *obj.InviteRecurrenceSeriesEndOneOf1
	}

	if obj.InviteRecurrenceSeriesEndOneOf2 != nil {
		return *obj.InviteRecurrenceSeriesEndOneOf2
	}

	// all schemas are nil
	return nil
}

type NullableInviteRecurrenceSeriesEnd struct {
	value *InviteRecurrenceSeriesEnd
	isSet bool
}

func (v NullableInviteRecurrenceSeriesEnd) Get() *InviteRecurrenceSeriesEnd {
	return v.value
}

func (v *NullableInviteRecurrenceSeriesEnd) Set(val *InviteRecurrenceSeriesEnd) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteRecurrenceSeriesEnd) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteRecurrenceSeriesEnd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteRecurrenceSeriesEnd(val *InviteRecurrenceSeriesEnd) *NullableInviteRecurrenceSeriesEnd {
	return &NullableInviteRecurrenceSeriesEnd{value: val, isSet: true}
}

func (v NullableInviteRecurrenceSeriesEnd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteRecurrenceSeriesEnd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
