/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AcceptEulaResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcceptEulaResponse{}

// AcceptEulaResponse Response after accepting EULA
type AcceptEulaResponse struct {
	Message string `json:"message"`
	UserId  string `json:"user_id"`
	// Personal Workspace org id auto-created on self-signup. Absent for existing users being linked to Kratos credentials.
	WorkspaceId NullableString `json:"workspace_id,omitempty"`
}

type _AcceptEulaResponse AcceptEulaResponse

// NewAcceptEulaResponse instantiates a new AcceptEulaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptEulaResponse(message string, userId string) *AcceptEulaResponse {
	this := AcceptEulaResponse{}
	this.Message = message
	this.UserId = userId
	return &this
}

// NewAcceptEulaResponseWithDefaults instantiates a new AcceptEulaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptEulaResponseWithDefaults() *AcceptEulaResponse {
	this := AcceptEulaResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *AcceptEulaResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AcceptEulaResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AcceptEulaResponse) SetMessage(v string) {
	o.Message = v
}

// GetUserId returns the UserId field value
func (o *AcceptEulaResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AcceptEulaResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AcceptEulaResponse) SetUserId(v string) {
	o.UserId = v
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AcceptEulaResponse) GetWorkspaceId() string {
	if o == nil || IsNil(o.WorkspaceId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkspaceId.Get()
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AcceptEulaResponse) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceId.Get(), o.WorkspaceId.IsSet()
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *AcceptEulaResponse) HasWorkspaceId() bool {
	if o != nil && o.WorkspaceId.IsSet() {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given NullableString and assigns it to the WorkspaceId field.
func (o *AcceptEulaResponse) SetWorkspaceId(v string) {
	o.WorkspaceId.Set(&v)
}

// SetWorkspaceIdNil sets the value for WorkspaceId to be an explicit nil
func (o *AcceptEulaResponse) SetWorkspaceIdNil() {
	o.WorkspaceId.Set(nil)
}

// UnsetWorkspaceId ensures that no value is present for WorkspaceId, not even an explicit nil
func (o *AcceptEulaResponse) UnsetWorkspaceId() {
	o.WorkspaceId.Unset()
}

func (o AcceptEulaResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["user_id"] = o.UserId
	if o.WorkspaceId.IsSet() {
		toSerialize["workspace_id"] = o.WorkspaceId.Get()
	}
	return toSerialize, nil
}

func (o *AcceptEulaResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAcceptEulaResponse := _AcceptEulaResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAcceptEulaResponse)

	if err != nil {
		return err
	}

	*o = AcceptEulaResponse(varAcceptEulaResponse)

	return err
}

type NullableAcceptEulaResponse struct {
	value *AcceptEulaResponse
	isSet bool
}

func (v NullableAcceptEulaResponse) Get() *AcceptEulaResponse {
	return v.value
}

func (v *NullableAcceptEulaResponse) Set(val *AcceptEulaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptEulaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptEulaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptEulaResponse(val *AcceptEulaResponse) *NullableAcceptEulaResponse {
	return &NullableAcceptEulaResponse{value: val, isSet: true}
}

func (v NullableAcceptEulaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptEulaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
