/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApartmentFloorListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApartmentFloorListResponse{}

// ApartmentFloorListResponse Distinct apartment floors for a directory device (efficient SQL).
type ApartmentFloorListResponse struct {
	Floors []ApartmentFloorSummary `json:"floors"`
}

type _ApartmentFloorListResponse ApartmentFloorListResponse

// NewApartmentFloorListResponse instantiates a new ApartmentFloorListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApartmentFloorListResponse(floors []ApartmentFloorSummary) *ApartmentFloorListResponse {
	this := ApartmentFloorListResponse{}
	this.Floors = floors
	return &this
}

// NewApartmentFloorListResponseWithDefaults instantiates a new ApartmentFloorListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApartmentFloorListResponseWithDefaults() *ApartmentFloorListResponse {
	this := ApartmentFloorListResponse{}
	return &this
}

// GetFloors returns the Floors field value
func (o *ApartmentFloorListResponse) GetFloors() []ApartmentFloorSummary {
	if o == nil {
		var ret []ApartmentFloorSummary
		return ret
	}

	return o.Floors
}

// GetFloorsOk returns a tuple with the Floors field value
// and a boolean to check if the value has been set.
func (o *ApartmentFloorListResponse) GetFloorsOk() ([]ApartmentFloorSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Floors, true
}

// SetFloors sets field value
func (o *ApartmentFloorListResponse) SetFloors(v []ApartmentFloorSummary) {
	o.Floors = v
}

func (o ApartmentFloorListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["floors"] = o.Floors
	return toSerialize, nil
}

func (o *ApartmentFloorListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"floors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApartmentFloorListResponse := _ApartmentFloorListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApartmentFloorListResponse)

	if err != nil {
		return err
	}

	*o = ApartmentFloorListResponse(varApartmentFloorListResponse)

	return err
}

type NullableApartmentFloorListResponse struct {
	value *ApartmentFloorListResponse
	isSet bool
}

func (v NullableApartmentFloorListResponse) Get() *ApartmentFloorListResponse {
	return v.value
}

func (v *NullableApartmentFloorListResponse) Set(val *ApartmentFloorListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApartmentFloorListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApartmentFloorListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApartmentFloorListResponse(val *ApartmentFloorListResponse) *NullableApartmentFloorListResponse {
	return &NullableApartmentFloorListResponse{value: val, isSet: true}
}

func (v NullableApartmentFloorListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApartmentFloorListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
