/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DegradationStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DegradationStatus{}

// DegradationStatus Full degradation snapshot for an org. Powers the dashboard panel + non-admin friction.
type DegradationStatus struct {
	DegradationLevel  float32           `json:"degradation_level"`
	Flagged           []FlaggedResource `json:"flagged"`
	OrgId             NullableString    `json:"org_id"`
	OverCapacity      bool              `json:"over_capacity"`
	OverCapacitySince NullableString    `json:"over_capacity_since,omitempty"`
	Overages          []KeyOverage      `json:"overages"`
	SelectionPolicy   SelectionPolicy   `json:"selection_policy"`
	Stage             DegradationStage  `json:"stage"`
}

type _DegradationStatus DegradationStatus

// NewDegradationStatus instantiates a new DegradationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDegradationStatus(degradationLevel float32, flagged []FlaggedResource, orgId NullableString, overCapacity bool, overages []KeyOverage, selectionPolicy SelectionPolicy, stage DegradationStage) *DegradationStatus {
	this := DegradationStatus{}
	this.DegradationLevel = degradationLevel
	this.Flagged = flagged
	this.OrgId = orgId
	this.OverCapacity = overCapacity
	this.Overages = overages
	this.SelectionPolicy = selectionPolicy
	this.Stage = stage
	return &this
}

// NewDegradationStatusWithDefaults instantiates a new DegradationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDegradationStatusWithDefaults() *DegradationStatus {
	this := DegradationStatus{}
	return &this
}

// GetDegradationLevel returns the DegradationLevel field value
func (o *DegradationStatus) GetDegradationLevel() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DegradationLevel
}

// GetDegradationLevelOk returns a tuple with the DegradationLevel field value
// and a boolean to check if the value has been set.
func (o *DegradationStatus) GetDegradationLevelOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DegradationLevel, true
}

// SetDegradationLevel sets field value
func (o *DegradationStatus) SetDegradationLevel(v float32) {
	o.DegradationLevel = v
}

// GetFlagged returns the Flagged field value
func (o *DegradationStatus) GetFlagged() []FlaggedResource {
	if o == nil {
		var ret []FlaggedResource
		return ret
	}

	return o.Flagged
}

// GetFlaggedOk returns a tuple with the Flagged field value
// and a boolean to check if the value has been set.
func (o *DegradationStatus) GetFlaggedOk() ([]FlaggedResource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Flagged, true
}

// SetFlagged sets field value
func (o *DegradationStatus) SetFlagged(v []FlaggedResource) {
	o.Flagged = v
}

// GetOrgId returns the OrgId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DegradationStatus) GetOrgId() string {
	if o == nil || o.OrgId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DegradationStatus) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// SetOrgId sets field value
func (o *DegradationStatus) SetOrgId(v string) {
	o.OrgId.Set(&v)
}

// GetOverCapacity returns the OverCapacity field value
func (o *DegradationStatus) GetOverCapacity() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OverCapacity
}

// GetOverCapacityOk returns a tuple with the OverCapacity field value
// and a boolean to check if the value has been set.
func (o *DegradationStatus) GetOverCapacityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverCapacity, true
}

// SetOverCapacity sets field value
func (o *DegradationStatus) SetOverCapacity(v bool) {
	o.OverCapacity = v
}

// GetOverCapacitySince returns the OverCapacitySince field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DegradationStatus) GetOverCapacitySince() string {
	if o == nil || IsNil(o.OverCapacitySince.Get()) {
		var ret string
		return ret
	}
	return *o.OverCapacitySince.Get()
}

// GetOverCapacitySinceOk returns a tuple with the OverCapacitySince field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DegradationStatus) GetOverCapacitySinceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OverCapacitySince.Get(), o.OverCapacitySince.IsSet()
}

// HasOverCapacitySince returns a boolean if a field has been set.
func (o *DegradationStatus) HasOverCapacitySince() bool {
	if o != nil && o.OverCapacitySince.IsSet() {
		return true
	}

	return false
}

// SetOverCapacitySince gets a reference to the given NullableString and assigns it to the OverCapacitySince field.
func (o *DegradationStatus) SetOverCapacitySince(v string) {
	o.OverCapacitySince.Set(&v)
}

// SetOverCapacitySinceNil sets the value for OverCapacitySince to be an explicit nil
func (o *DegradationStatus) SetOverCapacitySinceNil() {
	o.OverCapacitySince.Set(nil)
}

// UnsetOverCapacitySince ensures that no value is present for OverCapacitySince, not even an explicit nil
func (o *DegradationStatus) UnsetOverCapacitySince() {
	o.OverCapacitySince.Unset()
}

// GetOverages returns the Overages field value
func (o *DegradationStatus) GetOverages() []KeyOverage {
	if o == nil {
		var ret []KeyOverage
		return ret
	}

	return o.Overages
}

// GetOveragesOk returns a tuple with the Overages field value
// and a boolean to check if the value has been set.
func (o *DegradationStatus) GetOveragesOk() ([]KeyOverage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Overages, true
}

// SetOverages sets field value
func (o *DegradationStatus) SetOverages(v []KeyOverage) {
	o.Overages = v
}

// GetSelectionPolicy returns the SelectionPolicy field value
func (o *DegradationStatus) GetSelectionPolicy() SelectionPolicy {
	if o == nil {
		var ret SelectionPolicy
		return ret
	}

	return o.SelectionPolicy
}

// GetSelectionPolicyOk returns a tuple with the SelectionPolicy field value
// and a boolean to check if the value has been set.
func (o *DegradationStatus) GetSelectionPolicyOk() (*SelectionPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectionPolicy, true
}

// SetSelectionPolicy sets field value
func (o *DegradationStatus) SetSelectionPolicy(v SelectionPolicy) {
	o.SelectionPolicy = v
}

// GetStage returns the Stage field value
func (o *DegradationStatus) GetStage() DegradationStage {
	if o == nil {
		var ret DegradationStage
		return ret
	}

	return o.Stage
}

// GetStageOk returns a tuple with the Stage field value
// and a boolean to check if the value has been set.
func (o *DegradationStatus) GetStageOk() (*DegradationStage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stage, true
}

// SetStage sets field value
func (o *DegradationStatus) SetStage(v DegradationStage) {
	o.Stage = v
}

func (o DegradationStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["degradation_level"] = o.DegradationLevel
	toSerialize["flagged"] = o.Flagged
	toSerialize["org_id"] = o.OrgId.Get()
	toSerialize["over_capacity"] = o.OverCapacity
	if o.OverCapacitySince.IsSet() {
		toSerialize["over_capacity_since"] = o.OverCapacitySince.Get()
	}
	toSerialize["overages"] = o.Overages
	toSerialize["selection_policy"] = o.SelectionPolicy
	toSerialize["stage"] = o.Stage
	return toSerialize, nil
}

func (o *DegradationStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"degradation_level",
		"flagged",
		"org_id",
		"over_capacity",
		"overages",
		"selection_policy",
		"stage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDegradationStatus := _DegradationStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDegradationStatus)

	if err != nil {
		return err
	}

	*o = DegradationStatus(varDegradationStatus)

	return err
}

type NullableDegradationStatus struct {
	value *DegradationStatus
	isSet bool
}

func (v NullableDegradationStatus) Get() *DegradationStatus {
	return v.value
}

func (v *NullableDegradationStatus) Set(val *DegradationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDegradationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDegradationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDegradationStatus(val *DegradationStatus) *NullableDegradationStatus {
	return &NullableDegradationStatus{value: val, isSet: true}
}

func (v NullableDegradationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDegradationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
