/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MePushVapidPublicKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MePushVapidPublicKeyResponse{}

// MePushVapidPublicKeyResponse struct for MePushVapidPublicKeyResponse
type MePushVapidPublicKeyResponse struct {
	PublicKey string `json:"public_key"`
}

type _MePushVapidPublicKeyResponse MePushVapidPublicKeyResponse

// NewMePushVapidPublicKeyResponse instantiates a new MePushVapidPublicKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMePushVapidPublicKeyResponse(publicKey string) *MePushVapidPublicKeyResponse {
	this := MePushVapidPublicKeyResponse{}
	this.PublicKey = publicKey
	return &this
}

// NewMePushVapidPublicKeyResponseWithDefaults instantiates a new MePushVapidPublicKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMePushVapidPublicKeyResponseWithDefaults() *MePushVapidPublicKeyResponse {
	this := MePushVapidPublicKeyResponse{}
	return &this
}

// GetPublicKey returns the PublicKey field value
func (o *MePushVapidPublicKeyResponse) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *MePushVapidPublicKeyResponse) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *MePushVapidPublicKeyResponse) SetPublicKey(v string) {
	o.PublicKey = v
}

func (o MePushVapidPublicKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public_key"] = o.PublicKey
	return toSerialize, nil
}

func (o *MePushVapidPublicKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMePushVapidPublicKeyResponse := _MePushVapidPublicKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMePushVapidPublicKeyResponse)

	if err != nil {
		return err
	}

	*o = MePushVapidPublicKeyResponse(varMePushVapidPublicKeyResponse)

	return err
}

type NullableMePushVapidPublicKeyResponse struct {
	value *MePushVapidPublicKeyResponse
	isSet bool
}

func (v NullableMePushVapidPublicKeyResponse) Get() *MePushVapidPublicKeyResponse {
	return v.value
}

func (v *NullableMePushVapidPublicKeyResponse) Set(val *MePushVapidPublicKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMePushVapidPublicKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMePushVapidPublicKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMePushVapidPublicKeyResponse(val *MePushVapidPublicKeyResponse) *NullableMePushVapidPublicKeyResponse {
	return &NullableMePushVapidPublicKeyResponse{value: val, isSet: true}
}

func (v NullableMePushVapidPublicKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMePushVapidPublicKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
