/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateZoneRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateZoneRequest{}

// CreateZoneRequest struct for CreateZoneRequest
type CreateZoneRequest struct {
	ExternalId    NullableString  `json:"external_id,omitempty"`
	IntegrationId string          `json:"integration_id"`
	Name          LocalizedString `json:"name"`
	ParentZoneId  NullableString  `json:"parent_zone_id,omitempty"`
}

type _CreateZoneRequest CreateZoneRequest

// NewCreateZoneRequest instantiates a new CreateZoneRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateZoneRequest(integrationId string, name LocalizedString) *CreateZoneRequest {
	this := CreateZoneRequest{}
	this.IntegrationId = integrationId
	this.Name = name
	return &this
}

// NewCreateZoneRequestWithDefaults instantiates a new CreateZoneRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateZoneRequestWithDefaults() *CreateZoneRequest {
	this := CreateZoneRequest{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateZoneRequest) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateZoneRequest) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *CreateZoneRequest) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *CreateZoneRequest) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *CreateZoneRequest) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *CreateZoneRequest) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetIntegrationId returns the IntegrationId field value
func (o *CreateZoneRequest) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *CreateZoneRequest) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *CreateZoneRequest) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetName returns the Name field value
func (o *CreateZoneRequest) GetName() LocalizedString {
	if o == nil {
		var ret LocalizedString
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateZoneRequest) GetNameOk() (*LocalizedString, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateZoneRequest) SetName(v LocalizedString) {
	o.Name = v
}

// GetParentZoneId returns the ParentZoneId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateZoneRequest) GetParentZoneId() string {
	if o == nil || IsNil(o.ParentZoneId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentZoneId.Get()
}

// GetParentZoneIdOk returns a tuple with the ParentZoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateZoneRequest) GetParentZoneIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentZoneId.Get(), o.ParentZoneId.IsSet()
}

// HasParentZoneId returns a boolean if a field has been set.
func (o *CreateZoneRequest) HasParentZoneId() bool {
	if o != nil && o.ParentZoneId.IsSet() {
		return true
	}

	return false
}

// SetParentZoneId gets a reference to the given NullableString and assigns it to the ParentZoneId field.
func (o *CreateZoneRequest) SetParentZoneId(v string) {
	o.ParentZoneId.Set(&v)
}

// SetParentZoneIdNil sets the value for ParentZoneId to be an explicit nil
func (o *CreateZoneRequest) SetParentZoneIdNil() {
	o.ParentZoneId.Set(nil)
}

// UnsetParentZoneId ensures that no value is present for ParentZoneId, not even an explicit nil
func (o *CreateZoneRequest) UnsetParentZoneId() {
	o.ParentZoneId.Unset()
}

func (o CreateZoneRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ExternalId.IsSet() {
		toSerialize["external_id"] = o.ExternalId.Get()
	}
	toSerialize["integration_id"] = o.IntegrationId
	toSerialize["name"] = o.Name
	if o.ParentZoneId.IsSet() {
		toSerialize["parent_zone_id"] = o.ParentZoneId.Get()
	}
	return toSerialize, nil
}

func (o *CreateZoneRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"integration_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateZoneRequest := _CreateZoneRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateZoneRequest)

	if err != nil {
		return err
	}

	*o = CreateZoneRequest(varCreateZoneRequest)

	return err
}

type NullableCreateZoneRequest struct {
	value *CreateZoneRequest
	isSet bool
}

func (v NullableCreateZoneRequest) Get() *CreateZoneRequest {
	return v.value
}

func (v *NullableCreateZoneRequest) Set(val *CreateZoneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateZoneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateZoneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateZoneRequest(val *CreateZoneRequest) *NullableCreateZoneRequest {
	return &NullableCreateZoneRequest{value: val, isSet: true}
}

func (v NullableCreateZoneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateZoneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
