/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InvitationSiteAccessDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvitationSiteAccessDto{}

// InvitationSiteAccessDto struct for InvitationSiteAccessDto
type InvitationSiteAccessDto struct {
	IntegrationId NullableString                 `json:"integration_id"`
	Listing       NullableInvitationListingGrant `json:"listing,omitempty"`
	Role          NullableString                 `json:"role"`
}

type _InvitationSiteAccessDto InvitationSiteAccessDto

// NewInvitationSiteAccessDto instantiates a new InvitationSiteAccessDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationSiteAccessDto(integrationId NullableString, role NullableString) *InvitationSiteAccessDto {
	this := InvitationSiteAccessDto{}
	this.IntegrationId = integrationId
	this.Role = role
	return &this
}

// NewInvitationSiteAccessDtoWithDefaults instantiates a new InvitationSiteAccessDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationSiteAccessDtoWithDefaults() *InvitationSiteAccessDto {
	this := InvitationSiteAccessDto{}
	return &this
}

// GetIntegrationId returns the IntegrationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *InvitationSiteAccessDto) GetIntegrationId() string {
	if o == nil || o.IntegrationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.IntegrationId.Get()
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvitationSiteAccessDto) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationId.Get(), o.IntegrationId.IsSet()
}

// SetIntegrationId sets field value
func (o *InvitationSiteAccessDto) SetIntegrationId(v string) {
	o.IntegrationId.Set(&v)
}

// GetListing returns the Listing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvitationSiteAccessDto) GetListing() InvitationListingGrant {
	if o == nil || IsNil(o.Listing.Get()) {
		var ret InvitationListingGrant
		return ret
	}
	return *o.Listing.Get()
}

// GetListingOk returns a tuple with the Listing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvitationSiteAccessDto) GetListingOk() (*InvitationListingGrant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Listing.Get(), o.Listing.IsSet()
}

// HasListing returns a boolean if a field has been set.
func (o *InvitationSiteAccessDto) HasListing() bool {
	if o != nil && o.Listing.IsSet() {
		return true
	}

	return false
}

// SetListing gets a reference to the given NullableInvitationListingGrant and assigns it to the Listing field.
func (o *InvitationSiteAccessDto) SetListing(v InvitationListingGrant) {
	o.Listing.Set(&v)
}

// SetListingNil sets the value for Listing to be an explicit nil
func (o *InvitationSiteAccessDto) SetListingNil() {
	o.Listing.Set(nil)
}

// UnsetListing ensures that no value is present for Listing, not even an explicit nil
func (o *InvitationSiteAccessDto) UnsetListing() {
	o.Listing.Unset()
}

// GetRole returns the Role field value
// If the value is explicit nil, the zero value for string will be returned
func (o *InvitationSiteAccessDto) GetRole() string {
	if o == nil || o.Role.Get() == nil {
		var ret string
		return ret
	}

	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvitationSiteAccessDto) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// SetRole sets field value
func (o *InvitationSiteAccessDto) SetRole(v string) {
	o.Role.Set(&v)
}

func (o InvitationSiteAccessDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["integration_id"] = o.IntegrationId.Get()
	if o.Listing.IsSet() {
		toSerialize["listing"] = o.Listing.Get()
	}
	toSerialize["role"] = o.Role.Get()
	return toSerialize, nil
}

func (o *InvitationSiteAccessDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"integration_id",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvitationSiteAccessDto := _InvitationSiteAccessDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvitationSiteAccessDto)

	if err != nil {
		return err
	}

	*o = InvitationSiteAccessDto(varInvitationSiteAccessDto)

	return err
}

type NullableInvitationSiteAccessDto struct {
	value *InvitationSiteAccessDto
	isSet bool
}

func (v NullableInvitationSiteAccessDto) Get() *InvitationSiteAccessDto {
	return v.value
}

func (v *NullableInvitationSiteAccessDto) Set(val *InvitationSiteAccessDto) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationSiteAccessDto) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationSiteAccessDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationSiteAccessDto(val *InvitationSiteAccessDto) *NullableInvitationSiteAccessDto {
	return &NullableInvitationSiteAccessDto{value: val, isSet: true}
}

func (v NullableInvitationSiteAccessDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationSiteAccessDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
