/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WaveshareConnectionConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WaveshareConnectionConfig{}

// WaveshareConnectionConfig struct for WaveshareConnectionConfig
type WaveshareConnectionConfig struct {
	MqttClientId       string `json:"mqtt_client_id"`
	MqttPassword       string `json:"mqtt_password"`
	MqttPublishTopic   string `json:"mqtt_publish_topic"`
	MqttSubscribeTopic string `json:"mqtt_subscribe_topic"`
	MqttUsername       string `json:"mqtt_username"`
}

type _WaveshareConnectionConfig WaveshareConnectionConfig

// NewWaveshareConnectionConfig instantiates a new WaveshareConnectionConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWaveshareConnectionConfig(mqttClientId string, mqttPassword string, mqttPublishTopic string, mqttSubscribeTopic string, mqttUsername string) *WaveshareConnectionConfig {
	this := WaveshareConnectionConfig{}
	this.MqttClientId = mqttClientId
	this.MqttPassword = mqttPassword
	this.MqttPublishTopic = mqttPublishTopic
	this.MqttSubscribeTopic = mqttSubscribeTopic
	this.MqttUsername = mqttUsername
	return &this
}

// NewWaveshareConnectionConfigWithDefaults instantiates a new WaveshareConnectionConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWaveshareConnectionConfigWithDefaults() *WaveshareConnectionConfig {
	this := WaveshareConnectionConfig{}
	return &this
}

// GetMqttClientId returns the MqttClientId field value
func (o *WaveshareConnectionConfig) GetMqttClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MqttClientId
}

// GetMqttClientIdOk returns a tuple with the MqttClientId field value
// and a boolean to check if the value has been set.
func (o *WaveshareConnectionConfig) GetMqttClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MqttClientId, true
}

// SetMqttClientId sets field value
func (o *WaveshareConnectionConfig) SetMqttClientId(v string) {
	o.MqttClientId = v
}

// GetMqttPassword returns the MqttPassword field value
func (o *WaveshareConnectionConfig) GetMqttPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MqttPassword
}

// GetMqttPasswordOk returns a tuple with the MqttPassword field value
// and a boolean to check if the value has been set.
func (o *WaveshareConnectionConfig) GetMqttPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MqttPassword, true
}

// SetMqttPassword sets field value
func (o *WaveshareConnectionConfig) SetMqttPassword(v string) {
	o.MqttPassword = v
}

// GetMqttPublishTopic returns the MqttPublishTopic field value
func (o *WaveshareConnectionConfig) GetMqttPublishTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MqttPublishTopic
}

// GetMqttPublishTopicOk returns a tuple with the MqttPublishTopic field value
// and a boolean to check if the value has been set.
func (o *WaveshareConnectionConfig) GetMqttPublishTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MqttPublishTopic, true
}

// SetMqttPublishTopic sets field value
func (o *WaveshareConnectionConfig) SetMqttPublishTopic(v string) {
	o.MqttPublishTopic = v
}

// GetMqttSubscribeTopic returns the MqttSubscribeTopic field value
func (o *WaveshareConnectionConfig) GetMqttSubscribeTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MqttSubscribeTopic
}

// GetMqttSubscribeTopicOk returns a tuple with the MqttSubscribeTopic field value
// and a boolean to check if the value has been set.
func (o *WaveshareConnectionConfig) GetMqttSubscribeTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MqttSubscribeTopic, true
}

// SetMqttSubscribeTopic sets field value
func (o *WaveshareConnectionConfig) SetMqttSubscribeTopic(v string) {
	o.MqttSubscribeTopic = v
}

// GetMqttUsername returns the MqttUsername field value
func (o *WaveshareConnectionConfig) GetMqttUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MqttUsername
}

// GetMqttUsernameOk returns a tuple with the MqttUsername field value
// and a boolean to check if the value has been set.
func (o *WaveshareConnectionConfig) GetMqttUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MqttUsername, true
}

// SetMqttUsername sets field value
func (o *WaveshareConnectionConfig) SetMqttUsername(v string) {
	o.MqttUsername = v
}

func (o WaveshareConnectionConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mqtt_client_id"] = o.MqttClientId
	toSerialize["mqtt_password"] = o.MqttPassword
	toSerialize["mqtt_publish_topic"] = o.MqttPublishTopic
	toSerialize["mqtt_subscribe_topic"] = o.MqttSubscribeTopic
	toSerialize["mqtt_username"] = o.MqttUsername
	return toSerialize, nil
}

func (o *WaveshareConnectionConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mqtt_client_id",
		"mqtt_password",
		"mqtt_publish_topic",
		"mqtt_subscribe_topic",
		"mqtt_username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWaveshareConnectionConfig := _WaveshareConnectionConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWaveshareConnectionConfig)

	if err != nil {
		return err
	}

	*o = WaveshareConnectionConfig(varWaveshareConnectionConfig)

	return err
}

type NullableWaveshareConnectionConfig struct {
	value *WaveshareConnectionConfig
	isSet bool
}

func (v NullableWaveshareConnectionConfig) Get() *WaveshareConnectionConfig {
	return v.value
}

func (v *NullableWaveshareConnectionConfig) Set(val *WaveshareConnectionConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableWaveshareConnectionConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableWaveshareConnectionConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWaveshareConnectionConfig(val *WaveshareConnectionConfig) *NullableWaveshareConnectionConfig {
	return &NullableWaveshareConnectionConfig{value: val, isSet: true}
}

func (v NullableWaveshareConnectionConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWaveshareConnectionConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
