/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SetResourceKeepRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetResourceKeepRequest{}

// SetResourceKeepRequest struct for SetResourceKeepRequest
type SetResourceKeepRequest struct {
	// `true` pins the resource (kept within cap); `false` lets it be flagged as excess.
	Keep bool `json:"keep"`
	// Which capacity resource the row belongs to.
	Resource CapacityResource `json:"resource"`
	// The resource id to pin or unpin.
	ResourceId string `json:"resource_id"`
}

type _SetResourceKeepRequest SetResourceKeepRequest

// NewSetResourceKeepRequest instantiates a new SetResourceKeepRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetResourceKeepRequest(keep bool, resource CapacityResource, resourceId string) *SetResourceKeepRequest {
	this := SetResourceKeepRequest{}
	this.Keep = keep
	this.Resource = resource
	this.ResourceId = resourceId
	return &this
}

// NewSetResourceKeepRequestWithDefaults instantiates a new SetResourceKeepRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetResourceKeepRequestWithDefaults() *SetResourceKeepRequest {
	this := SetResourceKeepRequest{}
	return &this
}

// GetKeep returns the Keep field value
func (o *SetResourceKeepRequest) GetKeep() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Keep
}

// GetKeepOk returns a tuple with the Keep field value
// and a boolean to check if the value has been set.
func (o *SetResourceKeepRequest) GetKeepOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Keep, true
}

// SetKeep sets field value
func (o *SetResourceKeepRequest) SetKeep(v bool) {
	o.Keep = v
}

// GetResource returns the Resource field value
func (o *SetResourceKeepRequest) GetResource() CapacityResource {
	if o == nil {
		var ret CapacityResource
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *SetResourceKeepRequest) GetResourceOk() (*CapacityResource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *SetResourceKeepRequest) SetResource(v CapacityResource) {
	o.Resource = v
}

// GetResourceId returns the ResourceId field value
func (o *SetResourceKeepRequest) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *SetResourceKeepRequest) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *SetResourceKeepRequest) SetResourceId(v string) {
	o.ResourceId = v
}

func (o SetResourceKeepRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keep"] = o.Keep
	toSerialize["resource"] = o.Resource
	toSerialize["resource_id"] = o.ResourceId
	return toSerialize, nil
}

func (o *SetResourceKeepRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keep",
		"resource",
		"resource_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetResourceKeepRequest := _SetResourceKeepRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetResourceKeepRequest)

	if err != nil {
		return err
	}

	*o = SetResourceKeepRequest(varSetResourceKeepRequest)

	return err
}

type NullableSetResourceKeepRequest struct {
	value *SetResourceKeepRequest
	isSet bool
}

func (v NullableSetResourceKeepRequest) Get() *SetResourceKeepRequest {
	return v.value
}

func (v *NullableSetResourceKeepRequest) Set(val *SetResourceKeepRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetResourceKeepRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetResourceKeepRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetResourceKeepRequest(val *SetResourceKeepRequest) *NullableSetResourceKeepRequest {
	return &NullableSetResourceKeepRequest{value: val, isSet: true}
}

func (v NullableSetResourceKeepRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetResourceKeepRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
