/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProposeGroupPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProposeGroupPayload{}

// ProposeGroupPayload struct for ProposeGroupPayload
type ProposeGroupPayload struct {
	DisclosureAcknowledged bool `json:"disclosure_acknowledged"`
	// The site (integration) to propose the household to.
	IntegrationId string `json:"integration_id"`
}

type _ProposeGroupPayload ProposeGroupPayload

// NewProposeGroupPayload instantiates a new ProposeGroupPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProposeGroupPayload(disclosureAcknowledged bool, integrationId string) *ProposeGroupPayload {
	this := ProposeGroupPayload{}
	this.DisclosureAcknowledged = disclosureAcknowledged
	this.IntegrationId = integrationId
	return &this
}

// NewProposeGroupPayloadWithDefaults instantiates a new ProposeGroupPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProposeGroupPayloadWithDefaults() *ProposeGroupPayload {
	this := ProposeGroupPayload{}
	return &this
}

// GetDisclosureAcknowledged returns the DisclosureAcknowledged field value
func (o *ProposeGroupPayload) GetDisclosureAcknowledged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DisclosureAcknowledged
}

// GetDisclosureAcknowledgedOk returns a tuple with the DisclosureAcknowledged field value
// and a boolean to check if the value has been set.
func (o *ProposeGroupPayload) GetDisclosureAcknowledgedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisclosureAcknowledged, true
}

// SetDisclosureAcknowledged sets field value
func (o *ProposeGroupPayload) SetDisclosureAcknowledged(v bool) {
	o.DisclosureAcknowledged = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *ProposeGroupPayload) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *ProposeGroupPayload) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *ProposeGroupPayload) SetIntegrationId(v string) {
	o.IntegrationId = v
}

func (o ProposeGroupPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["disclosure_acknowledged"] = o.DisclosureAcknowledged
	toSerialize["integration_id"] = o.IntegrationId
	return toSerialize, nil
}

func (o *ProposeGroupPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disclosure_acknowledged",
		"integration_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProposeGroupPayload := _ProposeGroupPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProposeGroupPayload)

	if err != nil {
		return err
	}

	*o = ProposeGroupPayload(varProposeGroupPayload)

	return err
}

type NullableProposeGroupPayload struct {
	value *ProposeGroupPayload
	isSet bool
}

func (v NullableProposeGroupPayload) Get() *ProposeGroupPayload {
	return v.value
}

func (v *NullableProposeGroupPayload) Set(val *ProposeGroupPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableProposeGroupPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableProposeGroupPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProposeGroupPayload(val *ProposeGroupPayload) *NullableProposeGroupPayload {
	return &NullableProposeGroupPayload{value: val, isSet: true}
}

func (v NullableProposeGroupPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProposeGroupPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
