/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AuditSource Surface that originated the action.
type AuditSource string

// List of AuditSource
const (
	AUDITSOURCE_API           AuditSource = "api"
	AUDITSOURCE_DASHBOARD     AuditSource = "dashboard"
	AUDITSOURCE_PUBLIC_ACCESS AuditSource = "public_access"
	AUDITSOURCE_SMARTHOME     AuditSource = "smarthome"
	AUDITSOURCE_SCRIPTING     AuditSource = "scripting"
	AUDITSOURCE_SYSTEM        AuditSource = "system"
)

// All allowed values of AuditSource enum
var AllowedAuditSourceEnumValues = []AuditSource{
	"api",
	"dashboard",
	"public_access",
	"smarthome",
	"scripting",
	"system",
}

func (v *AuditSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuditSource(value)
	for _, existing := range AllowedAuditSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuditSource", value)
}

// NewAuditSourceFromValue returns a pointer to a valid AuditSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuditSourceFromValue(v string) (*AuditSource, error) {
	ev := AuditSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuditSource: valid values are %v", v, AllowedAuditSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuditSource) IsValid() bool {
	for _, existing := range AllowedAuditSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuditSource value
func (v AuditSource) Ptr() *AuditSource {
	return &v
}

type NullableAuditSource struct {
	value *AuditSource
	isSet bool
}

func (v NullableAuditSource) Get() *AuditSource {
	return v.value
}

func (v *NullableAuditSource) Set(val *AuditSource) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditSource) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditSource(val *AuditSource) *NullableAuditSource {
	return &NullableAuditSource{value: val, isSet: true}
}

func (v NullableAuditSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
