/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ResourceLifecycle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceLifecycle{}

// ResourceLifecycle Soft-delete and audit timestamps on a persisted resource.  Flattened onto HTTP JSON so `created_at` sits next to `id` / `name`. Absent fields are omitted (`None`).
type ResourceLifecycle struct {
	CreatedAt    NullableTime `json:"created_at,omitempty"`
	DeletedAt    NullableTime `json:"deleted_at,omitempty"`
	HardDeleteAt NullableTime `json:"hard_delete_at,omitempty"`
	PurgeAt      NullableTime `json:"purge_at,omitempty"`
	UpdatedAt    NullableTime `json:"updated_at,omitempty"`
}

// NewResourceLifecycle instantiates a new ResourceLifecycle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceLifecycle() *ResourceLifecycle {
	this := ResourceLifecycle{}
	return &this
}

// NewResourceLifecycleWithDefaults instantiates a new ResourceLifecycle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceLifecycleWithDefaults() *ResourceLifecycle {
	this := ResourceLifecycle{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceLifecycle) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceLifecycle) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ResourceLifecycle) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *ResourceLifecycle) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *ResourceLifecycle) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *ResourceLifecycle) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceLifecycle) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceLifecycle) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *ResourceLifecycle) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *ResourceLifecycle) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}

// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *ResourceLifecycle) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *ResourceLifecycle) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetHardDeleteAt returns the HardDeleteAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceLifecycle) GetHardDeleteAt() time.Time {
	if o == nil || IsNil(o.HardDeleteAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.HardDeleteAt.Get()
}

// GetHardDeleteAtOk returns a tuple with the HardDeleteAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceLifecycle) GetHardDeleteAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.HardDeleteAt.Get(), o.HardDeleteAt.IsSet()
}

// HasHardDeleteAt returns a boolean if a field has been set.
func (o *ResourceLifecycle) HasHardDeleteAt() bool {
	if o != nil && o.HardDeleteAt.IsSet() {
		return true
	}

	return false
}

// SetHardDeleteAt gets a reference to the given NullableTime and assigns it to the HardDeleteAt field.
func (o *ResourceLifecycle) SetHardDeleteAt(v time.Time) {
	o.HardDeleteAt.Set(&v)
}

// SetHardDeleteAtNil sets the value for HardDeleteAt to be an explicit nil
func (o *ResourceLifecycle) SetHardDeleteAtNil() {
	o.HardDeleteAt.Set(nil)
}

// UnsetHardDeleteAt ensures that no value is present for HardDeleteAt, not even an explicit nil
func (o *ResourceLifecycle) UnsetHardDeleteAt() {
	o.HardDeleteAt.Unset()
}

// GetPurgeAt returns the PurgeAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceLifecycle) GetPurgeAt() time.Time {
	if o == nil || IsNil(o.PurgeAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PurgeAt.Get()
}

// GetPurgeAtOk returns a tuple with the PurgeAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceLifecycle) GetPurgeAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurgeAt.Get(), o.PurgeAt.IsSet()
}

// HasPurgeAt returns a boolean if a field has been set.
func (o *ResourceLifecycle) HasPurgeAt() bool {
	if o != nil && o.PurgeAt.IsSet() {
		return true
	}

	return false
}

// SetPurgeAt gets a reference to the given NullableTime and assigns it to the PurgeAt field.
func (o *ResourceLifecycle) SetPurgeAt(v time.Time) {
	o.PurgeAt.Set(&v)
}

// SetPurgeAtNil sets the value for PurgeAt to be an explicit nil
func (o *ResourceLifecycle) SetPurgeAtNil() {
	o.PurgeAt.Set(nil)
}

// UnsetPurgeAt ensures that no value is present for PurgeAt, not even an explicit nil
func (o *ResourceLifecycle) UnsetPurgeAt() {
	o.PurgeAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceLifecycle) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceLifecycle) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ResourceLifecycle) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *ResourceLifecycle) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *ResourceLifecycle) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *ResourceLifecycle) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o ResourceLifecycle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	if o.HardDeleteAt.IsSet() {
		toSerialize["hard_delete_at"] = o.HardDeleteAt.Get()
	}
	if o.PurgeAt.IsSet() {
		toSerialize["purge_at"] = o.PurgeAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

type NullableResourceLifecycle struct {
	value *ResourceLifecycle
	isSet bool
}

func (v NullableResourceLifecycle) Get() *ResourceLifecycle {
	return v.value
}

func (v *NullableResourceLifecycle) Set(val *ResourceLifecycle) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceLifecycle) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceLifecycle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceLifecycle(val *ResourceLifecycle) *NullableResourceLifecycle {
	return &NullableResourceLifecycle{value: val, isSet: true}
}

func (v NullableResourceLifecycle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceLifecycle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
