/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InviteScheduleSnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteScheduleSnapshot{}

// InviteScheduleSnapshot struct for InviteScheduleSnapshot
type InviteScheduleSnapshot struct {
	ActiveWindow        NullableInviteWindow              `json:"active_window,omitempty"`
	IsRecurring         bool                              `json:"is_recurring"`
	NextWindow          NullableInviteWindow              `json:"next_window,omitempty"`
	SeriesEnd           NullableInviteRecurrenceSeriesEnd `json:"series_end,omitempty"`
	SlotDurationSeconds int64                             `json:"slot_duration_seconds"`
}

type _InviteScheduleSnapshot InviteScheduleSnapshot

// NewInviteScheduleSnapshot instantiates a new InviteScheduleSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteScheduleSnapshot(isRecurring bool, slotDurationSeconds int64) *InviteScheduleSnapshot {
	this := InviteScheduleSnapshot{}
	this.IsRecurring = isRecurring
	this.SlotDurationSeconds = slotDurationSeconds
	return &this
}

// NewInviteScheduleSnapshotWithDefaults instantiates a new InviteScheduleSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteScheduleSnapshotWithDefaults() *InviteScheduleSnapshot {
	this := InviteScheduleSnapshot{}
	return &this
}

// GetActiveWindow returns the ActiveWindow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteScheduleSnapshot) GetActiveWindow() InviteWindow {
	if o == nil || IsNil(o.ActiveWindow.Get()) {
		var ret InviteWindow
		return ret
	}
	return *o.ActiveWindow.Get()
}

// GetActiveWindowOk returns a tuple with the ActiveWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteScheduleSnapshot) GetActiveWindowOk() (*InviteWindow, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveWindow.Get(), o.ActiveWindow.IsSet()
}

// HasActiveWindow returns a boolean if a field has been set.
func (o *InviteScheduleSnapshot) HasActiveWindow() bool {
	if o != nil && o.ActiveWindow.IsSet() {
		return true
	}

	return false
}

// SetActiveWindow gets a reference to the given NullableInviteWindow and assigns it to the ActiveWindow field.
func (o *InviteScheduleSnapshot) SetActiveWindow(v InviteWindow) {
	o.ActiveWindow.Set(&v)
}

// SetActiveWindowNil sets the value for ActiveWindow to be an explicit nil
func (o *InviteScheduleSnapshot) SetActiveWindowNil() {
	o.ActiveWindow.Set(nil)
}

// UnsetActiveWindow ensures that no value is present for ActiveWindow, not even an explicit nil
func (o *InviteScheduleSnapshot) UnsetActiveWindow() {
	o.ActiveWindow.Unset()
}

// GetIsRecurring returns the IsRecurring field value
func (o *InviteScheduleSnapshot) GetIsRecurring() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRecurring
}

// GetIsRecurringOk returns a tuple with the IsRecurring field value
// and a boolean to check if the value has been set.
func (o *InviteScheduleSnapshot) GetIsRecurringOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRecurring, true
}

// SetIsRecurring sets field value
func (o *InviteScheduleSnapshot) SetIsRecurring(v bool) {
	o.IsRecurring = v
}

// GetNextWindow returns the NextWindow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteScheduleSnapshot) GetNextWindow() InviteWindow {
	if o == nil || IsNil(o.NextWindow.Get()) {
		var ret InviteWindow
		return ret
	}
	return *o.NextWindow.Get()
}

// GetNextWindowOk returns a tuple with the NextWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteScheduleSnapshot) GetNextWindowOk() (*InviteWindow, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextWindow.Get(), o.NextWindow.IsSet()
}

// HasNextWindow returns a boolean if a field has been set.
func (o *InviteScheduleSnapshot) HasNextWindow() bool {
	if o != nil && o.NextWindow.IsSet() {
		return true
	}

	return false
}

// SetNextWindow gets a reference to the given NullableInviteWindow and assigns it to the NextWindow field.
func (o *InviteScheduleSnapshot) SetNextWindow(v InviteWindow) {
	o.NextWindow.Set(&v)
}

// SetNextWindowNil sets the value for NextWindow to be an explicit nil
func (o *InviteScheduleSnapshot) SetNextWindowNil() {
	o.NextWindow.Set(nil)
}

// UnsetNextWindow ensures that no value is present for NextWindow, not even an explicit nil
func (o *InviteScheduleSnapshot) UnsetNextWindow() {
	o.NextWindow.Unset()
}

// GetSeriesEnd returns the SeriesEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InviteScheduleSnapshot) GetSeriesEnd() InviteRecurrenceSeriesEnd {
	if o == nil || IsNil(o.SeriesEnd.Get()) {
		var ret InviteRecurrenceSeriesEnd
		return ret
	}
	return *o.SeriesEnd.Get()
}

// GetSeriesEndOk returns a tuple with the SeriesEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InviteScheduleSnapshot) GetSeriesEndOk() (*InviteRecurrenceSeriesEnd, bool) {
	if o == nil {
		return nil, false
	}
	return o.SeriesEnd.Get(), o.SeriesEnd.IsSet()
}

// HasSeriesEnd returns a boolean if a field has been set.
func (o *InviteScheduleSnapshot) HasSeriesEnd() bool {
	if o != nil && o.SeriesEnd.IsSet() {
		return true
	}

	return false
}

// SetSeriesEnd gets a reference to the given NullableInviteRecurrenceSeriesEnd and assigns it to the SeriesEnd field.
func (o *InviteScheduleSnapshot) SetSeriesEnd(v InviteRecurrenceSeriesEnd) {
	o.SeriesEnd.Set(&v)
}

// SetSeriesEndNil sets the value for SeriesEnd to be an explicit nil
func (o *InviteScheduleSnapshot) SetSeriesEndNil() {
	o.SeriesEnd.Set(nil)
}

// UnsetSeriesEnd ensures that no value is present for SeriesEnd, not even an explicit nil
func (o *InviteScheduleSnapshot) UnsetSeriesEnd() {
	o.SeriesEnd.Unset()
}

// GetSlotDurationSeconds returns the SlotDurationSeconds field value
func (o *InviteScheduleSnapshot) GetSlotDurationSeconds() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SlotDurationSeconds
}

// GetSlotDurationSecondsOk returns a tuple with the SlotDurationSeconds field value
// and a boolean to check if the value has been set.
func (o *InviteScheduleSnapshot) GetSlotDurationSecondsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlotDurationSeconds, true
}

// SetSlotDurationSeconds sets field value
func (o *InviteScheduleSnapshot) SetSlotDurationSeconds(v int64) {
	o.SlotDurationSeconds = v
}

func (o InviteScheduleSnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ActiveWindow.IsSet() {
		toSerialize["active_window"] = o.ActiveWindow.Get()
	}
	toSerialize["is_recurring"] = o.IsRecurring
	if o.NextWindow.IsSet() {
		toSerialize["next_window"] = o.NextWindow.Get()
	}
	if o.SeriesEnd.IsSet() {
		toSerialize["series_end"] = o.SeriesEnd.Get()
	}
	toSerialize["slot_duration_seconds"] = o.SlotDurationSeconds
	return toSerialize, nil
}

func (o *InviteScheduleSnapshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_recurring",
		"slot_duration_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteScheduleSnapshot := _InviteScheduleSnapshot{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteScheduleSnapshot)

	if err != nil {
		return err
	}

	*o = InviteScheduleSnapshot(varInviteScheduleSnapshot)

	return err
}

type NullableInviteScheduleSnapshot struct {
	value *InviteScheduleSnapshot
	isSet bool
}

func (v NullableInviteScheduleSnapshot) Get() *InviteScheduleSnapshot {
	return v.value
}

func (v *NullableInviteScheduleSnapshot) Set(val *InviteScheduleSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteScheduleSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteScheduleSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteScheduleSnapshot(val *InviteScheduleSnapshot) *NullableInviteScheduleSnapshot {
	return &NullableInviteScheduleSnapshot{value: val, isSet: true}
}

func (v NullableInviteScheduleSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteScheduleSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
