/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DirectoryFloorSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryFloorSummary{}

// DirectoryFloorSummary One distinct floor row for a directory device (directory listing entities).
type DirectoryFloorSummary struct {
	Floor       interface{}   `json:"floor"`
	FloorNumber NullableInt64 `json:"floor_number,omitempty"`
	Key         string        `json:"key"`
}

type _DirectoryFloorSummary DirectoryFloorSummary

// NewDirectoryFloorSummary instantiates a new DirectoryFloorSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryFloorSummary(floor interface{}, key string) *DirectoryFloorSummary {
	this := DirectoryFloorSummary{}
	this.Floor = floor
	this.Key = key
	return &this
}

// NewDirectoryFloorSummaryWithDefaults instantiates a new DirectoryFloorSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryFloorSummaryWithDefaults() *DirectoryFloorSummary {
	this := DirectoryFloorSummary{}
	return &this
}

// GetFloor returns the Floor field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DirectoryFloorSummary) GetFloor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Floor
}

// GetFloorOk returns a tuple with the Floor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DirectoryFloorSummary) GetFloorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Floor) {
		return nil, false
	}
	return &o.Floor, true
}

// SetFloor sets field value
func (o *DirectoryFloorSummary) SetFloor(v interface{}) {
	o.Floor = v
}

// GetFloorNumber returns the FloorNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DirectoryFloorSummary) GetFloorNumber() int64 {
	if o == nil || IsNil(o.FloorNumber.Get()) {
		var ret int64
		return ret
	}
	return *o.FloorNumber.Get()
}

// GetFloorNumberOk returns a tuple with the FloorNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DirectoryFloorSummary) GetFloorNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FloorNumber.Get(), o.FloorNumber.IsSet()
}

// HasFloorNumber returns a boolean if a field has been set.
func (o *DirectoryFloorSummary) HasFloorNumber() bool {
	if o != nil && o.FloorNumber.IsSet() {
		return true
	}

	return false
}

// SetFloorNumber gets a reference to the given NullableInt64 and assigns it to the FloorNumber field.
func (o *DirectoryFloorSummary) SetFloorNumber(v int64) {
	o.FloorNumber.Set(&v)
}

// SetFloorNumberNil sets the value for FloorNumber to be an explicit nil
func (o *DirectoryFloorSummary) SetFloorNumberNil() {
	o.FloorNumber.Set(nil)
}

// UnsetFloorNumber ensures that no value is present for FloorNumber, not even an explicit nil
func (o *DirectoryFloorSummary) UnsetFloorNumber() {
	o.FloorNumber.Unset()
}

// GetKey returns the Key field value
func (o *DirectoryFloorSummary) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *DirectoryFloorSummary) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *DirectoryFloorSummary) SetKey(v string) {
	o.Key = v
}

func (o DirectoryFloorSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Floor != nil {
		toSerialize["floor"] = o.Floor
	}
	if o.FloorNumber.IsSet() {
		toSerialize["floor_number"] = o.FloorNumber.Get()
	}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *DirectoryFloorSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"floor",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectoryFloorSummary := _DirectoryFloorSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectoryFloorSummary)

	if err != nil {
		return err
	}

	*o = DirectoryFloorSummary(varDirectoryFloorSummary)

	return err
}

type NullableDirectoryFloorSummary struct {
	value *DirectoryFloorSummary
	isSet bool
}

func (v NullableDirectoryFloorSummary) Get() *DirectoryFloorSummary {
	return v.value
}

func (v *NullableDirectoryFloorSummary) Set(val *DirectoryFloorSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryFloorSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryFloorSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryFloorSummary(val *DirectoryFloorSummary) *NullableDirectoryFloorSummary {
	return &NullableDirectoryFloorSummary{value: val, isSet: true}
}

func (v NullableDirectoryFloorSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryFloorSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
