/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SingleResourceOutputOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SingleResourceOutputOptions{}

// SingleResourceOutputOptions Options for single-resource operations (get/create/update/delete/restore). Used when listing/filtering by `only_deleted` is not applicable.
type SingleResourceOutputOptions struct {
	// If true, include soft-deleted items in results.
	IncludeDeleted bool `json:"include_deleted"`
}

type _SingleResourceOutputOptions SingleResourceOutputOptions

// NewSingleResourceOutputOptions instantiates a new SingleResourceOutputOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSingleResourceOutputOptions(includeDeleted bool) *SingleResourceOutputOptions {
	this := SingleResourceOutputOptions{}
	this.IncludeDeleted = includeDeleted
	return &this
}

// NewSingleResourceOutputOptionsWithDefaults instantiates a new SingleResourceOutputOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSingleResourceOutputOptionsWithDefaults() *SingleResourceOutputOptions {
	this := SingleResourceOutputOptions{}
	return &this
}

// GetIncludeDeleted returns the IncludeDeleted field value
func (o *SingleResourceOutputOptions) GetIncludeDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeDeleted
}

// GetIncludeDeletedOk returns a tuple with the IncludeDeleted field value
// and a boolean to check if the value has been set.
func (o *SingleResourceOutputOptions) GetIncludeDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeDeleted, true
}

// SetIncludeDeleted sets field value
func (o *SingleResourceOutputOptions) SetIncludeDeleted(v bool) {
	o.IncludeDeleted = v
}

func (o SingleResourceOutputOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["include_deleted"] = o.IncludeDeleted
	return toSerialize, nil
}

func (o *SingleResourceOutputOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"include_deleted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSingleResourceOutputOptions := _SingleResourceOutputOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSingleResourceOutputOptions)

	if err != nil {
		return err
	}

	*o = SingleResourceOutputOptions(varSingleResourceOutputOptions)

	return err
}

type NullableSingleResourceOutputOptions struct {
	value *SingleResourceOutputOptions
	isSet bool
}

func (v NullableSingleResourceOutputOptions) Get() *SingleResourceOutputOptions {
	return v.value
}

func (v *NullableSingleResourceOutputOptions) Set(val *SingleResourceOutputOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableSingleResourceOutputOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableSingleResourceOutputOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSingleResourceOutputOptions(val *SingleResourceOutputOptions) *NullableSingleResourceOutputOptions {
	return &NullableSingleResourceOutputOptions{value: val, isSet: true}
}

func (v NullableSingleResourceOutputOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSingleResourceOutputOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
