/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TransferIntegrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferIntegrationRequest{}

// TransferIntegrationRequest struct for TransferIntegrationRequest
type TransferIntegrationRequest struct {
	// Must be `true` when the preview reports side-effect warnings; otherwise the request is rejected with `error_code = \"confirmation_required\"`.
	Confirm *bool            `json:"confirm,omitempty"`
	Mode    *TransferModeDto `json:"mode,omitempty"`
	// Destination organization id (must differ from the integration's current org).
	TargetOrgId string `json:"target_org_id"`
}

type _TransferIntegrationRequest TransferIntegrationRequest

// NewTransferIntegrationRequest instantiates a new TransferIntegrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferIntegrationRequest(targetOrgId string) *TransferIntegrationRequest {
	this := TransferIntegrationRequest{}
	this.TargetOrgId = targetOrgId
	return &this
}

// NewTransferIntegrationRequestWithDefaults instantiates a new TransferIntegrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferIntegrationRequestWithDefaults() *TransferIntegrationRequest {
	this := TransferIntegrationRequest{}
	return &this
}

// GetConfirm returns the Confirm field value if set, zero value otherwise.
func (o *TransferIntegrationRequest) GetConfirm() bool {
	if o == nil || IsNil(o.Confirm) {
		var ret bool
		return ret
	}
	return *o.Confirm
}

// GetConfirmOk returns a tuple with the Confirm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferIntegrationRequest) GetConfirmOk() (*bool, bool) {
	if o == nil || IsNil(o.Confirm) {
		return nil, false
	}
	return o.Confirm, true
}

// HasConfirm returns a boolean if a field has been set.
func (o *TransferIntegrationRequest) HasConfirm() bool {
	if o != nil && !IsNil(o.Confirm) {
		return true
	}

	return false
}

// SetConfirm gets a reference to the given bool and assigns it to the Confirm field.
func (o *TransferIntegrationRequest) SetConfirm(v bool) {
	o.Confirm = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *TransferIntegrationRequest) GetMode() TransferModeDto {
	if o == nil || IsNil(o.Mode) {
		var ret TransferModeDto
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferIntegrationRequest) GetModeOk() (*TransferModeDto, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *TransferIntegrationRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given TransferModeDto and assigns it to the Mode field.
func (o *TransferIntegrationRequest) SetMode(v TransferModeDto) {
	o.Mode = &v
}

// GetTargetOrgId returns the TargetOrgId field value
func (o *TransferIntegrationRequest) GetTargetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetOrgId
}

// GetTargetOrgIdOk returns a tuple with the TargetOrgId field value
// and a boolean to check if the value has been set.
func (o *TransferIntegrationRequest) GetTargetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetOrgId, true
}

// SetTargetOrgId sets field value
func (o *TransferIntegrationRequest) SetTargetOrgId(v string) {
	o.TargetOrgId = v
}

func (o TransferIntegrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Confirm) {
		toSerialize["confirm"] = o.Confirm
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	toSerialize["target_org_id"] = o.TargetOrgId
	return toSerialize, nil
}

func (o *TransferIntegrationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target_org_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferIntegrationRequest := _TransferIntegrationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferIntegrationRequest)

	if err != nil {
		return err
	}

	*o = TransferIntegrationRequest(varTransferIntegrationRequest)

	return err
}

type NullableTransferIntegrationRequest struct {
	value *TransferIntegrationRequest
	isSet bool
}

func (v NullableTransferIntegrationRequest) Get() *TransferIntegrationRequest {
	return v.value
}

func (v *NullableTransferIntegrationRequest) Set(val *TransferIntegrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferIntegrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferIntegrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferIntegrationRequest(val *TransferIntegrationRequest) *NullableTransferIntegrationRequest {
	return &NullableTransferIntegrationRequest{value: val, isSet: true}
}

func (v NullableTransferIntegrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferIntegrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
