/*
OpenApp API

IoT Device Management (Gates/Doors/Provisioning) API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateInventoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInventoryRequest{}

// CreateInventoryRequest struct for CreateInventoryRequest
type CreateInventoryRequest struct {
	IsActive      NullableBool  `json:"is_active,omitempty"`
	PriceCents    int64         `json:"price_cents"`
	ProductId     string        `json:"product_id"`
	StockQuantity NullableInt32 `json:"stock_quantity,omitempty"`
}

type _CreateInventoryRequest CreateInventoryRequest

// NewCreateInventoryRequest instantiates a new CreateInventoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInventoryRequest(priceCents int64, productId string) *CreateInventoryRequest {
	this := CreateInventoryRequest{}
	this.PriceCents = priceCents
	this.ProductId = productId
	return &this
}

// NewCreateInventoryRequestWithDefaults instantiates a new CreateInventoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInventoryRequestWithDefaults() *CreateInventoryRequest {
	this := CreateInventoryRequest{}
	return &this
}

// GetIsActive returns the IsActive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateInventoryRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive.Get()) {
		var ret bool
		return ret
	}
	return *o.IsActive.Get()
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateInventoryRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsActive.Get(), o.IsActive.IsSet()
}

// HasIsActive returns a boolean if a field has been set.
func (o *CreateInventoryRequest) HasIsActive() bool {
	if o != nil && o.IsActive.IsSet() {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given NullableBool and assigns it to the IsActive field.
func (o *CreateInventoryRequest) SetIsActive(v bool) {
	o.IsActive.Set(&v)
}

// SetIsActiveNil sets the value for IsActive to be an explicit nil
func (o *CreateInventoryRequest) SetIsActiveNil() {
	o.IsActive.Set(nil)
}

// UnsetIsActive ensures that no value is present for IsActive, not even an explicit nil
func (o *CreateInventoryRequest) UnsetIsActive() {
	o.IsActive.Unset()
}

// GetPriceCents returns the PriceCents field value
func (o *CreateInventoryRequest) GetPriceCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PriceCents
}

// GetPriceCentsOk returns a tuple with the PriceCents field value
// and a boolean to check if the value has been set.
func (o *CreateInventoryRequest) GetPriceCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceCents, true
}

// SetPriceCents sets field value
func (o *CreateInventoryRequest) SetPriceCents(v int64) {
	o.PriceCents = v
}

// GetProductId returns the ProductId field value
func (o *CreateInventoryRequest) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *CreateInventoryRequest) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *CreateInventoryRequest) SetProductId(v string) {
	o.ProductId = v
}

// GetStockQuantity returns the StockQuantity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateInventoryRequest) GetStockQuantity() int32 {
	if o == nil || IsNil(o.StockQuantity.Get()) {
		var ret int32
		return ret
	}
	return *o.StockQuantity.Get()
}

// GetStockQuantityOk returns a tuple with the StockQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateInventoryRequest) GetStockQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StockQuantity.Get(), o.StockQuantity.IsSet()
}

// HasStockQuantity returns a boolean if a field has been set.
func (o *CreateInventoryRequest) HasStockQuantity() bool {
	if o != nil && o.StockQuantity.IsSet() {
		return true
	}

	return false
}

// SetStockQuantity gets a reference to the given NullableInt32 and assigns it to the StockQuantity field.
func (o *CreateInventoryRequest) SetStockQuantity(v int32) {
	o.StockQuantity.Set(&v)
}

// SetStockQuantityNil sets the value for StockQuantity to be an explicit nil
func (o *CreateInventoryRequest) SetStockQuantityNil() {
	o.StockQuantity.Set(nil)
}

// UnsetStockQuantity ensures that no value is present for StockQuantity, not even an explicit nil
func (o *CreateInventoryRequest) UnsetStockQuantity() {
	o.StockQuantity.Unset()
}

func (o CreateInventoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IsActive.IsSet() {
		toSerialize["is_active"] = o.IsActive.Get()
	}
	toSerialize["price_cents"] = o.PriceCents
	toSerialize["product_id"] = o.ProductId
	if o.StockQuantity.IsSet() {
		toSerialize["stock_quantity"] = o.StockQuantity.Get()
	}
	return toSerialize, nil
}

func (o *CreateInventoryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"price_cents",
		"product_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInventoryRequest := _CreateInventoryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInventoryRequest)

	if err != nil {
		return err
	}

	*o = CreateInventoryRequest(varCreateInventoryRequest)

	return err
}

type NullableCreateInventoryRequest struct {
	value *CreateInventoryRequest
	isSet bool
}

func (v NullableCreateInventoryRequest) Get() *CreateInventoryRequest {
	return v.value
}

func (v *NullableCreateInventoryRequest) Set(val *CreateInventoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInventoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInventoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInventoryRequest(val *CreateInventoryRequest) *NullableCreateInventoryRequest {
	return &NullableCreateInventoryRequest{value: val, isSet: true}
}

func (v NullableCreateInventoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInventoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
